### ISSUE TITLE
[Bug]: 一旦添加所有设备进HA后，在米家APP中更改设备房间，HA中不会同步更改

### ISSUE THREAD

**Issue by MaoZ1993** [XiaoMi/ha_xiaomi_home#103]
### Describe the bug / 描述问题

一旦添加所有设备进HA后，在米家APP中更改设备房间，HA中不会同步更改

### To Reproduce / 复现步骤

添加小米账号，添加设备到HA，通过米家更改设备房间，到HA中更新设备信息，能看到侧边栏提示检测到设备变动，但实际并未在HA中更新设备位置

### Expected behavior / 预期结果

HA更新房间信息

### Home Assistant Core version / Home Assistant Core 版本

2024.12

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

0.1.0

### Additional context / 其他说明

如果在米家APP中修改房间名，HA中也不会对应更新

**Comment by nicelake** [comment]
房间信息不会更新到米家App中，HA的房间信息是独立的一套，只有在第一次导入时带入，之后需要自行在HA中设置

**Comment by JimmyKmi** [comment]
HA设备列表及绑定的家庭不会实时更改，需要手动更新集成。详情README

**Comment by SusanPhevos** [comment]
设计如此

**Comment by topsworld** [comment]
如上，非问题，issue 关闭
