### ISSUE TITLE
[Bug]: 杜亚卷帘控制器无法控制开合角度

### ISSUE THREAD

**Issue by tiandeyu** [XiaoMi/ha_xiaomi_home#11]
### Describe the bug / 描述问题

杜亚卷帘控制器无法控制开合角度

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/def8b604-ce5b-492d-b6df-666d415e668d)

### Expected behavior / 预期结果

可以控制开合角度

### Home Assistant Core version / Home Assistant Core 版本

2024.13.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by catsimple** [comment]
curtain实体里

**Comment by topsworld** [comment]
如上，可以打开Curtain实体调节开合角度，issue关闭，如果未解决可reopen

**Comment by tiandeyu** [comment]
抱歉，我的issue描述有误，卷帘应该具备开合角度、遮光角度2种特性
开启curtain模式，只有开合角度，没有遮光角度
![image](https://github.com/user-attachments/assets/6d125161-fba6-41a4-9ddc-ecb723cd809d)
![image](https://github.com/user-attachments/assets/731a1645-c71a-406b-8ed1-5bd6100a70d2)
我预期的应该是这样，这是我自己写的窗帘插件
![image](https://github.com/user-attachments/assets/be6c8bd0-d988-45f4-a237-2c432ee6b087)

据我了解，杜亚卷帘是使用行程的最后5%来控制遮光，米家App上面使用的是短行程开控制遮光角度，要到行程末尾才有效
