### ISSUE TITLE
[Bug]: 领普人体存在传感器ES3 存在传感器 有人无人状态不是二元传感器

### ISSUE THREAD

**Issue by Skyearn** [XiaoMi/ha_xiaomi_home#110]
### Describe the bug / 描述问题

可能的状态只有有人和无人两种，但是属性里能看到很多个有人状态

### To Reproduce / 复现步骤

领普人体存在传感器ES3 接入米家，米家使用 xiaomi home 接入。就可以看到有人无人的属性下无人和很多有人。这应该做成二元传感器就好了。这样也能很方便的 HomeKit bridge 接入。

![10151734441471_ pic](https://github.com/user-attachments/assets/e759886d-7dca-4f6d-8bc3-83fa26d4808b)

### Expected behavior / 预期结果

二元传感器。有人/无人

### Home Assistant Core version / Home Assistant Core 版本

2024.12.03

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by myyangchen** [comment]
感觉是领普的问题，米家极客版也是这样的，ps内容专门写了极客版有人状态让用无人状态取反

**Comment by Joee-D** [comment]
同意，人体传感器、门窗传感器等建议转换成binary sensor。
sensor接入homekit不识别，需要用template转成binary sensor才可以。

**Comment by Skyearn** [comment]
> 感觉是领普的问题，米家极客版也是这样的，ps内容专门写了极客版有人状态让用无人状态取反

主要是可以看到属性，就一个无人，其他全是有人，完全没必要做这么多状态。二元传感器还能直接接入 HomeKit。

**Comment by DyAxy** [comment]
领普的那里问题而已，在中枢网关里也是这样显示的。
用template 转一下binary sensor就行了。
![20241218-134617](https://github.com/user-attachments/assets/ab842490-59d2-4b0d-b07e-b1b559db07ae)

但是其他动作、门窗以及水浸输出都是sensor而不是binary sensor所以转homekit不识别

**Comment by Skyearn** [comment]
> 领普的那里问题而已，在中枢网关里也是这样显示的。 ![20241218-134617](https://private-user-images.githubusercontent.com/111729065/396775705-ab842490-59d2-4b0d-b07e-b1b559db07ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDQzMTEsIm5iZiI6MTczNDUwNDAxMSwicGF0aCI6Ii8xMTE3MjkwNjUvMzk2Nzc1NzA1LWFiODQyNDkwLTU5ZDItNGIwZC1iMDdlLWIxYjU1OWRiMDdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNjQwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTYwYmExMjYyN2I0ODJkMTNkYzc4MTFmODQyY2ZhNWEzNjM0ZGI0ZTlmOTI3ZTM5NWIwNjkxZDhkZDhiMjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bfa8wKfqRLlmQSThVavD4RFwDC5wI7wQ9sOZbo3MeRk) 用template 转一下binary sensor就行了。 `{% if is_state("sensor.linp_cn_xxxxx","无人") -%} off {%- else -%} on {%- endif %}`
> 
> 但是其他动作、门窗以及水浸输出都是sensor而不是binary sensor所以转homekit不识别

这个有具体的教程没，很久没用过 HA，买了个这个人在传感器才想弄一下。😂

**Comment by Skyearn** [comment]
> template

找到了，谢谢。https://bbs.hassbian.com/thread-18160-1-1.html

**Comment by DyAxy** [comment]
> > 领普的那里问题而已，在中枢网关里也是这样显示的。 ![20241218-134617](https://private-user-images.githubusercontent.com/111729065/396775705-ab842490-59d2-4b0d-b07e-b1b559db07ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDQzMTEsIm5iZiI6MTczNDUwNDAxMSwicGF0aCI6Ii8xMTE3MjkwNjUvMzk2Nzc1NzA1LWFiODQyNDkwLTU5ZDItNGIwZC1iMDdlLWIxYjU1OWRiMDdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNjQwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTYwYmExMjYyN2I0ODJkMTNkYzc4MTFmODQyY2ZhNWEzNjM0ZGI0ZTlmOTI3ZTM5NWIwNjkxZDhkZDhiMjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bfa8wKfqRLlmQSThVavD4RFwDC5wI7wQ9sOZbo3MeRk) 用template 转一下binary sensor就行了。 `{% if is_state("sensor.linp_cn_xxxxx","无人") -%} off {%- else -%} on {%- endif %}`
> > 但是其他动作、门窗以及水浸输出都是sensor而不是binary sensor所以转homekit不识别
> 
> 这个有具体的教程没，很久没用过 HA，买了个这个人在传感器才想弄一下。😂

可以直接用UI方式配置的 不需要yaml方式

**Comment by Skyearn** [comment]
> > > 领普的那里问题而已，在中枢网关里也是这样显示的。 ![20241218-134617](https://private-user-images.githubusercontent.com/111729065/396775705-ab842490-59d2-4b0d-b07e-b1b559db07ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDQzMTEsIm5iZiI6MTczNDUwNDAxMSwicGF0aCI6Ii8xMTE3MjkwNjUvMzk2Nzc1NzA1LWFiODQyNDkwLTU5ZDItNGIwZC1iMDdlLWIxYjU1OWRiMDdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNjQwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTYwYmExMjYyN2I0ODJkMTNkYzc4MTFmODQyY2ZhNWEzNjM0ZGI0ZTlmOTI3ZTM5NWIwNjkxZDhkZDhiMjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bfa8wKfqRLlmQSThVavD4RFwDC5wI7wQ9sOZbo3MeRk) 用template 转一下binary sensor就行了。 `{% if is_state("sensor.linp_cn_xxxxx","无人") -%} off {%- else -%} on {%- endif %}`
> > > 但是其他动作、门窗以及水浸输出都是sensor而不是binary sensor所以转homekit不识别
> > 
> > 
> > 这个有具体的教程没，很久没用过 HA，买了个这个人在传感器才想弄一下。😂
> 
> 可以直接用UI方式配置的 不需要yaml方式

入口在哪里哇，能否指下路，需要安装其他三方的吗。

**Comment by Skyearn** [comment]
> > > > 领普的那里问题而已，在中枢网关里也是这样显示的。 ![20241218-134617](https://private-user-images.githubusercontent.com/111729065/396775705-ab842490-59d2-4b0d-b07e-b1b559db07ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDQzMTEsIm5iZiI6MTczNDUwNDAxMSwicGF0aCI6Ii8xMTE3MjkwNjUvMzk2Nzc1NzA1LWFiODQyNDkwLTU5ZDItNGIwZC1iMDdlLWIxYjU1OWRiMDdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNjQwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTYwYmExMjYyN2I0ODJkMTNkYzc4MTFmODQyY2ZhNWEzNjM0ZGI0ZTlmOTI3ZTM5NWIwNjkxZDhkZDhiMjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bfa8wKfqRLlmQSThVavD4RFwDC5wI7wQ9sOZbo3MeRk) 用template 转一下binary sensor就行了。 `{% if is_state("sensor.linp_cn_xxxxx","无人") -%} off {%- else -%} on {%- endif %}`
> > > > 但是其他动作、门窗以及水浸输出都是sensor而不是binary sensor所以转homekit不识别
> > > 
> > > 
> > > 这个有具体的教程没，很久没用过 HA，买了个这个人在传感器才想弄一下。😂
> > 
> > 
> > 可以直接用UI方式配置的 不需要yaml方式
> 
> 入口在哪里哇，能否指下路，需要安装其他三方的吗。

我找到了，感谢。https://www.home-assistant.io/integrations/template/#configuration
