### ISSUE TITLE
[Bug]: zhimi.heater.mc2a not recognized as climate 

### ISSUE THREAD

**Issue by DenisV94** [XiaoMi/ha_xiaomi_home#124]
### Describe the bug / 描述问题

The device zhimi.heater.mc2a is not recognized as a climate thermostat object in Home Assistant. It does not behave or integrate as expected, based on the Home Assistant Climate integration.

### To Reproduce / 复现步骤

Go to Settings > Devices & Services > Xiaomi Home Integration.
Configure or add a zhimi.heater.mc2a device.
Attempt to control the heater or observe its entity type.
Notice that it does not appear or behave as a climate object.

### Expected behavior / 预期结果

The zhimi.heater.mc2a device should be recognized as a climate entity in Home Assistant, allowing it to function as a thermostat object.

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

0.1.1

**Comment by JimmyKmi** [comment]
see https://github.com/XiaoMi/ha_xiaomi_home/issues/117
