### ISSUE TITLE
升级提示error: pathspec ‘v0.1.1’ did not match any file(s) know go git

### ISSUE THREAD

**Issue by ecool2021** [XiaoMi/ha_xiaomi_home#127]
### Describe the bug / 描述问题

cd config/ha_xiaomi_home git checkout v0.1.1 升级提示错误

### To Reproduce / 复现步骤

cd config/ha_xiaomi_home 
git checkout v0.1.1

### Expected behavior / 预期结果

error: pathspec ‘v0.1.1’ did not match any file(s) know go git

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by devang2** [comment]
没拉取到吗？加入HACS自己义库，没提示有升级（需要再观察），但是点重新下载有更新版本。

**Comment by githubgj** [comment]
> 没拉取到吗？加入HACS自己义库，没提示有升级（需要再观察），但是点重新下载有更新版本。

我已经添加到了HACS里面，然后下载了最新的v0.1.1,根据提示重启HASS之后，打开集成依然显示版本是v0.1.0，不知道为什么，有成功升级的吗

**Comment by lql1151686140** [comment]
我也无法更新成功，哪怕替换文件都不行，集成里面一直都是0.1.0

**Comment by lql1151686140** [comment]
但是hacs提示更新成功

**Comment by MarcPolaris** [comment]
> 我也无法更新成功，哪怕替换文件都不行，集成里面一直都是0.1.0

同样的情况，怎么回事。

**Comment by he0119** [comment]
> > 我也无法更新成功，哪怕替换文件都不行，集成里面一直都是0.1.0
> 
> 同样的情况，怎么回事。

也许是没有更新 manifest.json 的问题。

https://github.com/XiaoMi/ha_xiaomi_home/blob/189060dd864e83b476f03edd8e2fb217f9ab6012/custom_components/xiaomi_home/manifest.json#L28

**Comment by lql1151686140** [comment]
> > > 我也无法更新成功，哪怕替换文件都不行，集成里面一直都是0.1.0
> > 
> > 
> > 同样的情况，怎么回事。
> 
> 也许是没有更新 manifest.json 的问题。
> 
> https://github.com/XiaoMi/ha_xiaomi_home/blob/189060dd864e83b476f03edd8e2fb217f9ab6012/custom_components/xiaomi_home/manifest.json#L28

不行，替换这个文件还是0.1.0

**Comment by lql1151686140** [comment]
> > > 我也无法更新成功，哪怕替换文件都不行，集成里面一直都是0.1.0
> > 
> > 
> > 同样的情况，怎么回事。
> 
> 也许是没有更新 manifest.json 的问题。
> 
> https://github.com/XiaoMi/ha_xiaomi_home/blob/189060dd864e83b476f03edd8e2fb217f9ab6012/custom_components/xiaomi_home/manifest.json#L28

破案了，就是这个文件没修改版本号，手动改成0.1.1了就好了

**Comment by ecool2021** [comment]
已经升级到0.12
![image](https://github.com/user-attachments/assets/3b3c642a-9a7a-4d7f-8142-39ef8011286a)
