### ISSUE TITLE
[Bug]: 小米米家智能墙壁插座zimi.plug.zncz01  功耗参数 电功率 识别错误 

### ISSUE THREAD

**Issue by MarcPolaris** [XiaoMi/ha_xiaomi_home#130]
### Describe the bug / 描述问题

zimi.plug.zncz01 功耗参数 电功率 识别错误 实际37.3w，集成里显示 3,730 W 望修复。

### To Reproduce / 复现步骤

无

### Expected behavior / 预期结果

修复

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.1

**Comment by asdi998** [comment]
同样的问题，功率显示为实际的100倍。
