### ISSUE TITLE
[Bug]: 经常性崩溃导致所有设备无法在集成控制

### ISSUE THREAD

**Issue by Decwind** [XiaoMi/ha_xiaomi_home#131]
### Describe the bug / 描述问题

经常性崩溃导致所有设备无法在集成控制

### To Reproduce / 复现步骤

操作设备后1分钟之内必出现这种情况

### Expected behavior / 预期结果

希望能解决整体离线问题

### Home Assistant Logs / 系统日志

[home-assistant_2024-12-18T01-38-10.402Z.log](https://github.com/user-attachments/files/18173495/home-assistant_2024-12-18T01-38-10.402Z.log)

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.1

**Comment by topsworld** [comment]
@Decwind 您好，根据云服务同事给的反馈，Home Assistant订阅成功了，但是下行pub消息给HA的时候，HA没有响应，导致MQTT断连，需要检查下本地网络环境是否正常，或者尝试换个网络环境。

**Comment by topsworld** [comment]
如上，非集成问题，问题关闭，如果更换网络环境，问题仍然存在再reopen
