### ISSUE TITLE
[Bug]: 小爱音箱部分实体无法使用

### ISSUE THREAD

**Issue by ZhaiSoul** [XiaoMi/ha_xiaomi_home#147]
### Describe the bug / 描述问题

静音和TTS实体无法使用

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/97e7a014-ed98-4fd1-bb86-eaf694b489c6)

### Expected behavior / 预期结果

正常使用这些实体

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245
集成: Home Assistant WebSocket API (文档, 问题)
首次出现: 13:01:45 (2 次总计出现)
上次记录: 13:01:50

[23169105105040] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1066, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 567, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 内部错误

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/switch.py", line 101, in async_turn_off
    await self.set_property_async(value=False)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1070, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}') from e
RuntimeError: 执行错误, 内部错误, switch.xiaomi_cn_277034212_s12_mute_p_2_2,  扬声器 静音

日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245
集成: Home Assistant WebSocket API (文档, 问题)
首次出现: 13:01:36 (1 次总计出现)
上次记录: 13:01:36

[23169105105040] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1279, in action_async
    return await self.miot_device.miot_client.action_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        in_list=in_list or [])
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 694, in action_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 内部错误

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 153, in async_set_value
    if await self.action_async(in_list=in_value):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1285, in action_async
    raise RuntimeError(f'{e}, {self.entity_id}, {self.name}') from e
RuntimeError: 执行错误, 内部错误, text.xiaomi_cn_277034212_s12_play_text_a_5_1,  智能音箱 播放文本

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by MarcPolaris** [comment]
同样的问题  手上的xiaomi.wifispeaker.lx04，xiaomi.wifispeaker.lx06 ，xiaomi.wifispeaker.l7a   都是显示“无法执行动作“text/set_value” 。 action exec failed, 智能音箱 播放文本(text.xiaomi_cn_445809544_l7a_play_text_a_5_1), invalid action params format, xxx”

**Comment by fay000fay** [comment]
xiaomi.wifispeaker.s12，即小米AI音箱一代，没有TTS文本功能。miot auto可以，希望官方早点补全

**Comment by ZhaiSoul** [comment]
> xiaomi.wifispeaker.s12，即小米AI音箱一代，没有TTS文本功能。miot auto可以，希望官方早点补全

Xiaomi Miot Auto可以正常播放TTS内容，而且我目前也和其他设备有联动的
![image](https://github.com/user-attachments/assets/e2aa35eb-dc69-4303-b573-f393c40136bc)

**Comment by fay000fay** [comment]
> > xiaomi.wifispeaker.s12，即小米AI音箱一代，没有TTS文本功能。miot auto可以，希望官方早点补全
> 
> Xiaomi Miot Auto可以正常播放TTS内容，而且我目前也和其他设备有联动的 ![image](https://private-user-images.githubusercontent.com/8712438/396775515-e2aa35eb-dc69-4303-b573-f393c40136bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDEwOTMsIm5iZiI6MTczNDUwMDc5MywicGF0aCI6Ii84NzEyNDM4LzM5Njc3NTUxNS1lMmFhMzVlYi1kYzY5LTQzMDMtYjU3My1mMzkzYzQwMTM2YmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMDU0NjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzM5Nzc4YjZlYzFmMzZkMTk0YTA2ODk2YTc0MDgzMjIxZTgxNTQxODM3ZDAxZWEwZjMxMjc2MmIzYTM1ZmNkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JRMePaxwoc4SN9-iwPW5JC9PWgfPlwvQg7_EXoq-lyo)

我也是有联动。所以我暂时还是用miot auto。

**Comment by ZhaiSoul** [comment]
> 同样的问题 手上的xiaomi.wifispeaker.lx04，xiaomi.wifispeaker.lx06 ，xiaomi.wifispeaker.l7a 都是显示“无法执行动作“text/set_value” 。 action exec failed, 智能音箱 播放文本(text.xiaomi_cn_445809544_l7a_play_text_a_5_1), invalid action params format, xxx”

你这个可能是输入的格式有问题，目前官方的这个输入文本是数组类型，即你得输入`["测试内容"]`，但我目前的问题是连静音按钮都没法正常使用，报的错和你也不一样

**Comment by Hugh696** [comment]
> xiaomi.wifispeaker.s12，即小米AI音箱一代，没有TTS文本功能。miot auto可以，希望官方早点补全

格式不对，
语音播报是：
["你好"]

语音指令是：
["天气怎么样",false]
如果让它静默执行：
["开灯",true]

**Comment by fay000fay** [comment]
> > xiaomi.wifispeaker.s12，即小米AI音箱一代，没有TTS文本功能。miot auto可以，希望官方早点补全
> 
> 格式不对， 语音播报是： ["你好"]
> 
> 语音指令是： ["天气怎么样",false] 如果让它静默执行： ["开灯",true]

我看网上有说，用notify.send_message这个action,然后发文本给notify.音箱这个实体对吧。我还没试，等会儿去试下

**Comment by Hugh696** [comment]
> > > xiaomi.wifispeaker.s12，即小米AI音箱一代，没有TTS文本功能。miot auto可以，希望官方早点补全
> > 
> > 
> > 格式不对， 语音播报是： ["你好"]
> > 语音指令是： ["天气怎么样",false] 如果让它静默执行： ["开灯",true]
> 
> 我看网上有说，用notify.send_message这个action,然后发文本给notify.音箱这个实体对吧。我还没试，等会儿去试下

没错是这个，另外如果在node-red json里调用，需要改成
[\"你好\"]

**Comment by Hugh696** [comment]
> > > > xiaomi.wifispeaker.s12，即小米AI音箱一代，没有TTS文本功能。miot auto可以，希望官方早点补全
> > > 
> > > 
> > > 格式不对， 语音播报是： ["你好"]
> > > 语音指令是： ["天气怎么样",false] 如果让它静默执行： ["开灯",true]
> > 
> > 
> > 我看网上有说，用notify.send_message这个action,然后发文本给notify.音箱这个实体对吧。我还没试，等会儿去试下
> 
> 没错是这个，另外如果在node-red json里调用，需要改成 ["你好"]

我反斜杠怎么没了……两个引号前面各加个反斜杠

**Comment by milumet** [comment]
> > xiaomi.wifispeaker.s12，即小米AI音箱一代，没有TTS文本功能。miot auto可以，希望官方早点补全
> 
> 格式不对，
> 语音播报是：
> ["你好"]
> 
> 语音指令是：
> ["天气怎么样",false]
> 如果让它静默执行：
> ["开灯",true]

大神 太 6 了  。 可以让美的洗衣机洗完衣服 小爱播报了

**Comment by topsworld** [comment]
“内部错误”问题是由于本地控制引起的，可以升级v0.1.3解决。

**Comment by yangrusen** [comment]
我这里怎么没有播放文本和执行文本的框？类似于Miot auto那样的，你的截图里是有的。

**Comment by ZhaiSoul** [comment]
> 我这里怎么没有播放文本和执行文本的框？类似于Miot auto那样的，你的截图里是有的。

阅读项目的ReadMe，里面有写
