### ISSUE TITLE
[Bug]: yeelight 浴霸异常

### ISSUE THREAD

**Issue by tufeikafei** [XiaoMi/ha_xiaomi_home#15]
### Describe the bug / 描述问题

yeelink.bhf_light.v6 这款浴霸的状态属性温度等等都没有正确显示。

### To Reproduce / 复现步骤

![微信图片_20241216214959](https://github.com/user-attachments/assets/6b48f8b0-338e-4cf7-9622-e1dd4fbfb0d4)
yeelight这款浴霸除了灯的状态是正确的，其他模式之类的显示的属性状态都是不正确的。
显示是在加热中，但是这里没有显示，都显示待机，设置的温度35度，但是插件中显示是6度。

### Expected behavior / 预期结果

希望正确的获取到属性。

### Home Assistant Logs / 系统日志

[home-assistant_2024-12-16T14-14-07.744Z.log](https://github.com/user-attachments/files/18151325/home-assistant_2024-12-16T14-14-07.744Z.log)

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by tufeikafei** [comment]
重载后获取到正确数据了。

**Comment by SusanPhevos** [comment]
xiaomi_home不会轮询设备状态，浴霸未上报风暖温度，故xiaomi_home中显示的浴霸风暖温度始终不变。
这是浴霸设备的问题。

**Comment by SusanPhevos** [comment]
> 后期能否加个功能，比如有些确定不会自动上报的设备是通过轮询来获取数据？

xiaomi_home只能通过MIoT-Spec-V2获知设备的能力，风暖属性access含notify，该属性应当在变化时上报，然而实际却没有上报，属于设备实现的问题。为了减少云端压力，xiaomi_home不会加轮询逻辑。

**Comment by rugal7699** [comment]
HA里的模式和米家app里相比有少，导致使用极速加热时，HA里的状态会显示为待机
![IMG_9497](https://github.com/user-attachments/assets/d4bd0701-23f2-414b-8803-0bf85987b8df)
![IMG_9498](https://github.com/user-attachments/assets/7af6fe02-e246-4a3e-bc52-873e7641b769)

**Comment by erchuyi** [comment]
> xiaomi

中枢网关固件更新后，是否能在本地执行，这样就没有云端压力了

**Comment by SusanPhevos** [comment]
> > xiaomi
> 
> 中枢网关固件更新后，是否能在本地执行，这样就没有云端压力了

这属于设备未按规范实现的问题，不宜在xiaomi_home中增加轮询逻辑。
