### ISSUE TITLE
[Bug]: yeelink.light.lamp15 缺少氛围灯开关

### ISSUE THREAD

**Issue by MarcPolaris** [XiaoMi/ha_xiaomi_home#151]
### Describe the bug / 描述问题

yeelink显示器挂灯yeelink.light.lamp15 缺少氛围灯开关

### To Reproduce / 复现步骤

<img width="675" alt="截屏2024-12-18 14 42 24" src="https://github.com/user-attachments/assets/d48c38ef-80b7-45a2-a3bd-60c85c25218b" />
<img width="383" alt="截屏2024-12-18 14 41 27" src="https://github.com/user-attachments/assets/0db3ea82-83ae-484a-a766-33182e6cd079" />

### Expected behavior / 预期结果

增加氛围灯的开关

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.1

**Comment by SusanPhevos** [comment]
yeelink.light.lamp15 的[MIoT-Spec-V2](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:light:0000A001:yeelink-lamp15:3:0000C814)只定义了一个 Light，故xiaomi_home只生成了一个灯的Entity。
请问第二张截图是米家APP的界面吗？

**Comment by MarcPolaris** [comment]
> yeelink.light.lamp15的[MIoT-Spec-V2](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:light:0000A001:yeelink-lamp15:3:0000C814)只定义了一个Light，故xiaomi_home只生成了一个灯的实体。请问第二张截图是米家APP的界面吗？

对的，第二张是米家app的界面
