### ISSUE TITLE
[Bug]: 米家智能插座2蓝牙版，电压、电流、用电量显示错误

### ISSUE THREAD

**Issue by ljj23h** [XiaoMi/ha_xiaomi_home#153]
### Describe the bug / 描述问题

米家智能插座2蓝牙版，电压、电流、用电量显示错误

### To Reproduce / 复现步骤

<img width="651" alt="Snipaste_2024-12-18_15-40-18" src="https://github.com/user-attachments/assets/893b7ce9-a3e8-44d7-b533-64e68fa691be" />

### Expected behavior / 预期结果

显示正常

### Home Assistant Core version / Home Assistant Core 版本

2024.12.1

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.6

### Xiaomi Home integration version / 米家集成版本

v0.1.1

### Additional context / 其他说明

无

**Comment by JimmyKmi** [comment]
待观察，这个设备在米家上报的数据也比较乱。
电流始终是5，在极客版可验证是设备问题。
已工作时间HA始终显示 180min，极客使用查询方法进行查询，出来的值是无规律数字，多次查询都不一致。
电压参数待观察，目前我这边传感器上报是数值220，HA显示220 mV，实际家庭电压235.5V，该参数不具备参考性。
