### ISSUE TITLE
[Bug]: all devices from my xiaomi account on Singapore server shown as unavailable in the status

### ISSUE THREAD

**Issue by sydskyhigh** [XiaoMi/ha_xiaomi_home#157]
### Describe the bug / 描述问题

 all devices from my xiaomi account on Singapore server shown as unavailable in the status

### To Reproduce / 复现步骤

per description above

### Expected behavior / 预期结果

should be shown as available

### Home Assistant Core version / Home Assistant Core 版本

2024.11

### Home Assistant Operation System version / Home Assistant Operation System 版本

14

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by SusanPhevos** [comment]
Hi, can you upload the Home Assistant logs?
