### ISSUE TITLE
[Bug]: 空调没办法控制

### ISSUE THREAD

**Issue by Tricooo** [XiaoMi/ha_xiaomi_home#16]
### Describe the bug / 描述问题

无法控制空调

### To Reproduce / 复现步骤

报错无法执行动作“climate/set_hvac_mode” 。 执行错误, 设备在当前状态下无法执行此操作, climate.xiaomi_cn_m4, 空调, mode

### Expected behavior / 预期结果

点击图形化按钮应该可以正常控制

### Home Assistant Core version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by pccr10001** [comment]
冷氣Widget無法控制模式
但可以從Toggle開啟跟關閉

**Comment by SusanPhevos** [comment]
问题同 #37

**Comment by topsworld** [comment]
v0.1.1已修复，问题关闭，如果问题仍存在再reopen
