### ISSUE TITLE
[Bug]: 小方摄像机无法开启p2p视频流

### ISSUE THREAD

**Issue by catiz** [XiaoMi/ha_xiaomi_home#160]
### Describe the bug / 描述问题

按下按钮无法显示摄像头画面

### To Reproduce / 复现步骤

![WeChat截图_20241218183747](https://github.com/user-attachments/assets/4a153f1f-890e-44e6-a658-f5d444795cda)

无法执行动作“button/press” 。 执行错误, Device不存在, button.isa_cn_55796713_isc5_start_p2p_stream_a_3_1, P2P视频流 开始实时视频流

### Expected behavior / 预期结果

显示摄像头画面

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by raulmadrid777** [comment]
为什么不支持查看摄像头视频？

**Comment by chenmdg** [comment]
应该支持局域网查看摄像头
