### ISSUE TITLE
[Bug]: 小米人脸智能识别门锁（lumi.lock.mcn002）状态上报异常

### ISSUE THREAD

**Issue by XiaoyaoLinghao** [XiaoMi/ha_xiaomi_home#165]
### Describe the bug / 描述问题

门锁型号lumi.lock.mcn002，存在较严重的状态上报错误，如门状态长时间保持为已开锁，间歇性显示为不可用

### To Reproduce / 复现步骤

查看门锁状态，显示门状态一直处于开锁状态，且门铃响了、发生异常、锁事件现实的状态与APP内完全就不相符
![1](https://github.com/user-attachments/assets/37eb769e-aef3-47fd-8754-666a8902e9c4)
![2](https://github.com/user-attachments/assets/7c854f9d-31f9-4860-b7be-a6b5553d18ed)

### Expected behavior / 预期结果

使数据获得有效上报

### Home Assistant Logs / 系统日志

[history.csv](https://github.com/user-attachments/files/18181007/history.csv)

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by SusanPhevos** [comment]
门锁设备问题，自身上报状态不及时。
