### ISSUE TITLE
[Bug]: 米家空调伴侣Pro 万能遥控版 空调 开关状态切换一直处于未知状态

### ISSUE THREAD

**Issue by huhuime** [XiaoMi/ha_xiaomi_home#166]
### Describe the bug / 描述问题

米家空调伴侣Pro 万能遥控版 空调 开关状态切换一直处于未知状态

### To Reproduce / 复现步骤

不管开关还是点击触发都是未知状态
![image](https://github.com/user-attachments/assets/585f9399-e497-476b-9951-cc7655bee860)

### Expected behavior / 预期结果

正常显示开关状态

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

Supervisor 2024.12.0/Frontend 20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.1

### Additional context / 其他说明

使用Home Assistant Supervisor运行在树莓派上

**Comment by SusanPhevos** [comment]
这是一个Button Entity，从“不再可用”变成“未知”表示设备由离线变为在线，按下Button持续的时间很短，故截图中蓝色标记的时间在时间轴上只能显示很窄的一条线，时间轴上大部分显示为灰色“未知”。此为正常现象。
