### ISSUE TITLE
[Bug]: viomi.waterheater.e1

### ISSUE THREAD

**Issue by gujiys** [XiaoMi/ha_xiaomi_home#17]
### Describe the bug / 描述问题

热水器开关成传感器了

### To Reproduce / 复现步骤

开关成传感了

![0012](https://github.com/user-attachments/assets/97b07e0d-dda4-4e1b-9915-529f455d76e9)

### Expected behavior / 预期结果

开关

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

14

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by JimmyKmi** [comment]
点进去“热水器”就可以开关了，“热水器”是一个包含开关等的完整实体

**Comment by topsworld** [comment]
您好，热水器开关可以从热水器实体控制

**Comment by gujiys** [comment]
是我不会用还是哪里没设置好，点开只有模式可调，没有开关啊，模式有3，日常  速热，定时。定时是不能用的


![0016](https://github.com/user-attachments/assets/43d9e368-ef63-4d13-b0cc-672ce29df09e)
![0015](https://github.com/user-attachments/assets/273fd2b1-bd30-459c-9175-7a1c59fcb17f)
