### ISSUE TITLE
[Bug]: 更新0.1.1后在集成里面显示版本号还是0.1.0

### ISSUE THREAD

**Issue by wlbchn** [XiaoMi/ha_xiaomi_home#173]
### Describe the bug / 描述问题

更新0.1.1后在集成里面显示版本号还是0.1.0

### To Reproduce / 复现步骤

hacs Custom repositories 方式更新，更新后正常重启。之后集成里显示依然是0.1.0，hacs里显示0.1.1

### Expected behavior / 预期结果

正常显示更新后的版本号

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.1

### Additional context / 其他说明

无

**Comment by lql1151686140** [comment]
我今天发现这个问题，后来发现就是作者单纯的忘记修改版本号了

**Comment by SusanPhevos** [comment]
试试 https://github.com/XiaoMi/ha_xiaomi_home/releases/tag/v0.1.2

**Comment by topsworld** [comment]
如上，问题关闭
