### ISSUE TITLE
[Bug]: 如何排除不想同步的设备？

### ISSUE THREAD

**Issue by Today-to-Lsp** [XiaoMi/ha_xiaomi_home#185]
### Describe the bug / 描述问题

如何排除不想同步的设备？

### To Reproduce / 复现步骤

如何排除不想同步的设备？

### Expected behavior / 预期结果

排除不想同步的设备

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by JimmyKmi** [comment]
same: https://github.com/XiaoMi/ha_xiaomi_home/issues/189

**Comment by L-Morningstar** [comment]
目前可以在ha里禁用实体
