### ISSUE TITLE
[Bug]: 易来浴霸pro极速加热模式

### ISSUE THREAD

**Issue by rugal7699** [XiaoMi/ha_xiaomi_home#187]
### Describe the bug / 描述问题

HA里没有极速加热模式，导致使用米家app或遙控器切換极速加热时，HA里的状态会显示为待机

### To Reproduce / 复现步骤

![IMG_9498](https://github.com/user-attachments/assets/814bab08-724a-4e85-81e0-d279b13db8f4)
![IMG_9500](https://github.com/user-attachments/assets/4aef257e-106a-41fa-9073-bb31decd8160)

### Expected behavior / 预期结果

HA里增加模式

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/yeelink.bhf_light.v6

这款设备厂商没有在 miot-spec 规格中定义极速制热，因此不会出现实体或选项。
