### ISSUE TITLE
[Bug]: 添加账户时，无法通过筛选，去同步设备

### ISSUE THREAD

**Issue by BrkOne** [XiaoMi/ha_xiaomi_home#189]
### Describe the bug / 描述问题

添加账户时，无法通过筛选，去同步设备

### To Reproduce / 复现步骤

添加账户时，无法通过筛选，去同步设备

### Expected behavior / 预期结果

期望添加账户时，可以通过筛选设备型号，去包含或排除设备进行同步

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.2

### Additional context / 其他说明

当前版本添加账户时，无法通过筛选，去同步设备。

期望添加账户时，可以通过筛选设备型号，去包含或排除设备进行同步。

期望功能截图：

![33](https://github.com/user-attachments/assets/f9b3e039-88e0-4d13-af5a-39cd419ed123)

**Comment by JimmyKmi** [comment]
Hello, this is currently in the planning stages. Additionally, this is a feature suggestion, so please submit it to the discussions.
