### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Crickus** [XiaoMi/ha_xiaomi_home#192]
### Describe the bug / 描述问题

Inteleligent Aroma Diffuser (BLE) from Mi Home is not imported

### To Reproduce / 复现步骤

In Mi Home Intelligent Aroma diffuser is on-boarded and fully functional.
![photo_2024-12-18_21-00-28](https://github.com/user-attachments/assets/cf894798-4bd5-40fb-973a-e71cda24c1ca)
![photo_2024-12-18_21-00-35](https://github.com/user-attachments/assets/5311838e-9da1-478f-bea4-19e434e60858)
![photo_2024-12-18_21-00-38](https://github.com/user-attachments/assets/d31fdf39-0086-409b-95dd-7a1b0a409cd3)

During initial profile this device is not imported. Additional updates during device in pair mode or actively managing doesn't help.
 Device is visible during Bluetooth passive scan and allowed to be connected.
 
![photo_2024-12-18_21-00-42](https://github.com/user-attachments/assets/80649423-c5ba-4e5f-b4be-23d79215f3d8)
![photo_2024-12-18_21-00-45](https://github.com/user-attachments/assets/f7225c4b-15c0-46f8-a869-d81467d12553)
 

### Expected behavior / 预期结果

Device been imported during profile inicialization with integration

### Home Assistant Core version / Home Assistant Core 版本

core-2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

Home Assistant OS 14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by JimmyKmi** [comment]
Model: szxzh.diffuser.v03  
urn:miot-spec-v2:device:diffuser:0000A01E:szxzh-v03:1  
This device does not seem to support any automation linkage.

https://mijia.wiki/products/szxzh.diffuser.v03

**Comment by JimmyKmi** [comment]
> Too bad( Plugin is quite poor in options. It even doesn't support Mi Home scenes (no if, no then). I hope it will be possible to provide automatization with HA

There are certain devices that can only be managed by directly connecting to Bluetooth via a smartphone and do not support any automation. As users, we often refer to them as "falsely connected to Mi Home" or "connected but not fully integrated."
