### ISSUE TITLE
[Bug]: 米家小厨宝只有温控器实体，没有开关实体，无法打开或者关闭小厨宝

### ISSUE THREAD

**Issue by LUOZEYUE** [XiaoMi/ha_xiaomi_home#195]
### Describe the bug / 描述问题

米家小厨宝只有温控器实体，没有开关实体，无法打开或者关闭小厨宝

### To Reproduce / 复现步骤

![1734567553427](https://github.com/user-attachments/assets/b9122abe-f788-4596-b50b-b46d52ec0d18)

### Expected behavior / 预期结果

增加一个开关实体，可以便捷的在ha里开关小厨宝

### Home Assistant Core version / Home Assistant Core 版本

最新

### Home Assistant Operation System version / Home Assistant Operation System 版本

最新

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by topsworld** [comment]
您好，可以点击热水器，会看到有关闭选项

**Comment by topsworld** [comment]
如上，问题关闭
![image](https://github.com/user-attachments/assets/0c7c1be9-cba9-48c1-b903-0f7a79299b26)
