### ISSUE TITLE
[Bug]: 青米延長線qmi.plug.2a1c1 感測器實體單位錯誤

### ISSUE THREAD

**Issue by delphicchen** [XiaoMi/ha_xiaomi_home#196]
### Describe the bug / 描述问题

青米延長線qmi.plug.2a1c1 感測器實體單位錯誤，用電量沒有單位kWh，電壓應該是V而非mV

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/98e06594-f234-4761-b72a-571922dd93dd)

### Expected behavior / 预期结果

用電量單位應該是kWh，電壓應該是V而非mV

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

N/A

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by SusanPhevos** [comment]
siid=3, piid=2 厂商定义的unit是watt。其余属性厂商未定义unit，故使用默认单位。
