### ISSUE TITLE
[Bug]: zigbee版本的门窗传感器显示状态为：分离和接触，能否设置显示为：打开和关闭

### ISSUE THREAD

**Issue by LUOZEYUE** [XiaoMi/ha_xiaomi_home#197]
### Describe the bug / 描述问题

zigbee版本的门窗传感器显示状态为： 分离和接触，能否设置为：打开和关闭，这样比较符合语言习惯

### To Reproduce / 复现步骤

![1734568223022](https://github.com/user-attachments/assets/47eb0e38-8ee9-40ac-9925-df083199afbc)

### Expected behavior / 预期结果

状态设置为：打开和关闭

### Home Assistant Core version / Home Assistant Core 版本

最新

### Home Assistant Operation System version / Home Assistant Operation System 版本

最新

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by Yuke-hd** [comment]
参考https://github.com/XiaoMi/ha_xiaomi_home?tab=readme-ov-file#multiple-language-support

**Comment by topsworld** [comment]
您好，您也可以进入集成目录，找到miot/specs/bool_trans.json，修改key为contact_state的项

**Comment by topsworld** [comment]
如上，问题关闭，后续我们会支持更多用户自定义功能
