### ISSUE TITLE
[Bug]: 带夜灯功能的网关无法设置夜灯色彩和亮度

### ISSUE THREAD

**Issue by nicelake** [XiaoMi/ha_xiaomi_home#21]
### Describe the bug / 描述问题

小米多功能网关（lumi.gateway.v3）和Aqara网关（lumi.gateway.aqhm01）带有彩色夜灯功能，可以调整RGB色彩和亮度，但Xiaomi Home集成中只能开和关，无法设置色彩和亮度

### To Reproduce / 复现步骤

设备 - 网关 - 灯

### Expected behavior / 预期结果

可以设置灯的色彩和亮度

### Home Assistant Core version / Home Assistant Core 版本

2024.11.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

### Additional context / 其他说明

在Xiaomi Miio中可以正常设置灯的色彩和亮度

**Comment by SusanPhevos** [comment]
lumi.gateway.v3的MIoT-Spec-V2 https://home.miot-spec.com/spec/lumi.gateway.v3 未定义RGB色彩和亮度，故xiaomi_home无法生成相应的Entity。
米家APP亦根据设备定义MIoT-Spec-V2对设备进行控制，因此米家APP应该也无法调节lumi.gateway.v3的RGB色彩、亮度。

**Comment by SusanPhevos** [comment]
lumi.gateway.v3 和 lumi.gateway.aqhm01 是比较老的设备，MIoT-Spec-V2是在设备上线几年后才定义的。米家APP做了特殊处理，不是通过MIoT-Spec-V2控制设备。因此设备的MIoT-Spec-V2中没有RGB色彩、亮度，但米家APP可调整这两项属性。
xiaomi_home从设计上只会根据MIoT-Spec-V2生成Entity，因此厂商未在MIoT-Spec-V2中定义RGB色彩、亮度，xiaomi_home无法生成相应Entity。

**Comment by nicelake** [comment]
感谢您的答疑，现在理解了这其中的缘由。
