### ISSUE TITLE
[Bug]: 无法加载配置向导: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by rigel0212** [XiaoMi/ha_xiaomi_home#217]
### Describe the bug / 描述问题

无法加载配置向导: {"message":"Invalid handler specified"}

### To Reproduce / 复现步骤

Home Assistant
Core
2024.12.4
Supervisor
2024.12.0
Operating System
14.0
Frontend
20241127.8

该homeassistant版本下无法安装，

### Expected behavior / 预期结果

无法安装

### Home Assistant Logs / 系统日志

无法安装

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.1

**Comment by rigel0212** [comment]
日志：
日志记录器: homeassistant.config_entries
来源: config_entries.py:3314
首次出现: 11:39:10 (5 次总计出现)
上次记录: 12:12:42

Error occurred loading flow for integration xiaomi_home: No module named 'custom_components.xiaomi_home.config_flow'

**Comment by TheThirdSanta** [comment]
macos上用python安装也会报同样的错误

**Comment by rigel0212** [comment]
> macos上用python安装也会报同样的错误

我也是macos的。不过我是用虚拟机安装的。

**Comment by chenyushan** [comment]
我用macos python也一样报错，m2芯片的macmini AttributeError: module 'os' has no attribute 'eventfdUnexpected exception importing platform custom_components.xiaomi_home.config_flow

AttributeError: module 'os' has no attribute 'eventfd'

Error occurred loading flow for integration xiaomi_home: Exception importing custom_components.xiaomi_home.config_flow

这是个比较严重的问题。Home Assistant 在加载 xiaomi_home 集成时遇到了错误，导致集成无法正常运行。错误信息 AttributeError: module 'os' has no attribute 'eventfd' 表明 xiaomi_home 集成依赖的 os 模块中缺少 eventfd 属性。eventfd 通常用于 Linux 系统上的事件通知，而 macOS 不直接支持。

**Comment by rigel0212** [comment]
> 我用macos python也一样报错，m2芯片的macmini AttributeError: module 'os' has no attribute 'eventfdUnexpected exception importing platform custom_components.xiaomi_home.config_flow
> 
> AttributeError: module 'os' has no attribute 'eventfd'
> 
> Error occurred loading flow for integration xiaomi_home: Exception importing custom_components.xiaomi_home.config_flow
> 
> 这是个比较严重的问题。Home Assistant 在加载 xiaomi_home 集成时遇到了错误，导致集成无法正常运行。错误信息 AttributeError: module 'os' has no attribute 'eventfd' 表明 xiaomi_home 集成依赖的 os 模块中缺少 eventfd 属性。eventfd 通常用于 Linux 系统上的事件通知，而 macOS 不直接支持。

更新到xiaomi_home[v0.1.2]可以添加了
