### ISSUE TITLE
[Bug]: 小爱不支持朗读文本

### ISSUE THREAD

**Issue by likenfc** [XiaoMi/ha_xiaomi_home#222]
### Describe the bug / 描述问题

希望让小爱支持设置指定的文本并进行朗读

### To Reproduce / 复现步骤

希望让小爱支持朗读指定文本，比如 欢迎回家 等，之前那个三方的可以，迁过来了才发现不支持

### Expected behavior / 预期结果

希望让小爱支持朗读指定文本

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by likenfc** [comment]
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/2943b349-9fd5-4dd9-a4a6-8d40ad14f7f7" />
好吧，其实支持，只是用法变了，希望官方可以出个具体用法说明。。。

**Comment by MarcPolaris** [comment]
没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。

**Comment by zghnwsq** [comment]
readme里面的action部分说了

**Comment by likenfc** [comment]
> readme里面的action部分说了

怪我，没仔细去读，，，或者说没想到这样用，因为之前第三方那个一直都不是这样用的，所以，哈哈

**Comment by likenfc** [comment]
> 没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。

按我上面图里这样用就行，就能让小爱朗读指定内容了

**Comment by MarcPolaris** [comment]
> > 没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。
> 
> 按我上面图里这样用就行，就能让小爱朗读指定内容了

必须在自动化里才可以吗？我想直接让小爱播放指定文字，比如我在楼下，喊楼上的人吃饭，像auto那个集成直接在播放文本里输入要播放的文字就行了，这个就实现不了了吗？

**Comment by rohdea0826** [comment]
> > > 没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。
> > 
> > 
> > 按我上面图里这样用就行，就能让小爱朗读指定内容了
> 
> 必须在自动化里才可以吗？我想直接让小爱播放指定文字，比如我在楼下，喊楼上的人吃饭，像auto那个集成直接在播放文本里输入要播放的文字就行了，这个就实现不了了吗？

创建一个脚本, entity_id改成自己音响的播放实体就可以了。
```YAML
alias: 小爱播放文本
sequence:
  - action: notify.send_message
    metadata: {}
    data:
      message: " [\"{{ msg }} \"] "
    target:
      entity_id: notify.xiaomi_cn_108269114_lx5a_play_text_a_5_1
fields:
  msg:
    selector:
      text: null
    required: true
    name: 小爱将会播放：
description: ""
icon: mdi:speaker-message
```
<img width="702" alt="image" src="https://github.com/user-attachments/assets/b01b22f1-b7f7-4439-9429-21bb9c1ef0ba" />

**Comment by MarcPolaris** [comment]
> > > > 没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。
> > > 
> > > 
> > > 按我上面图里这样用就行，就能让小爱朗读指定内容了
> > 
> > 
> > 必须在自动化里才可以吗？我想直接让小爱播放指定文字，比如我在楼下，喊楼上的人吃饭，像auto那个集成直接在播放文本里输入要播放的文字就行了，这个就实现不了了吗？
> 
> 创建一个脚本, entity_id改成自己音响的播放实体就可以了。
> 
> ```yaml
> alias: 小爱播放文本
> sequence:
>   - action: notify.send_message
>     metadata: {}
>     data:
>       message: " [\"{{ msg }} \"] "
>     target:
>       entity_id: notify.xiaomi_cn_108269114_lx5a_play_text_a_5_1
> fields:
>   msg:
>     selector:
>       text: null
>     required: true
>     name: 小爱将会播放：
> description: ""
> icon: mdi:speaker-message
> ```
> 
> <img alt="image" width="702" src="https://private-user-images.githubusercontent.com/12271811/397372410-b01b22f1-b7f7-4439-9429-21bb9c1ef0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTMzOTgsIm5iZiI6MTczNDYxMzA5OCwicGF0aCI6Ii8xMjI3MTgxMS8zOTczNzI0MTAtYjAxYjIyZjEtYjdmNy00NDM5LTk0MjktMjFiYjljMWVmMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEyNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNjdiODMzZDkzNWI5ZmRhZDIzNzE0ZjA1MGFhMzhiMjUwYWU0YzZjYmYwNWZkNTM5ZGExMzUyMmU2ZmIzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._dNXsiLRFAlzvInVN3fXpFBYmhIP8uY7v0FlS5GO8NA">

创建脚本提示：Message malformed: extra keys not allowed @ data['sequence'][0]['sequence']    小白根本玩不赢，还是太复杂了。

**Comment by zghnwsq** [comment]
> > > 没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。
> > 
> > 
> > 按我上面图里这样用就行，就能让小爱朗读指定内容了
> 
> 必须在自动化里才可以吗？我想直接让小爱播放指定文字，比如我在楼下，喊楼上的人吃饭，像auto那个集成直接在播放文本里输入要播放的文字就行了，这个就实现不了了吗？

应该是现阶段没有做精细适配，action是可以带多个参数的，比如执行文字指令的第二个参数是：是否静默执行。要接收多个参数，所以用了列表形式

**Comment by cxyttboy** [comment]
1.首先要勾选 Action 调试模式 ：  设置 > 设备与服务 > 已配置 > Xiaomi Home  > 配置 > Action 调试模式
2.这样就会出现 智能音箱 播放文本 和 智能音箱 执行文本指令  两个选项
3.文本指令输入的格式 是   ["文本指令",false]

**Comment by nextvary** [comment]
> 1.首先要勾选 Action 调试模式 ： 设置 > 设备与服务 > 已配置 > Xiaomi Home > 配置 > Action 调试模式 2.这样就会出现 智能音箱 播放文本 和 智能音箱 执行文本指令 两个选项 3.文本指令输入的格式 是 ["文本指令",false]

4. 播放文本  ["朗读一下"]

**Comment by uduoy** [comment]
> > > > > 没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。
> > > > 
> > > > 
> > > > 按我上面图里这样用就行，就能让小爱朗读指定内容了
> > > 
> > > 
> > > 必须在自动化里才可以吗？我想直接让小爱播放指定文字，比如我在楼下，喊楼上的人吃饭，像auto那个集成直接在播放文本里输入要播放的文字就行了，这个就实现不了了吗？
> > 
> > 
> > 创建一个脚本, entity_id改成自己音响的播放实体就可以了。
> > ```yaml
> > alias: 小爱播放文本
> > sequence:
> >   - action: notify.send_message
> >     metadata: {}
> >     data:
> >       message: " [\"{{ msg }} \"] "
> >     target:
> >       entity_id: notify.xiaomi_cn_108269114_lx5a_play_text_a_5_1
> > fields:
> >   msg:
> >     selector:
> >       text: null
> >     required: true
> >     name: 小爱将会播放：
> > description: ""
> > icon: mdi:speaker-message
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="702" src="https://private-user-images.githubusercontent.com/12271811/397372410-b01b22f1-b7f7-4439-9429-21bb9c1ef0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTMzOTgsIm5iZiI6MTczNDYxMzA5OCwicGF0aCI6Ii8xMjI3MTgxMS8zOTczNzI0MTAtYjAxYjIyZjEtYjdmNy00NDM5LTk0MjktMjFiYjljMWVmMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEyNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNjdiODMzZDkzNWI5ZmRhZDIzNzE0ZjA1MGFhMzhiMjUwYWU0YzZjYmYwNWZkNTM5ZGExMzUyMmU2ZmIzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._dNXsiLRFAlzvInVN3fXpFBYmhIP8uY7v0FlS5GO8NA">
> 
> 创建脚本提示：Message malformed: extra keys not allowed @ data['sequence'][0]['sequence'] 小白根本玩不赢，还是太复杂了。

创建脚本，而不是创建自动化

**Comment by songcs3** [comment]
> > > > 没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。
> > > 
> > > 
> > > 按我上面图里这样用就行，就能让小爱朗读指定内容了
> > 
> > 
> > 必须在自动化里才可以吗？我想直接让小爱播放指定文字，比如我在楼下，喊楼上的人吃饭，像auto那个集成直接在播放文本里输入要播放的文字就行了，这个就实现不了了吗？
> 
> 创建一个脚本, entity_id改成自己音响的播放实体就可以了。
> 
> ```yaml
> alias: 小爱播放文本
> sequence:
>   - action: notify.send_message
>     metadata: {}
>     data:
>       message: " [\"{{ msg }} \"] "
>     target:
>       entity_id: notify.xiaomi_cn_108269114_lx5a_play_text_a_5_1
> fields:
>   msg:
>     selector:
>       text: null
>     required: true
>     name: 小爱将会播放：
> description: ""
> icon: mdi:speaker-message
> ```
> 
> <img alt="image" width="702" src="https://private-user-images.githubusercontent.com/12271811/397372410-b01b22f1-b7f7-4439-9429-21bb9c1ef0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjU2OTksIm5iZiI6MTczNDg2NTM5OSwicGF0aCI6Ii8xMjI3MTgxMS8zOTczNzI0MTAtYjAxYjIyZjEtYjdmNy00NDM5LTk0MjktMjFiYjljMWVmMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDExMDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NDEzMDljNzhjZWMxZjJlMjk1Y2I3MjZjZmVmOTkzMzk5ZjA5NjIzNDhhODM1MmYwZTgwNTA1ZDVjMGY5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3cGeslOqym5Vbo7d-C9-MavAx3gz6f6lxuDeVAKfmSM">

请问这个代码是写在哪里的 还有这个弹出框是怎么做的？感谢给几个详细截图 感谢。整了很久 依旧搞不懂。

**Comment by rohdea0826** [comment]
> > > > > 没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。
> > > > 
> > > > 
> > > > 按我上面图里这样用就行，就能让小爱朗读指定内容了
> > > 
> > > 
> > > 必须在自动化里才可以吗？我想直接让小爱播放指定文字，比如我在楼下，喊楼上的人吃饭，像auto那个集成直接在播放文本里输入要播放的文字就行了，这个就实现不了了吗？
> > 
> > 
> > 创建一个脚本, entity_id改成自己音响的播放实体就可以了。
> > ```yaml
> > alias: 小爱播放文本
> > sequence:
> >   - action: notify.send_message
> >     metadata: {}
> >     data:
> >       message: " [\"{{ msg }} \"] "
> >     target:
> >       entity_id: notify.xiaomi_cn_108269114_lx5a_play_text_a_5_1
> > fields:
> >   msg:
> >     selector:
> >       text: null
> >     required: true
> >     name: 小爱将会播放：
> > description: ""
> > icon: mdi:speaker-message
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="702" src="https://private-user-images.githubusercontent.com/12271811/397372410-b01b22f1-b7f7-4439-9429-21bb9c1ef0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjU2OTksIm5iZiI6MTczNDg2NTM5OSwicGF0aCI6Ii8xMjI3MTgxMS8zOTczNzI0MTAtYjAxYjIyZjEtYjdmNy00NDM5LTk0MjktMjFiYjljMWVmMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDExMDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NDEzMDljNzhjZWMxZjJlMjk1Y2I3MjZjZmVmOTkzMzk5ZjA5NjIzNDhhODM1MmYwZTgwNTA1ZDVjMGY5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3cGeslOqym5Vbo7d-C9-MavAx3gz6f6lxuDeVAKfmSM">
> 
> 请问这个代码是写在哪里的 还有这个弹出框是怎么做的？感谢给几个详细截图 感谢。整了很久 依旧搞不懂。


找到一个更优雅的解决方法
1. 设置 --> 设备与服务 --> 辅助元素 --> 创建辅助元素 --> 文本 ，命名为“小爱同学”
2. 设置 --> 自动化与场景 --> 脚本 --> 创建脚本 --> 右上角切换为YAML编辑，粘贴以下内容
（message中的input_text.xiao_ai_tong_xue为上一步创建的文本元素的实体标识符，entity_id需替换为自己音响播放文本的实体id）
```YAML
alias: 小爱播放文本
sequence:
  - action: notify.send_message
    metadata: {}
    data:
      message: " [\"{{ states('input_text.xiao_ai_tong_xue') }}\"] "
    target:
      entity_id: notify.xiaomi_cn_*_play_text*
fields: {}
description: ""
icon: mdi:speaker-message
```
4. 设置 --> 自动化与场景 --> 自动化 --> 创建自动化 
![image](https://github.com/user-attachments/assets/72bd6f97-5f7c-4f8c-8e4b-0be51589488c)
5. 主页添加辅助元素“小爱同学”即可
![image](https://github.com/user-attachments/assets/35647aaf-6c54-4028-b374-0c51b1b3f6f9)

**Comment by LeoYanlv** [comment]
> > > > > > 没整明白咋用，参考龙佬的[hass-xiaomi-miot]那样就挺好的，简单实用。
> > > > > 
> > > > > 
> > > > > 按我上面图里这样用就行，就能让小爱朗读指定内容了
> > > > 
> > > > 
> > > > 必须在自动化里才可以吗？我想直接让小爱播放指定文字，比如我在楼下，喊楼上的人吃饭，像auto那个集成直接在播放文本里输入要播放的文字就行了，这个就实现不了了吗？
> > > 
> > > 
> > > 创建一个脚本, entity_id改成自己音响的播放实体就可以了。
> > > alias: 小爱播放文本
> > > sequence:
> > >   - action: notify.send_message
> > >     metadata: {}
> > >     data:
> > >       message: " [\"{{ msg }} \"] "
> > >     target:
> > >       entity_id: notify.xiaomi_cn_108269114_lx5a_play_text_a_5_1
> > > fields:
> > >   msg:
> > >     selector:
> > >       text: null
> > >     required: true
> > >     name: 小爱将会播放：
> > > description: ""
> > > icon: mdi:speaker-message
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > <img alt="image" width="702" src="https://private-user-images.githubusercontent.com/12271811/397372410-b01b22f1-b7f7-4439-9429-21bb9c1ef0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjU2OTksIm5iZiI6MTczNDg2NTM5OSwicGF0aCI6Ii8xMjI3MTgxMS8zOTczNzI0MTAtYjAxYjIyZjEtYjdmNy00NDM5LTk0MjktMjFiYjljMWVmMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDExMDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NDEzMDljNzhjZWMxZjJlMjk1Y2I3MjZjZmVmOTkzMzk5ZjA5NjIzNDhhODM1MmYwZTgwNTA1ZDVjMGY5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3cGeslOqym5Vbo7d-C9-MavAx3gz6f6lxuDeVAKfmSM">
> > 
> > 
> > 请问这个代码是写在哪里的 还有这个弹出框是怎么做的？感谢给几个详细截图 感谢。整了很久 依旧搞不懂。
> 
> 找到一个更优雅的解决方法
> 
> 1. 设置 --> 设备与服务 --> 辅助元素 --> 创建辅助元素 --> 文本 ，命名为“小爱同学”
> 2. 设置 --> 自动化与场景 --> 脚本 --> 创建脚本 --> 右上角切换为YAML编辑，粘贴以下内容
>    （message中的input_text.xiao_ai_tong_xue为上一步创建的文本元素的实体标识符，entity_id需替换为自己音响播放文本的实体id）
> 
> alias: 小爱播放文本
> sequence:
>   - action: notify.send_message
>     metadata: {}
>     data:
>       message: " [\"{{ states('input_text.xiao_ai_tong_xue') }}\"] "
>     target:
>       entity_id: notify.xiaomi_cn_*_play_text*
> fields: {}
> description: ""
> icon: mdi:speaker-message
> 3. 设置 --> 自动化与场景 --> 自动化 --> 创建自动化
> 
> ![image](https://github.com/user-attachments/assets/72bd6f97-5f7c-4f8c-8e4b-0be51589488c) 4. 主页添加辅助元素“小爱同学”即可
> 
> ![image](https://github.com/user-attachments/assets/35647aaf-6c54-4028-b374-0c51b1b3f6f9)

你这个方法，文字 部分 怎么变化呢？不可能都是一个声音吧
