### ISSUE TITLE
[Bug]: zimi.plug.zncz01 功率统计存在问题

### ISSUE THREAD

**Issue by DoraTiger** [XiaoMi/ha_xiaomi_home#223]
### Describe the bug / 描述问题

存在两个power_consumption参数，且内容不一致。

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/1dff2ced-1fdd-4e15-b953-c0b894f3a465)
如图，翻阅spec得知，一个功率参数为[power-consumption](https://miot-spec.org/miot-spec-v2/spec/service?type=urn:miot-spec-v2:service:power-consumption:0000780E)服务中的[electric-power](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:miot-spec-v2:property:electric-power:00000066)，且统计参数被放大了100倍。
![image](https://github.com/user-attachments/assets/63c6a3bf-9bd5-4856-b240-0777c643fd40)
一个功率参数为[user-electric-power](https://miot-spec.org/miot-spec-v2/spec/service?type=urn:zimi-spec:service:user-electric-power:00007806)中的[electric-power](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:zimi-spec:property:electric-power:00000001)，且显示值不主动更新。
![image](https://github.com/user-attachments/assets/bcdd3350-ec14-42b6-8dc1-8e2cf1bcf070)

### Expected behavior / 预期结果

期望跟米家中显示一致。

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

docker版本，无OS

### Xiaomi Home integration version / 米家集成版本

v0.1.0

### Additional context / 其他说明

功率部分，自行集成并测试了request#101的内容。

**Comment by DoraTiger** [comment]
same issues #130

**Comment by SusanPhevos** [comment]
xiaomi_home只能根据厂商定义的[MIoT-Spec-V2](https://home.miot-spec.com/spec/zimi.plug.zncz01)生成实体并原样展示设备上报的属性值。厂商开发的米家设备插件对设备上报值做了转换，因此能显示正确。
