### ISSUE TITLE
[Bug]: 安装时出现网络问题，其他集成都可以正常使用！

### ISSUE THREAD

**Issue by zuifengguai** [XiaoMi/ha_xiaomi_home#233]
### Describe the bug / 描述问题

添加集成时出现网络问题，其他集成都可以正常使用！

### To Reproduce / 复现步骤

![PixPin_2024-12-19_16-37-24](https://github.com/user-attachments/assets/d0f73ac0-b6b1-401c-a6f6-688a4111f840)

在启动“Xiaomi Home”的配置向导，请稍候后，就出现了这个问题

### Expected behavior / 预期结果

能正常安装

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by JimmyKmi** [comment]
请提交日志

**Comment by imbytecat** [comment]
<img width="1443" alt="image" src="https://github.com/user-attachments/assets/aa9de171-b76e-4db3-b3bd-cf789b5c30ff" />
一样问题，我是HAOS，要怎么查看日志？

**Comment by zuifengguai** [comment]
> <img alt="image" width="1443" src="https://private-user-images.githubusercontent.com/15844288/397375525-aa9de171-b76e-4db3-b3bd-cf789b5c30ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTIxMjAsIm5iZiI6MTczNDYxMTgyMCwicGF0aCI6Ii8xNTg0NDI4OC8zOTczNzU1MjUtYWE5ZGUxNzEtYjc2ZS00ZGIzLWIzYmQtY2Y3ODliNWMzMGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEyMzcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMWEyYWYxMzVlODgyNjNhZWQwYjExMjIxZGU2MWNhODNmMzYyY2VkNzdiODliYWYzOGNjMDZkNmRjMjNjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XjVVvYxPAQKvmjskuAOC4J8JVYFgtW1UPZG3jYXFqUM"> 一样问题，我是HAOS，要怎么查看日志？

我也是虚拟机安装的HAOS出现的这个问题

**Comment by zuifengguai** [comment]
问题解决！！主路由的安全设置问题!打开了爱快内网禁止ping，取消了解决了。
![PixPin_2024-12-20_09-31-47](https://github.com/user-attachments/assets/80d8cb61-1fbc-440a-8865-e1e0d71809b6)

**Comment by JimmyKmi** [comment]
> 问题解决！！主路由的安全设置问题!打开了爱快内网禁止ping，取消了解决了。 ![PixPin_2024-12-20_09-31-47](https://private-user-images.githubusercontent.com/46639423/397586394-80d8cb61-1fbc-440a-8865-e1e0d71809b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NzIyMzIsIm5iZiI6MTczNDY3MTkzMiwicGF0aCI6Ii80NjYzOTQyMy8zOTc1ODYzOTQtODBkOGNiNjEtMWZiYy00NDBhLTg4NjUtZTFlMGQ3MTgwOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA1MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNDU3YzY5NTdiZWQyNGEwZDhmYWRkNGNmYzgwMGFjMzllNDMyMjExZTMwNDk2ZGI4NDkzNGI3YWRhNzkxOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SxuYSib1R2P1aWLDSREWyB4eydF_7C6ykWtpp8QQZXk)

恭喜解决，其实爱快家用情况下只建议打开 禁止外网PING、丢弃无效链接访问、TCP最大报文长度
