### ISSUE TITLE
[Bug]: OAuth2 Redirect URL无法自定义为IP

### ISSUE THREAD

**Issue by llity** [XiaoMi/ha_xiaomi_home#239]
### Describe the bug / 描述问题

OAuth2 Redirect URL无法自定义为IP

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/c071ce72-399b-4917-abb0-a178fbd28de1)

### Expected behavior / 预期结果

OAuth2 Redirect URL 指定为固定的IP地址

### Home Assistant Core version / Home Assistant Core 版本

最新版

### Home Assistant Operation System version / Home Assistant Operation System 版本

最新版

### Xiaomi Home integration version / 米家集成版本

最新版

### Additional context / 其他说明

![image](https://github.com/user-attachments/assets/9e5240e3-9019-4239-a61d-c1a8956144fd)

**Comment by gujiangjiang** [comment]
我通过修改hosts为homeassistant.local成功了，目前只能这样先用

**Comment by llity** [comment]
> 我通过修改hosts为homeassistant.local成功了，目前只能这样先用

在那里修改哦？我用的容器版HA

**Comment by llity** [comment]
> 与该问题为同一个问题 #8 解决方案 #6

行不通，需要官方修改是最好的办法。

**Comment by LOVE2CMOL** [comment]
> > 与该问题为同一个问题 #8 解决方案 #6
> 
> 行不通，需要官方修改是最好的办法。

回调的页面 改成你自己的地址就行了

**Comment by LOVE2CMOL** [comment]
官方不改是因为那个oath2页面是有地址白名单的 而白名单就只有homeassistant.local

**Comment by yichengchen** [comment]
> > 与该问题为同一个问题 #8 解决方案 #6
> 
> 行不通，需要官方修改是最好的办法。

改用浏览器的电脑本机的host

**Comment by SusanPhevos** [comment]
#39

**Comment by ZhaiSoul** [comment]
OAuth协议回调地址是这样的，不能够让用户自己随意改

**Comment by llity** [comment]
按照前面的方法已解决
