### ISSUE TITLE
[Bug]: 添加账号后设置失败

### ISSUE THREAD

**Issue by chkdsk228** [XiaoMi/ha_xiaomi_home#24]
### Describe the bug / 描述问题

设置失败

### To Reproduce / 复现步骤

正常添加账号后提示设置失败。无法获取设备
<img width="208" alt="image" src="https://github.com/user-attachments/assets/a134d462-9776-477a-b76f-0f310a561047" />

### Expected behavior / 预期结果

成功获取设备

### Home Assistant Core version / Home Assistant Core 版本

2024.10.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241002.3

### Xiaomi Home integration version / 米家集成版本

0.1.0

**Comment by xzlq1234** [comment]
2024-12-16 22:03:54.338 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_client] ha.225ede98a9fd50853xxxxxx, on properties_changed, b'{"method":"properties_changed","params":{"did":"407546870","siid":12,"piid":14,"value":225}}'

**Comment by topsworld** [comment]
core版本需要2024.11.0及以上

**Comment by chkdsk228** [comment]
> core版本需要2024.11.0及以上

是的发完之后就看到了哈哈哈哈。已经做更新解决了。

**Comment by Meteors27** [comment]
2025.01.02版本不行

> core版本需要2024.11.0及以上
