### ISSUE TITLE
[Bug]: 获取登录授权信息（OAuth token）失败

### ISSUE THREAD

**Issue by benkwan49** [XiaoMi/ha_xiaomi_home#240]
### Describe the bug / 描述问题

登录后手动输入IP地址后跳转回Homeassistant界面显示获取登录授权信息（OAuth token）失败

### To Reproduce / 复现步骤

1、集成搜索添加xiaomi_home
2、跳转登录小米账号
3、回调地址修改为本地ip
![Snipaste_2024-12-19_17-58-30](https://github.com/user-attachments/assets/63b89498-8daf-44bb-a158-7b29721eb746)
4、出现获取登录授权信息失败
![Snipaste_2024-12-19_17-59-24](https://github.com/user-attachments/assets/f995daa5-3cc7-4b50-af40-00979f9c2180)

### Expected behavior / 预期结果

正确授权获取智能设备信息

### Home Assistant Logs / 系统日志

docker Host网络模式部署，报错日志如下：
![Snipaste_2024-12-19_18-00-29](https://github.com/user-attachments/assets/6f5a54ac-4a1e-422d-84b8-1ee6f407c579)

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by galaxyGGG** [comment]
I met the same problem.

Here is what the home-assistant log showed:

```
日志记录器: custom_components.xiaomi_home.config_flow
来源: custom_components/xiaomi_home/config_flow.py:315
集成: Xiaomi Home ([文档](https://github.com/XiaoMi/ha_xiaomi_home/blob/main/README.md), [问题](https://github.com/XiaoMi/ha_xiaomi_home/issues))
首次出现: 22:31:19 (15 次总计出现)
上次记录: 22:31:24

task_oauth exception, get_token_error

```

**Comment by galaxyGGG** [comment]
![image](https://github.com/user-attachments/assets/1c04b859-c02b-463f-abad-90189692770b)
Now the error shows as this

**Comment by galaxyGGG** [comment]
I re-cloned the latest github code, and now the auth process has been passed.

**Comment by topsworld** [comment]
Hello, look at the above log, it shows that the network connection fails, which leads to the failure of obtaining the token. Please confirm whether the local network is normal.

**Comment by benkwan49** [comment]
I don't know if it's a network issue, but after updating the latest version it worked fine and the problem didn't recur
