### ISSUE TITLE
[Bug]: aqara E1开关被按下描述缺少左，中，右的标记，且按下无法触发自动化

### ISSUE THREAD

**Issue by felixkang** [XiaoMi/ha_xiaomi_home#254]
### Describe the bug / 描述问题

配置自动化时，aqara E1开关被按下描述缺少左，中，右的标记，且按下后无法触发自动化

### To Reproduce / 复现步骤
1、配置页面显示异常
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/3e8ce13b-9e4d-4900-8113-2703a6691dba" />
2、点击后有事件发生，但是无法触发自动化
<img width="2032" alt="image" src="https://github.com/user-attachments/assets/433a5fe3-81ca-43f0-bffe-720bfdc50608" />

### Expected behavior / 预期结果

期望显示为 开关 左键 被按下

### Home Assistant Core version / Home Assistant Core 版本

2024.14.0

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by SusanPhevos** [comment]
您好！请上传一下问题复现时debug级别的Home Assistant日志。
日志级别设置方法详见[这里](https://github.com/XiaoMi/ha_xiaomi_home/blob/main/doc/CONTRIBUTING_zh.md#%E6%8A%A5%E5%91%8A%E9%97%AE%E9%A2%98)。

**Comment by felixkang** [comment]
> 您好！请上传一下问题复现时debug级别的Home Assistant日志。 日志级别设置方法详见[这里](https://github.com/XiaoMi/ha_xiaomi_home/blob/main/doc/CONTRIBUTING_zh.md#%E6%8A%A5%E5%91%8A%E9%97%AE%E9%A2%98)。

日志已上传，复现步骤及硬件环境说明如下：
1-家中主网关为 xiaomi 中枢网关，子网关为 aqara E1网关，aqara E1零火三键开关通过子网关接入米家
2-配置了四个自动化，三个是被按下触发（因为显示中没有左，中，右的区分，所以全部配上了），一个是开关状态切换触发
3-结果为开关状态切换可以触发自动化，三个被按下无法触发

PS：通过 xiaomi-gateway3配置被按下是可以正常触发
<img width="2032" alt="image" src="https://github.com/user-attachments/assets/4e443759-20cf-43d8-8a57-0b32fffdc1c7" />
[Xiaomi Home Log Dec 22 2024 (1).log](https://github.com/user-attachments/files/18221444/Xiaomi.Home.Log.Dec.22.2024.1.log)

**Comment by felixkang** [comment]
<img width="2032" alt="image" src="https://github.com/user-attachments/assets/6f2dd11e-b15c-4ec5-bbf9-f12b308be4d1" />
另外我发现在 red-node 里可以选到单击这个事件，也可以正常触发

**Comment by SusanPhevos** [comment]
1、配置页面显示异常
第一张图“书房开关 设备确认 设备确认 被按下”对应的是控制中的Button实体。厂商配置中文没有区分按键名称，因此三个选项显示的名称完全一样。请帮忙验证这个 #412 修改是否解决了这里的显示问题。更新源代码后，需要更新实体转换规则、重新添加一次设备，修改才能生效：[设置 > 设备与服务 > 已配置 > Xiaomi Home](https://my.home-assistant.io/redirect/integration/?domain=xiaomi_home) > 配置 > 更新实体转换规则 & 更新设备列表

2、点击后有事件发生，但是无法触发自动化
按照你的需求，自动化的触发条件应当设置为“事件”而不是“设备”。
首先，在设备事件实体的详情页复制“实体标识符”，例如
![Screenshot from 2024-12-24 15-27-08](https://github.com/user-attachments/assets/9a7c1177-f9db-41b7-a0a2-d445f6092bed)
然后在自动化规则中添加“事件”触发条件，
![Screenshot from 2024-12-24 15-25-29](https://github.com/user-attachments/assets/c739ff64-b37b-42fc-8301-c48c35eeb933)
“事件类型”填写上一步复制的“实体标识符”。

**Comment by felixkang** [comment]
> 1、配置页面显示异常 第一张图“书房开关 设备确认 设备确认 被按下”对应的是控制中的Button实体。厂商配置中文没有区分按键名称，因此三个选项显示的名称完全一样。请帮忙验证这个 #412 修改是否解决了这里的显示问题。更新源代码后，需要更新实体转换规则、重新添加一次设备，修改才能生效：[设置 > 设备与服务 > 已配置 > Xiaomi Home](https://my.home-assistant.io/redirect/integration/?domain=xiaomi_home) > 配置 > 更新实体转换规则 & 更新设备列表
> 
> 2、点击后有事件发生，但是无法触发自动化 按照你的需求，自动化的触发条件应当设置为“事件”而不是“设备”。 首先，在设备事件实体的详情页复制“实体标识符”，例如 ![Screenshot from 2024-12-24 15-27-08](https://private-user-images.githubusercontent.com/5947653/398359457-9a7c1177-f9db-41b7-a0a2-d445f6092bed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDk0MDUsIm5iZiI6MTczNTA0OTEwNSwicGF0aCI6Ii81OTQ3NjUzLzM5ODM1OTQ1Ny05YTdjMTE3Ny1mOWRiLTQxYjctYTBhMi1kNDQ1ZjYwOTJiZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMTQwNTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmI5ZmI4ODNlMmE3ODQ2ZmU2MjIxNmEwNGY5NDZmMzBmNDFlMDgxODkzZjU3OGNkOGQwOTRkOThkZjRkYzE0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IesjACvQ1Mbpu_qMwWLj8gd0R0qdrVvUtY0c0b4TbCA) 然后在自动化规则中添加“事件”触发条件， ![Screenshot from 2024-12-24 15-25-29](https://private-user-images.githubusercontent.com/5947653/398359759-c739ff64-b37b-42fc-8301-c48c35eeb933.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDk0MDUsIm5iZiI6MTczNTA0OTEwNSwicGF0aCI6Ii81OTQ3NjUzLzM5ODM1OTc1OS1jNzM5ZmY2NC1iMzdiLTQyZmMtODMwMS1jNDhjMzVlZWI5MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMTQwNTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTViZmI4ZGQ1NTllMDZhYzdkOTliNmE5Mzc5MmNjOGZjMjllYTVlYWViZjYzMTA5ZGRiNjZmNTUwZmM1ZjAxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SHEY_8NosllbH728ba28jwzZMmjE1843GzmJ7HoZv-U) “事件类型”填写上一步复制的“实体标识符”。

<img width="2032" alt="image" src="https://github.com/user-attachments/assets/5c2a8dff-1e52-4b7d-b698-de514365f148" />
<img width="2032" alt="image" src="https://github.com/user-attachments/assets/ebad9994-7274-448c-908e-df37e3e6e104" />
经测试，显示问题并未修复，请知悉

**Comment by felixkang** [comment]
<img width="2032" alt="image" src="https://github.com/user-attachments/assets/b18348a8-de3a-4116-8495-3dca4560733b" />

方法二配置也不生效，我发现我按下开关之后不会收到任何事件，只有点击页面上的『按下』两个字才能触发这个事件，之前能够显示事件，应当是xiaomi-gateway3上报的，因为我停用xiaomi-gateway3之后就再也没看到这个事件了

**Comment by SusanPhevos** [comment]
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/18622299/398427706-b18348a8-de3a-4116-8495-3dca4560733b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTA3NTMsIm5iZiI6MTczNTA5MDQ1MywicGF0aCI6Ii8xODYyMjI5OS8zOTg0Mjc3MDYtYjE4MzQ4YTgtZGUzYS00MTE2LTg0OTUtM2RjYTQ1NjA3MzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAxMzQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkODlkMzVhYmE5OWIxMDI1ZjYyODExYTlhY2U5ZTgyMmI0NDZmMWMxM2FjMDE1NmM5N2E3YjRlYjZhMWIzZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZBpIrGTRZXug2TQPYiGuFQ8x1gg_obFor47b2jsrQr8">
> 方法二配置也不生效，我发现我按下开关之后不会收到任何事件，只有点击页面上的『按下』两个字才能触发这个事件，之前能够显示事件，应当是xiaomi-gateway3上报的，因为我停用xiaomi-gateway3之后就再也没看到这个事件了

这个地方选错了，你在图中选的是控制中的button而不是事件中的event，实体标识符要以Event开头而不是以Button开头。我在你之前提交的日志里看到xiaomi_home接收了正确的事件消息，该事件是非标准MIoT-Spec-V2，不能隐藏非标准生成实体。要在你发的第二张图中，去选 “书房开关*左键控制继电器开关 单击”的实体标识符，注意这个实体名称中有一个星号*

**Comment by felixkang** [comment]
> > <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/18622299/398427706-b18348a8-de3a-4116-8495-3dca4560733b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTA3NTMsIm5iZiI6MTczNTA5MDQ1MywicGF0aCI6Ii8xODYyMjI5OS8zOTg0Mjc3MDYtYjE4MzQ4YTgtZGUzYS00MTE2LTg0OTUtM2RjYTQ1NjA3MzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAxMzQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkODlkMzVhYmE5OWIxMDI1ZjYyODExYTlhY2U5ZTgyMmI0NDZmMWMxM2FjMDE1NmM5N2E3YjRlYjZhMWIzZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZBpIrGTRZXug2TQPYiGuFQ8x1gg_obFor47b2jsrQr8">
> > 方法二配置也不生效，我发现我按下开关之后不会收到任何事件，只有点击页面上的『按下』两个字才能触发这个事件，之前能够显示事件，应当是xiaomi-gateway3上报的，因为我停用xiaomi-gateway3之后就再也没看到这个事件了
> 
> 这个地方选错了，你在图中选的是控制中的button而不是事件中的event，实体标识符要以Event开头而不是以Button开头。我在你之前提交的日志里看到xiaomi_home接收了正确的事件消息，该事件是非标准MIoT-Spec-V2，不能隐藏非标准生成实体。要在你发的第二张图中，去选 “书房开关*左键控制继电器开关 单击”的实体标识符，注意这个实体名称中有一个星号*

<img width="2032" alt="image" src="https://github.com/user-attachments/assets/78c9b20e-5e20-47d5-974f-15bf1bad11d4" />
<img width="2032" alt="image" src="https://github.com/user-attachments/assets/fa125a02-4602-4744-82c2-a25e2173bff0" />
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/a91b8552-0753-4705-9a8d-67b2de1f4dea" />

升级到最新版本之后，带 * 的实体全部消失了，原来页面上很多属性也没有了

**Comment by felixkang** [comment]
> > <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/18622299/398427706-b18348a8-de3a-4116-8495-3dca4560733b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTA3NTMsIm5iZiI6MTczNTA5MDQ1MywicGF0aCI6Ii8xODYyMjI5OS8zOTg0Mjc3MDYtYjE4MzQ4YTgtZGUzYS00MTE2LTg0OTUtM2RjYTQ1NjA3MzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAxMzQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkODlkMzVhYmE5OWIxMDI1ZjYyODExYTlhY2U5ZTgyMmI0NDZmMWMxM2FjMDE1NmM5N2E3YjRlYjZhMWIzZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZBpIrGTRZXug2TQPYiGuFQ8x1gg_obFor47b2jsrQr8">
> > 方法二配置也不生效，我发现我按下开关之后不会收到任何事件，只有点击页面上的『按下』两个字才能触发这个事件，之前能够显示事件，应当是xiaomi-gateway3上报的，因为我停用xiaomi-gateway3之后就再也没看到这个事件了
> 
> 这个地方选错了，你在图中选的是控制中的button而不是事件中的event，实体标识符要以Event开头而不是以Button开头。我在你之前提交的日志里看到xiaomi_home接收了正确的事件消息，该事件是非标准MIoT-Spec-V2，不能隐藏非标准生成实体。要在你发的第二张图中，去选 “书房开关*左键控制继电器开关 单击”的实体标识符，注意这个实体名称中有一个星号*

<img width="1988" alt="image" src="https://github.com/user-attachments/assets/aceaa34d-c746-4bb1-9fff-2c480b81bc70" />

<img width="2032" alt="image" src="https://github.com/user-attachments/assets/bd3f7294-ab24-408c-b5b9-66890cb0206f" />
配事件不能触发，我改用状态之后可以正常触发

**Comment by felixkang** [comment]
另外发现，这个触发时间很不稳定，有时立即触发，有的需要三四秒
[Xiaomi Home Log Dec 25 2024.log](https://github.com/user-attachments/files/18246438/Xiaomi.Home.Log.Dec.25.2024.log)
