### ISSUE TITLE
[Bug]: 无法获取正确认证跳转地址

### ISSUE THREAD

**Issue by lqfdnr1** [XiaoMi/ha_xiaomi_home#258]
### Describe the bug / 描述问题

添加集成时候无法获取正确认证跳转地址，导致认证失败

### To Reproduce / 复现步骤

![Screenshot_20241220_005719_com kiwibrowser browser](https://github.com/user-attachments/assets/0de0c0de-cec0-48d4-9309-5a936f97975a)

### Expected behavior / 预期结果

认证地址可编辑

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.2.1

### Xiaomi Home integration version / 米家集成版本

V0.1.2

**Comment by SusanPhevos** [comment]
See #39

**Comment by 712042790** [comment]
编辑一下你电脑上的HOSTS文件就可以了
