### ISSUE TITLE
[Bug]: "Xiaomi Home Device Lost changes" all the time 

### ISSUE THREAD

**Issue by Stooovie** [XiaoMi/ha_xiaomi_home#259]
### Describe the bug / 描述问题

The integration notifies repeatedly and frequently of device changes, even after updating the device list and there not being any changes. 

### To Reproduce / 复现步骤

1) use HA with this integration
2) that's it. Notifications will come. 

### Expected behavior / 预期结果

No such unnecessary notifications

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.1

### Xiaomi Home integration version / 米家集成版本

0.1.0

### Additional context / 其他说明

![IMG_0175](https://github.com/user-attachments/assets/bf0f9a3f-1527-45d7-8230-2e6662bbc9c3)

**Comment by topsworld** [comment]
Hello, this notification reveals the actual situation of the devices. Is the state of these devices truly offline?

**Comment by topsworld** [comment]
> Hello, this notification reveals the actual situation of the devices. Is the state of these devices truly offline?

Later, we will support the device filtering feature, enabling you to filter out certain offline devices, and thus they will not be displayed.

**Comment by Stooovie** [comment]
They re offline yes (truly offline, disconnected for the winter season). The issue is, the notification pops up several times a day, when there's no changes in the status of the devices.
