### ISSUE TITLE
[Bug]: 设备实体状态未知

### ISSUE THREAD

**Issue by FeryHuo** [XiaoMi/ha_xiaomi_home#263]
### Describe the bug / 描述问题

小爱音箱万能遥控版、Xiaomi路由器AX3000T 实体状态未知

### To Reproduce / 复现步骤

小爱音箱万能遥控版，通知程序中智能音箱 播放文本、智能音箱执行文本指令都是未知状态
Xiaomi路由器AX3000T 路由器连接设备数、路由器上传速度、路由器下载速度都是未知状态
![wechat_2024-12-20_080947_662](https://github.com/user-attachments/assets/0d740f86-b7c2-46fd-b7ca-63096c1ee94a)
![wechat_2024-12-20_080957_756](https://github.com/user-attachments/assets/9903eef6-ddac-4331-9efb-0a99808b18ca)
![wechat_2024-12-20_081204_959](https://github.com/user-attachments/assets/0fcc6b6c-87f8-4e0c-9e80-9e365338fcdc)

### Expected behavior / 预期结果

能够正常显示状态

### Home Assistant Logs / 系统日志

[](
[home-assistant_2024-12-20T00-13-07.780Z.log](https://github.com/user-attachments/files/18204354/home-assistant_2024-12-20T00-13-07.780Z.log)

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

2024.12.4

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by al-one** [comment]
走 notify 服务

**Comment by topsworld** [comment]
如上，非问题，ISSUE关闭
