### ISSUE TITLE
[Bug]: aqara水浸传感器无水浸状态

### ISSUE THREAD

**Issue by sam0773** [XiaoMi/ha_xiaomi_home#277]
### Describe the bug / 描述问题

无水浸传感器的状态传感器

### To Reproduce / 复现步骤

使用xiaomi home接入 aqara水浸传感器lumi.sensor_wleak.aq1，查看该设备的实体,页面只有三个未知事件
![QQ截图20241220134344](https://github.com/user-attachments/assets/06e11bf9-769f-4ca6-bba2-db41f7c228b5)

### Expected behavior / 预期结果

显示水浸传感器的水浸状态

### Home Assistant Core version / Home Assistant Core 版本

2024.12.1

### Home Assistant Operation System version / Home Assistant Operation System 版本

无

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by L-Morningstar** [comment]
我也有这个问题

**Comment by sam0773** [comment]
这是一封自动回复邮件你好，您所发的邮件我已收到，我将在阅读后尽快给你回复。

**Comment by sam0773** [comment]
怎么解决呢？

**Comment by topsworld** [comment]
您好，事件需要有过触发才会有值。
