### ISSUE TITLE
[Bug]: BE6500路由器的中枢不显示虚拟事件

### ISSUE THREAD

**Issue by 810517583** [XiaoMi/ha_xiaomi_home#280]
### Describe the bug / 描述问题

路由器的中枢不显示虚拟事件,无法判断是否是因为路由器的原因

### To Reproduce / 复现步骤

![QQ20241220-140356](https://github.com/user-attachments/assets/43c24e38-48bb-40cd-b422-e806d4e6ce5d)
![QQ20241220-140405](https://github.com/user-attachments/assets/c6c1b08c-78ef-4a58-a87a-5fa81bfc9244)
![QQ20241220-140459](https://github.com/user-attachments/assets/66e701ea-5e32-4fb0-aaa1-2db88cd6eebf)
路由器的中枢不显示虚拟事件，且路由器的中枢不显示虚拟事件,无法判断是否是因为路由器的原因

### Expected behavior / 预期结果

设备列表中可以选择虚拟事件，并且可以显示正在执行的虚拟事件

### Home Assistant Logs / 系统日志

没有

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

docker

### Xiaomi Home integration version / 米家集成版本

v0.1.2

### Additional context / 其他说明

暂无

**Comment by 810517583** [comment]
![QQ20241220-141724](https://github.com/user-attachments/assets/81c6645f-771b-4612-91dc-060a68ab886c)

**Comment by Stream-z** [comment]
> ![QQ20241220-141724](https://private-user-images.githubusercontent.com/8052916/397635381-81c6645f-771b-4612-91dc-060a68ab886c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzc2MzQsIm5iZiI6MTczNDY3NzMzNCwicGF0aCI6Ii84MDUyOTE2LzM5NzYzNTM4MS04MWM2NjQ1Zi03NzFiLTQ2MTItOTFkYy0wNjBhNjhhYjg4NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjBUMDY0ODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDkyZmJiMWI4OWNjMDdmNDMxMDBjZmM0Y2Y0NDkzOTZhOWFkNWVhZDllNWJlMzUxY2Q1ZTJiNDU1MGQzNWMwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pPqnA1Sz4yOBbx-h4G1UJNKfV9fKRsHhmPtBMf3kgVg)

格式不对，正确格式为 ["xxxxxx"]

**Comment by Stream-z** [comment]
另外虚拟事件的内容，可以到“开发者工具”——“状态”，找到中枢的的“event.xiaomi_cn_xxxxx_hub1_virtual_event_e_4_1”类似的这个实体，实体属性中是有具体的发生的虚拟事件的内容的

**Comment by topsworld** [comment]
如上，非问题，问题关闭

**Comment by 810517583** [comment]
> > ![QQ20241220-141724](https://private-user-images.githubusercontent.com/8052916/397635381-81c6645f-771b-4612-91dc-060a68ab886c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzc2MzQsIm5iZiI6MTczNDY3NzMzNCwicGF0aCI6Ii84MDUyOTE2LzM5NzYzNTM4MS04MWM2NjQ1Zi03NzFiLTQ2MTItOTFkYy0wNjBhNjhhYjg4NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjBUMDY0ODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDkyZmJiMWI4OWNjMDdmNDMxMDBjZmM0Y2Y0NDkzOTZhOWFkNWVhZDllNWJlMzUxY2Q1ZTJiNDU1MGQzNWMwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pPqnA1Sz4yOBbx-h4G1UJNKfV9fKRsHhmPtBMf3kgVg)
> 
> 格式不对，正确格式为 ["xxxxxx"]。ha中产生虚拟事件，推荐使用notify服务，“notify.send_message”用这个action，调用中枢的notify实体

图裂了

**Comment by victor647** [comment]
所以如果要让中枢网关产生一个虚拟事件，要怎么搞？
