### ISSUE TITLE
认证后提示没有设备或实体

### ISSUE THREAD

**Issue by LittleKa3235** [XiaoMi/ha_xiaomi_home#286]
### Describe the Bug / 描述问题

认证后提示没有设备或实体

### How to Reproduce / 复现步骤

 认证过程中没有问题，也能看到实体数量，但认证后提示没有设备或实体
[
![QQ20241220-164713](https://github.com/user-attachments/assets/cee0812f-68d4-43c9-8c76-32ea77a74278)
](url)

### Expected Behavior / 预期结果

正常导入实体

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.config_entries
来源: config_entries.py:594
首次出现: 16:34:19 (8 次总计出现)
上次记录: 16:45:25

Error setting up entry Ka: 2274011 [中国大陆] for xiaomi_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry
    raise err
  File "/config/custom_components/xiaomi_home/__init__.py", line 140, in async_setup_entry
    device.spec_transform()
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 540, in spec_transform
    prop.external_unit = self.unit_convert(prop.unit)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 619, in unit_convert
    'μS/cm': UnitOfConductivity.MICROSIEMENS_PER_CM,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'

### Home Assistant Core Version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.0

**Comment by alanhi** [comment]
我的是docker版本，镜像升级到最新版本解决的

**Comment by SusanPhevos** [comment]
同 #176

**Comment by yingkeafffafaf** [comment]
在线等，一样的问题，求解决

**Comment by Leeeeeeooo** [comment]
我也是 求解决踢我一下

**Comment by Leeeeeeooo** [comment]
> 我的是docker版本，镜像升级到最新版本解决的

你好 你是说升级docker还是升级ha呀，请教

**Comment by alanhi** [comment]
升级ha

**Comment by Leeeeeeooo** [comment]
> 升级ha

感谢 我试试

**Comment by Leeeeeeooo** [comment]
> 升级ha

可惜了 没有用，已经是最新版12.5了 哭了
