### ISSUE TITLE
小爱音箱没有conversation播放控制实体

### ISSUE THREAD

**Issue by 86727515** [XiaoMi/ha_xiaomi_home#287]
### Describe the Bug / 描述问题

小爱音箱没有conversation播放控制实体

### How to Reproduce / 复现步骤

小爱音箱没有conversation播放控制实体，无法获取语音响应

### Expected Behavior / 预期结果

conversation播放控制实体

### Home Assistant Logs / 系统日志

小爱音箱没有conversation播放控制实体

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.2

**Comment by SusanPhevos** [comment]
参考 #57 #51 ,Notify Entity用于向音箱发送需要播放的文本，打开“Action 调试”还会显示文本输入框，可手动输入需要播放的文本。

**Comment by milumet** [comment]
我也遇到这个问题了，后面发现是没有开 action 调试。但是给他加入文本就变成一个错误

**Comment by 86727515** [comment]
我指的不是发送文本让音箱去播放。而是主动获取交谈内容。比如对音箱说，小爱同学，打开空调。node-red中获取到“打开空调”这四个字的文本
