### ISSUE TITLE
卷帘应该具备开合角度、遮光角度2种特性

### ISSUE THREAD

**Issue by tiandeyu** [XiaoMi/ha_xiaomi_home#291]
@topsworld 抱歉，我的issue描述有误，卷帘应该具备开合角度、遮光角度2种特性
开启curtain模式，只有开合角度，没有遮光角度
![image](https://github.com/user-attachments/assets/6d125161-fba6-41a4-9ddc-ecb723cd809d)
![image](https://github.com/user-attachments/assets/731a1645-c71a-406b-8ed1-5bd6100a70d2)
我预期的应该是这样，这是我自己写的窗帘插件
![image](https://github.com/user-attachments/assets/be6c8bd0-d988-45f4-a237-2c432ee6b087)

据我了解，杜亚卷帘是使用行程的最后5%来控制遮光，米家App上面使用的是短行程开控制遮光角度，要到行程末尾才有效

_Originally posted by @tiandeyu in https://github.com/XiaoMi/ha_xiaomi_home/issues/11#issuecomment-2549964099_

**Comment by SusanPhevos** [comment]
xiaomi_home根据设备厂商定义的[MIoT-Spec-V2](https://home.miot-spec.com/spec/dooya.curtain.c1)生成实体，厂商未定义的内容无法生成实体。

**Comment by wb871029** [comment]
> xiaomi_home根据设备厂商定义的[MIoT-Spec-V2](https://home.miot-spec.com/spec/dooya.curtain.c1)生成实体，厂商未定义的内容无法生成实体。

杜亚卷帘在米家极客版里有开到（0-100）%执行动作

**Comment by tiandeyu** [comment]
所以我理解可能有2方面原因，在于miot不完善或者厂家不规范的代码
1，miot没有标准的调光卷帘模板
2，厂家代码不规范

**Comment by SusanPhevos** [comment]
> > xiaomi_home根据设备厂商定义的[MIoT-Spec-V2](https://home.miot-spec.com/spec/dooya.curtain.c1)生成实体，厂商未定义的内容无法生成实体。
> 
> 杜亚卷帘在米家极客版里有开到（0-100）%执行动作

极客版也是通过设置 siid=2 piid=7 target-position 属性值实现。xiaomi_home根据该属性生成开合角度实体。

**Comment by SusanPhevos** [comment]
> 所以我理解可能有2方面原因，在于miot不完善或者厂家不规范的代码 1，miot没有标准的调光卷帘模板 2，厂家代码不规范

米家APP插件是厂商自己开发，厂商未定义的Spec内容，也可能通过插件做特殊处理实现。
