### ISSUE TITLE
vrf添加的米家空调无法正常控制

### ISSUE THREAD

**Issue by liuyu1483** [XiaoMi/ha_xiaomi_home#293]
### Describe the Bug / 描述问题

vrf添加的米家空调无法正常控制

### How to Reproduce / 复现步骤

vrf添加的米家空调无法正常控制，打开后，能控制，但关闭后就不能打开按钮，没效果，没反应。只有当空调被提前开启后，能控制制热制冷，温度调节，但关闭后，就控制不了了

### Expected Behavior / 预期结果

vrf添加的米家空调无法正常控制

### Home Assistant Logs / 系统日志

vrf添加的米家空调无法正常控制

### Home Assistant Core Version / Home Assistant Core 版本

2024.12

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13.0

### Xiaomi Home Integration Version / 米家集成版本

0.1.0

**Comment by SusanPhevos** [comment]
同 #16 ，试试 [v0.1.3](https://github.com/XiaoMi/ha_xiaomi_home/releases/tag/v0.1.3)
