### ISSUE TITLE
小米米家电子温湿度计pro无法获取数据

### ISSUE THREAD

**Issue by minedeed** [XiaoMi/ha_xiaomi_home#301]
### Describe the Bug / 描述问题

无法获取数据，显示不可用

### How to Reproduce / 复现步骤

![IMG_6411](https://github.com/user-attachments/assets/f3e20bd1-3afc-430e-a836-391a618b6593)
![IMG_6412](https://github.com/user-attachments/assets/5f38b0a1-97ed-4f0c-bb5f-a0745d9a0c4e)
![IMG_6413](https://github.com/user-attachments/assets/e49f77e6-9a5a-4deb-9245-c284c2d9224a)
![IMG_6414](https://github.com/user-attachments/assets/dd11e1d9-c259-4d16-a252-d593a4dfc206)
![IMG_6415](https://github.com/user-attachments/assets/00249e6f-764c-4090-b51e-0e8e4a9dbbfc)

### Expected Behavior / 预期结果

正常显示

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.2

**Comment by JimmyKmi** [comment]
![wechat_2024-12-21_173603_073](https://github.com/user-attachments/assets/bae01c4a-d6c2-4371-a562-dffb4ccc2c2d)

实测可用，请检查网络连接是否稳定

**Comment by minedeed** [comment]
> ![wechat_2024-12-21_173603_073](https://private-user-images.githubusercontent.com/69306141/397918478-bae01c4a-d6c2-4371-a562-dffb4ccc2c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODUwMDAsIm5iZiI6MTczNDc4NDcwMCwicGF0aCI6Ii82OTMwNjE0MS8zOTc5MTg0NzgtYmFlMDFjNGEtZDZjMi00MzcxLWE1NjItZGZmYjRjY2MyYzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEyMzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNjMyMDMwYjMyZDMzMzUwMWRhMTMxZjFhZmYxYmJmOWVhYjc5YjA2ZTRmOTQ2MTExYTk4Mjc4ODA4MGQ5Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BWd--8CwyJGmFOV0VXdQbzoINjRbYUOGPh-OGlzpj4k)
> 
> 实测可用，请检查网络连接是否稳定

你好 你这个是那个长方形的设备吗，我们固件版本不一样

**Comment by JimmyKmi** [comment]
> > ![wechat_2024-12-21_173603_073](https://private-user-images.githubusercontent.com/69306141/397918478-bae01c4a-d6c2-4371-a562-dffb4ccc2c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODUwMDAsIm5iZiI6MTczNDc4NDcwMCwicGF0aCI6Ii82OTMwNjE0MS8zOTc5MTg0NzgtYmFlMDFjNGEtZDZjMi00MzcxLWE1NjItZGZmYjRjY2MyYzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEyMzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNjMyMDMwYjMyZDMzMzUwMWRhMTMxZjFhZmYxYmJmOWVhYjc5YjA2ZTRmOTQ2MTExYTk4Mjc4ODA4MGQ5Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BWd--8CwyJGmFOV0VXdQbzoINjRbYUOGPh-OGlzpj4k)
> > 实测可用，请检查网络连接是否稳定
> 
> 你好 你这个是那个长方形的设备吗，我们固件版本不一样

您好，我看您的model是miaomiaoce.sensor_ht.t1，我拿了个miaomiaoce.sensor_ht.t1进行复测也是正常的，如图：
![image](https://github.com/user-attachments/assets/2c6d776b-6344-4ab5-85a6-995dc33ab795)

miaomiaoce.sensor_ht.t8 是 miaomiaoce.sensor_ht.t1 的同款迭代产品，两款都正常的

**Comment by minedeed** [comment]
> > > ![wechat_2024-12-21_173603_073](https://private-user-images.githubusercontent.com/69306141/397918478-bae01c4a-d6c2-4371-a562-dffb4ccc2c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODUwMDAsIm5iZiI6MTczNDc4NDcwMCwicGF0aCI6Ii82OTMwNjE0MS8zOTc5MTg0NzgtYmFlMDFjNGEtZDZjMi00MzcxLWE1NjItZGZmYjRjY2MyYzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEyMzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNjMyMDMwYjMyZDMzMzUwMWRhMTMxZjFhZmYxYmJmOWVhYjc5YjA2ZTRmOTQ2MTExYTk4Mjc4ODA4MGQ5Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BWd--8CwyJGmFOV0VXdQbzoINjRbYUOGPh-OGlzpj4k)
> > > 实测可用，请检查网络连接是否稳定
> > 
> > 
> > 你好 你这个是那个长方形的设备吗，我们固件版本不一样
> 
> 您好，我看您的model是miaomiaoce.sensor_ht.t1，我拿了个miaomiaoce.sensor_ht.t1进行复测也是正常的，如图： ![image](https://private-user-images.githubusercontent.com/69306141/397928449-2c6d776b-6344-4ab5-85a6-995dc33ab795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODgzODYsIm5iZiI6MTczNDc4ODA4NiwicGF0aCI6Ii82OTMwNjE0MS8zOTc5Mjg0NDktMmM2ZDc3NmItNjM0NC00YWI1LTg1YTYtOTk1ZGMzM2FiNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMzQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzc0ZTM3NjYyYTgzNjQ5YWZhN2NkYjM2MDAzZDc1OTc4ZjdjYjkwZDZiMjNjM2NhOTY3Mzc4M2UyMzBkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ON57_W85BvI_NMQFii_7InsiEEeTEaUuL681IF1NBQU)
> 
> miaomiaoce.sensor_ht.t8 是 miaomiaoce.sensor_ht.t1 的同款迭代产品，两款都正常的

那这设备需要什么网关介入吗？目前那个房间只有小爱音箱 pro 和米家空调伴侣

**Comment by minedeed** [comment]
你好，通过点击xiaomihome集成，更新设备列表，该问题已经解决了，可能的原因这个设备长期离线，后面直接集成，然后解绑了一次设备，再次重新绑定，导致这个问题，谢谢了

**Comment by sashiburi69** [comment]
> 你好，通过点击xiaomihome集成，更新设备列表，该问题已经解决了，可能的原因这个设备长期离线，后面直接集成，然后解绑了一次设备，再次重新绑定，导致这个问题，谢谢了

我也遇到这个问题了，重新更新列表也不起作用
