### ISSUE TITLE
摄像头没有视频（HA也不会显示摄像头）

### ISSUE THREAD

**Issue by WSXYT** [XiaoMi/ha_xiaomi_home#309]
### Describe the Bug / 描述问题

摄像头没有视频（HA也不会显示摄像头）

### How to Reproduce / 复现步骤

含有摄像头

### Expected Behavior / 预期结果

有摄像头并且可以查看画面

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by JimmyKmi** [comment]
已经有大量相同反馈并有原因说明，提issue前请先检索避免重复提问。

参考：
https://github.com/XiaoMi/ha_xiaomi_home/issues/40
https://github.com/XiaoMi/ha_xiaomi_home/issues/62
https://github.com/XiaoMi/ha_xiaomi_home/issues/160
https://github.com/XiaoMi/ha_xiaomi_home/discussions/292

**Comment by QIAOYANGvg** [comment]
I sincerely hope to have your support. Currently, there are four Xiaomi cameras placed at home. However, during the actual usage process, they are not supported, which indeed causes great inconvenience to daily monitoring. The operation process is cumbersome. It not only takes a lot of time but also makes people feel very troubled. I originally had high expectations for Xiaomi's monitoring devices. After all, the brand has a good reputation. But this experience is really not satisfactory. If this situation continues, it's likely that Xiaomi will hardly be my first choice when I choose monitoring devices in the future.

**Comment by williamchenghu** [comment]
https://github.com/XiaoMi/ha_xiaomi_home/discussions/78#discussioncomment-12951230 yea dude, no joke, i didn't expect to see this ways of maintaining a community. good job folks 👏

> I sincerely hope to have your support. Currently, there are four Xiaomi cameras placed at home. However, during the actual usage process, they are not supported, which indeed causes great inconvenience to daily monitoring. The operation process is cumbersome. It not only takes a lot of time but also makes people feel very troubled. I originally had high expectations for Xiaomi's monitoring devices. After all, the brand has a good reputation. But this experience is really not satisfactory. If this situation continues, it's likely that Xiaomi will hardly be my first choice when I choose monitoring devices in the future.

**Comment by bulesky520** [comment]
应该要加摄像头显示啊，只给本地局域网连接也行
