### ISSUE TITLE
小米人脸识别智能门锁X全部实体不可用

### ISSUE THREAD

**Issue by twfjcn** [XiaoMi/ha_xiaomi_home#315]
### Describe the Bug / 描述问题

小米人脸识别智能门锁X全部实体不可用，但是日志检测事件正常。

### How to Reproduce / 复现步骤

小米人脸识别智能门锁X全部实体不可用，但是日志检测事件正常。

### Expected Behavior / 预期结果

传感器显示正常，实体时间正常

### Home Assistant Logs / 系统日志

无                    

### Home Assistant Core Version / Home Assistant Core 版本

2024-11.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14       

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

### Additional Context / 其他说明

小米人脸识别智能门锁X全部实体不可用，但是日志检测事件正常。

**Comment by SusanPhevos** [comment]
厂商定义的设备[MIoT-Spec-V2](https://home.miot-spec.com/spec/lumi.lock.bmcn05)除电池电量之外，所有属性不可读、不可写、不通知，故xiaomi_home无法生成相应实体。

**Comment by Lengran1992** [comment]
这款门锁应该是Aqara代工的，属性不可读写很不可思议

**Comment by twfjcn** [comment]
> 厂商定义的设备[MIoT-Spec-V2](https://home.miot-spec.com/spec/lumi.lock.bmcn05)除电池电量之外，所有属性不可读、不可写、不通知，故xiaomi_home无法生成相应实体。

![微信截图_20241222155544](https://github.com/user-attachments/assets/fd406ece-0fbf-4f93-bee8-a5041a04365e)
虽然，但是.....为啥xiaomi miot Auto第三方插件可以做到读取电量等信息呢？

**Comment by SusanPhevos** [comment]
> > 厂商定义的设备[MIoT-Spec-V2](https://home.miot-spec.com/spec/lumi.lock.bmcn05)除电池电量之外，所有属性不可读、不可写、不通知，故xiaomi_home无法生成相应实体。
> 
> 那这个样子的话，**米家**这个应用理论上也无法获取相应的数据导致无法查看、控制对应的设备，除非它的实现没有符合权限管理甚至没有走小米服务器？ 这是不是也算是厂商的不规范，任何属性都至少可读吧（就算是安全类的数据做完权限验证也该是可读的）。

蓝牙直连的属性有些可读、可写，米家APP设备插件由厂商自行开发，厂商可能自己做了特殊转换。
