### ISSUE TITLE
Yeelight屏幕挂灯Pro版无法调整颜色

### ISSUE THREAD

**Issue by tjq19940331** [XiaoMi/ha_xiaomi_home#328]
### Describe the Bug / 描述问题

Yeelight屏幕挂灯Pro版无法调整颜色，目前是显示为一个实体，只能调整前面的色温灯，无法控制后面的颜色灯。

### How to Reproduce / 复现步骤

其他问题：这个问题同样出现在小爱同学控制上，可以看到ha_xiaomi_home生成的实体可以根据小爱指令变化颜色，但是实际并没有反应，猜测调用的模型不正确，此问题在Xiaomi Miot Auto也相同。

原因猜测：Yeelight屏幕挂灯有普通版和Pro版，Pro版的两个灯是分开控制的。Pro版开启局域网控制后，安装Yeelight的官方插件，可以看到是两个实体，分别控制色温灯和颜色灯，且控制是正常的。

### Expected Behavior / 预期结果

希望像Yeelight官方插件一样，Pro版本挂灯生成两个灯实体，分别控制两个灯。

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4

### Additional Context / 其他说明

_No response

设备详情页截图
![image](https://github.com/user-attachments/assets/f4aa88d5-191d-4eb4-99a6-86289170e9b7)

**Comment by shenmirenQUQ** [comment]
这个还是用Yeelight的集成吧，也稳定好用

**Comment by pv0402** [comment]
这个真不如yeelight自己的，用这个功能又不会变多

**Comment by SusanPhevos** [comment]
您好！请发一下设备详情页截图。

**Comment by tjq19940331** [comment]
> 您好！请发一下设备详情页截图。

**Comment by Lengran1992** [comment]
Yeelight屏幕挂灯也是如此![image](https://github.com/user-attachments/assets/b344231e-ca56-4924-b69f-ea6422e34c48)![image](https://github.com/user-attachments/assets/36926d69-3014-4b1b-8af4-ecade1623eae)

**Comment by SusanPhevos** [comment]
See #151

**Comment by tjq19940331** [comment]
感觉问题不在于实体个数，当前实体是可以正确读取灯的颜色，只是无法更改颜色，插件目前更改颜色是通过调整color（miot-spec-v2中SSID2  PIID4 ）这个属性值，而这个属性值的调整并没有起到控制效果，尝试过利用python-miot等方式更改过此值，亦无效果。比较好奇的是插件目前是怎么读取到灯的颜色的呢？
另外：有个小建议，如果无法控制灯的颜色，应将实体初始化为色温灯，删除掉颜色控制选项。

**Comment by tjq19940331** [comment]
> See #151

感觉问题不在于实体个数，当前实体是可以正确读取灯的颜色，只是无法更改颜色，插件目前更改颜色是通过调整color（miot-spec-v2中SSID2  PIID4 ）这个属性值，而这个属性值的调整并没有起到控制效果，尝试过利用python-miot等方式更改过此值，亦无效果。比较好奇的是插件目前是怎么读取到灯的颜色的呢？
另外：有个小建议，如果无法控制灯的颜色，应将实体初始化为色温灯，删除掉颜色控制选项。
