### ISSUE TITLE
智能门锁X经常性离线

### ISSUE THREAD

**Issue by yeungchie** [XiaoMi/ha_xiaomi_home#331]
### Describe the Bug / 描述问题

智能门锁X经常性离线，设备lumi.lock.bmcn05

### How to Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/ef91d6ad-f9cc-42c0-9d70-8827d7f44784)

### Expected Behavior / 预期结果

/

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.2

### Home Assistant Operation System Version / Home Assistant Operation System 版本

unknown

### Xiaomi Home Integration Version / 米家集成版本

v0.1.2

**Comment by NOisi-x** [comment]
v1.0.3问题依旧

**Comment by yeungchie** [comment]
![image](https://github.com/user-attachments/assets/1edd951c-9f70-4f7e-a776-f18946626853)

**Comment by SusanPhevos** [comment]
See #315

**Comment by windowlife** [comment]
一样的问题，看#315，意思是解决不了，让用xiaomi_miot插件
![screenshot_2024-12-25_13-43-14](https://github.com/user-attachments/assets/cf2e116a-082d-4878-ade8-1da9ec795a76)
