### ISSUE TITLE
[Bug]: 中枢网关缺少触发虚拟事件以及无法检测产生的虚拟事件

### ISSUE THREAD

**Issue by lixinyu02** [XiaoMi/ha_xiaomi_home#34]
### Describe the bug / 描述问题

中枢网关缺少触发虚拟事件以及无法检测产生的虚拟事件

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/02cac800-48c4-4502-8cbc-02d80152c424)

### Expected behavior / 预期结果

中枢网关可以在ha中正确检测到产生的事件以及正常产生事件

### Home Assistant Core version / Home Assistant Core 版本

2024.12.2

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by JimmyKmi** [comment]
可以开启 Action 调试模式进行事件触发，格式 ["事件"]，使用自动化可以通过通知触发。虚拟事件是事件，不存在状态。

**Comment by FDrag0n** [comment]
https://github.com/XiaoMi/ha_xiaomi_home/discussions/29
可以参考我这里问的，已经成功触发了

**Comment by topsworld** [comment]
如上，感谢热心网友教程，问题关闭

**Comment by moxuec** [comment]
产生虚拟事件可以不使用通知，直接选择设备--动作。需要注意的是事件的值为数组
![image](https://github.com/user-attachments/assets/92bc1b76-224a-4c88-9392-118e8b539fef)
