### ISSUE TITLE
Are E-Scooters supported or is it a bug?

### ISSUE THREAD

**Issue by bavarianbytes** [XiaoMi/ha_xiaomi_home#343]
### Describe the Bug / 描述问题

A have one device in my Xiaomi Home App which is a Xiaomi Electric Scooter 4 Pro 2nd Gen. In the configuration wizard i see my correct family number, but it shows 0 devices. So i cannot proceed. My country in the app is Germany, so i tried region Europe in the HA integration. Tried also China, but no change.

### How to Reproduce / 复现步骤
<img width="604" alt="Bildschirmfoto 2024-12-21 um 21 55 30" src="https://github.com/user-attachments/assets/2f7cc0d2-8333-4ad6-9b53-e288f1e6c6d4" />

### Expected Behavior / 预期结果

See one device (scooter) in the config wizard.

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by SusanPhevos** [comment]
The e-scooter is a type of device with high safety level and high privacy sensitivity. It can only be accessed by BLE GATT. No data of the e-scooter is transmitted or stored by Xiaomi Cloud or Xiaomi gateway. Thus, it can not be imported into xiaomi_home integration.
