### ISSUE TITLE
多个家庭多个物理HA 只能认证一个吗?

### ISSUE THREAD

**Issue by coolzhi** [XiaoMi/ha_xiaomi_home#347]
### Describe the Bug / 描述问题

多个家庭多个物理HA 只能认证一个吗?

### How to Reproduce / 复现步骤

https://github.com/XiaoMi/ha_xiaomi_home/discussions/346

### Expected Behavior / 预期结果

多个家庭多个物理HA 只能认证一个吗?

### Home Assistant Logs / 系统日志

https://github.com/XiaoMi/ha_xiaomi_home/discussions/346

### Home Assistant Core Version / Home Assistant Core 版本

多个家庭多个物理HA 只能认证一个吗?

### Home Assistant Operation System Version / Home Assistant Operation System 版本

多个家庭多个物理HA 只能认证一个吗?

### Xiaomi Home Integration Version / 米家集成版本

多个家庭多个物理HA 只能认证一个吗?

### Additional Context / 其他说明

https://github.com/XiaoMi/ha_xiaomi_home/discussions/346

**Comment by topsworld** [comment]
您好，可以分别物理HA认证。
