### ISSUE TITLE
家里路由如何重启之后，经常就出现设备全部不可用，xiaomi_home集成更新设备就显示“配置失败。网络连接异常，请检查设备网络配置“。

### ISSUE THREAD

**Issue by githubgj** [XiaoMi/ha_xiaomi_home#349]
### Describe the Bug / 描述问题

xiaomi_home集成更新设备就显示“配置失败。网络连接异常，请检查设备网络配置“

### How to Reproduce / 复现步骤

<img width="1401" alt="截屏2024-12-22 11 13 48" src="https://github.com/user-attachments/assets/fab1bfcc-7cf2-4f1e-8d53-dbec45610c0e" />

### Expected Behavior / 预期结果

重启不会出现设备不可用情况

### Home Assistant Logs / 系统日志

<img width="1401" alt="截屏2024-12-22 11 13 48" src="https://github.com/user-attachments/assets/896ea329-e2fb-49fd-a08c-ec36bf165170" />
[home-assistant_xiaomi_home_2024-12-22T03-09-58.678Z.log](https://github.com/user-attachments/files/18220673/home-assistant_xiaomi_home_2024-12-22T03-09-58.678Z.log)

### Home Assistant Core Version / Home Assistant Core 版本

2024.11.1

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by topsworld** [comment]
您好，麻烦检查下路由设置是否静止内网ping操作，我们会在下个版本优化下网路检查逻辑。

**Comment by githubgj** [comment]
> 您好，麻烦检查下路由设置是否静止内网ping操作，我们会在下个版本优化下网路检查逻辑。

这种情况都是在家里路由器重启之后发生的。路由器重启之后有时候没问题，有时候就会发生这种情况，这种随机问题发生两次了，这会和路由设置是否静止内网ping操作有关吗？

**Comment by topsworld** [comment]
> > 您好，麻烦检查下路由设置是否静止内网ping操作，我们会在下个版本优化下网路检查逻辑。
> 
> 这种情况都是在家里路由器重启之后发生的。路由器重启之后有时候没问题，有时候就会发生这种情况，这种随机问题发生两次了，这会和路由设置是否静止内网ping操作有关吗？

和这个有关，网络异常，集成不会去连接小米云，所以导致不可用

**Comment by githubgj** [comment]
> > > 您好，麻烦检查下路由设置是否静止内网ping操作，我们会在下个版本优化下网路检查逻辑。
> > 
> > 
> > 这种情况都是在家里路由器重启之后发生的。路由器重启之后有时候没问题，有时候就会发生这种情况，这种随机问题发生两次了，这会和路由设置是否静止内网ping操作有关吗？
> 
> 和这个有关，网络异常，集成不会去连接小米云，所以导致不可用

好的，我去试试修改。但是以后这种情况会优化吗？因为其他集成从来没出现过这种情况

**Comment by topsworld** [comment]
> > > > 您好，麻烦检查下路由设置是否静止内网ping操作，我们会在下个版本优化下网路检查逻辑。
> > > 
> > > 
> > > 这种情况都是在家里路由器重启之后发生的。路由器重启之后有时候没问题，有时候就会发生这种情况，这种随机问题发生两次了，这会和路由设置是否静止内网ping操作有关吗？
> > 
> > 
> > 和这个有关，网络异常，集成不会去连接小米云，所以导致不可用
> 
> 好的，我去试试修改。但是以后这种情况会优化吗？因为其他集成从来没出现过这种情况

会优化

**Comment by yanzhijian** [comment]
不好意思没有看懂，现在是否有临时解决方案，我的内网允许ping，但是同样无法连接。我用的多模网管2，已经设置了静态ip，我应该如何排查或者在版本更新前临时解决问题呢？

**Comment by yanzhijian** [comment]
> > 不好意思没有看懂，现在是否有临时解决方案，我的内网允许ping，但是同样无法连接。我用的多模网管2，已经设置了静态ip，我应该如何排查或者在版本更新前临时解决问题呢？
> 
> custom_components/xiaomi_home/miot/miot_network.py 195行 ` return output.returncode == 0`改成 `return True` 改完重启HA 临时解决一下

非常感谢您的帮助，但我修改后，依旧无法连接。我通过ha的重启和重启ha的主机都尝试了，依旧是无法连接。或许还有别的方式吗？

**Comment by zhengjier** [comment]
> > > 不好意思没有看懂，现在是否有临时解决方案，我的内网允许ping，但是同样无法连接。我用的多模网管2，已经设置了静态ip，我应该如何排查或者在版本更新前临时解决问题呢？
> > 
> > 
> > custom_components/xiaomi_home/miot/miot_network.py 195行 ` return output.returncode == 0`改成 `return True` 改完重启HA 临时解决一下
> 
> 非常感谢您的帮助，但我修改后，依旧无法连接。我通过ha的重启和重启ha的主机都尝试了，依旧是无法连接。或许还有别的方式吗？

应该是197行的 `return False` 改成 `return True` 然后重启HA绕过网络检查

**Comment by shen-lan** [comment]
![image](https://github.com/user-attachments/assets/39cba862-27b7-4756-9d8a-cd3dd00beb72)
一样的报错 有啥好的解决办法吗？部署在op软路由上。

**Comment by shen-lan** [comment]
@shen-lan  好了 参考楼上直接改代码可以了.....
