### ISSUE TITLE
ha自动化中，设置 小爱音箱Pro  播放文本的值，自动化运行到该步骤时报错，ha自动化停止运行

### ISSUE THREAD

**Issue by zmdsclzj** [XiaoMi/ha_xiaomi_home#351]
### Describe the Bug / 描述问题

ha自动化中，设置 小爱音箱Pro  播放文本的值，自动化运行到该步骤时报错，ha自动化停止运行

### How to Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/f02e0827-9222-461e-b535-a5ea3f235e21)
![image](https://github.com/user-attachments/assets/f18612ef-8cad-4e50-a28c-621eac98af11)

### Expected Behavior / 预期结果

希望可以播放

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

Frontend 20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.0

**Comment by topsworld** [comment]
https://note.p.lzj.ac.cn/s/bd635048-ae38-43c9-9f31-d61175a01cf6/doc/5lit5p6i572r5ywz6jma5ouf5lql5lu26kem5yr5yk5omn6kgm-BBcVquoizJ

您好，非问题，请详细查看往期issue
