### ISSUE TITLE
易来 韶华系列吸顶灯 只有开关功能 无法调节亮度色温

### ISSUE THREAD

**Issue by gao19970120** [XiaoMi/ha_xiaomi_home#353]
### Describe the Bug / 描述问题

易来 韶华系列吸顶灯 只有开关功能 无法调节亮度色温  model:yeelink.light.celling17

### How to Reproduce / 复现步骤

在米家集成中添加易来 韶华系列吸顶灯

### Expected Behavior / 预期结果

增加条件色温亮度功能

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b0

**Comment by SusanPhevos** [comment]
您好！请发一下设备详情页截图，以及点击灯泡图标后弹出的界面截图。

**Comment by gao19970120** [comment]
可以调节，之前没找到，不好意思
