### ISSUE TITLE
米家直流变频落地扇1x 无法调节风速

### ISSUE THREAD

**Issue by gao19970120** [XiaoMi/ha_xiaomi_home#354]
### Describe the Bug / 描述问题

米家直流变频落地扇1x 无法调节风速

### How to Reproduce / 复现步骤

米家直流变频落地扇1x ，model: dmaker.fan.p5，只有摆风角度可调节，无法调节风模式和风速

### Expected Behavior / 预期结果

增加调节风模式（自然风/直吹风）和风速调节

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.0

### Xiaomi Home Integration Version / 米家集成版本

0.1.4b0

**Comment by SusanPhevos** [comment]
您好！请问是xiaomi_home没有生成模式和风速实体？还是生成了实体但操作无效？
