### ISSUE TITLE
小爱音响pro没有播放指定文本和执行文本指令的动作

### ISSUE THREAD

**Issue by gao19970120** [XiaoMi/ha_xiaomi_home#355]
### Describe the Bug / 描述问题

小爱音响pro没有播放指定文本和执行文本指令的动作

### How to Reproduce / 复现步骤

在miot auto中可以实现

### Expected Behavior / 预期结果

添加播放指定文本和执行文本指令的动作

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.0

### Xiaomi Home Integration Version / 米家集成版本

0.1.4b2

**Comment by topsworld** [comment]
您好，可以看下readme或者去discussion中查看使用方法

**Comment by topsworld** [comment]
Duplicate of #96  非问题，问题关闭。
