### ISSUE TITLE
登入成功了但是无法获取到设备列表

### ISSUE THREAD

**Issue by weizhaowu-se** [XiaoMi/ha_xiaomi_home#356]
### Describe the Bug / 描述问题

登入成功了但是无法获取到设备列表

### How to Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/ed8184c8-ef43-495b-bcb5-0776efddfe17)

### Expected Behavior / 预期结果

获取设备列表

### Home Assistant Logs / 系统日志

![image](https://github.com/user-attachments/assets/88508e54-d4a5-44a5-bfe0-7646bb607a13)

### Home Assistant Core Version / Home Assistant Core 版本

2024.7.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

2024.7.3

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b0

### Additional Context / 其他说明

部署位置是群晖上的容器部署

**Comment by topsworld** [comment]
您好，可以将容器升级到最新版本，我们后面会做一些兼容

**Comment by 96sir-com** [comment]
我也遇到了这个问题，是虚拟几部署的homeassets，集成版本v0.1.4b0

**Comment by 96sir-com** [comment]
我也遇到了这个问题，是虚拟几部署的homeassistant，集成版本v0.1.4b0

**Comment by xdtxAM** [comment]
> 您好，可以将容器升级到最新版本，我们后面会做一些兼容

使用最新的官方镜像，也遇到了这个问题。同样的报错

**Comment by yhcghjj** [comment]
我也是，更新了0.1.4b0也不行，一样的错误

**Comment by weizhaowu-se** [comment]
> > 您好，可以将容器升级到最新版本，我们后面会做一些兼容
> 
> 使用最新的官方镜像，也遇到了这个问题。同样的报错

我更新了ha的Docker镜像之后就可以了

**Comment by yhcghjj** [comment]
> 我也是，更新了0.1.4b0也不行，一样的错误

更新以后重新创建容器就可以了，感谢工作人员。
