### ISSUE TITLE
路由器重启后所有设备掉线，并无法更新设备列表，经多次尝试均无法将设备上线。

### ISSUE THREAD

**Issue by yanzhijian** [XiaoMi/ha_xiaomi_home#359]
### Describe the Bug / 描述问题

路由器重启后所有米家设备离线通过重置等方式也无法重新连接。

### How to Reproduce / 复现步骤

多模网关2 设备已经固定ip
重启路由器后，homeassistant的启动速度比路由器要快，应该是没有连网，在 [#349]中提问过，但是根据修改配置文件的解答方案依旧无法解决此问题。故单独开一个issue，希望提供一个临时解决方案。
ha和多模网关都是固定ip，所有的Wi-Fi设备都是固定ip。
<img width="368" alt="image" src="https://github.com/user-attachments/assets/5fbdf9eb-63ab-4515-a3cc-1f18836948f6" />
在设备中更新设备列表会提示上图所示错误。与 #349  不同。希望可以给一个临时解决方案并尽快在后续更新中解决该问题。先谢谢了。

### Expected Behavior / 预期结果

重启路由器后，应该可以自动完成连接。

### Home Assistant Logs / 系统日志

[home-assistant_xiaomi_home_2024-12-22T13-01-24.389Z.log](https://github.com/user-attachments/files/18221921/home-assistant_xiaomi_home_2024-12-22T13-01-24.389Z.log)
[home-assistant_2024-12-22T13-03-40.910Z.log](https://github.com/user-attachments/files/18221923/home-assistant_2024-12-22T13-03-40.910Z.log)

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by topsworld** [comment]
看日志，全是DNS解析错误，麻烦检查下本地DNS解析是否正常
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host ha.api.io.mi.com:443 ssl:default [DNS server returned answer with no data]

__mips_connect, connect error, [Errno -5] Name has no usable address

**Comment by yanzhijian** [comment]
> 看日志，全是DNS解析错误，麻烦检查下本地DNS解析是否正常 aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host ha.api.io.mi.com:443 ssl:default [DNS server returned answer with no data]
> 
> __mips_connect, connect error, [Errno -5] Name has no usable address

去翻了一圈，docker装hass,他本地自建了一个dns,虚拟出了很多本地网段，所以请求不出去。正在尝试解决。这玩意也太坑了 哈哈

**Comment by topsworld** [comment]
如上，非问题，问题关闭，后续集成会完善错误提示
