### ISSUE TITLE
小米蓝牙无线双键开关部分事件缺失

### ISSUE THREAD

**Issue by felixkang** [XiaoMi/ha_xiaomi_home#360]
### Describe the Bug / 描述问题

小米蓝牙无线双键开关无法选择单击左键、单击右键这些事件

### How to Reproduce / 复现步骤

<img width="2032" alt="image" src="https://github.com/user-attachments/assets/8d6bf867-6f84-4487-b002-45b15af20516" />
1-只显示了单击事件，没有区分左右键
2-已开启标准模式，米家上可正常选择事件

![AA6E363D-4D37-4024-994F-63A292268DE6_4_5005_c](https://github.com/user-attachments/assets/c1aa4192-0c8f-4a3d-86d0-b0ed4d3e7e3a)
![6B4CFA10-0AD9-4034-A5FC-2E8DB09E6004_4_5005_c](https://github.com/user-attachments/assets/713dd3ed-4662-413a-805a-26259db695e5)
![ECDB0F73-0F4B-417A-A1A1-94A9FEDF2B25_4_5005_c](https://github.com/user-attachments/assets/9051c216-3268-4d54-8deb-d76f522f4d62)

### Expected Behavior / 预期结果

像米家 APP 一样选择所有事件

### Home Assistant Logs / 系统日志

[Uploading Xiaomi Home Log Dec 22 2024 (2).log…]()

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by SusanPhevos** [comment]
在单击事件详情页，应该会看到是哪个按键触发了事件

**Comment by LeoYanlv** [comment]
[https://github.com/XiaoMi/ha_xiaomi_home/issues/319#issue-2753823165](url)
和我上报的问题一样，事件缺少子参数
