### ISSUE TITLE
米家体脂秤 S400 Pro无法获取数据

### ISSUE THREAD

**Issue by liuzhen99** [XiaoMi/ha_xiaomi_home#362]
### Describe the Bug / 描述问题

米家体脂秤 S400 Pro无法获取数据

### How to Reproduce / 复现步骤

![112](https://github.com/user-attachments/assets/4a6c904f-c6a5-4782-a350-e75bc4693792)

### Expected Behavior / 预期结果

获取体重等数据

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b0

**Comment by SusanPhevos** [comment]
厂商定义的设备[MIoT-Spec-V2](https://home.miot-spec.com/spec/xiaomi.scales.ms110)所有属性不可读、不可写、不通知，故xiaomi_home无法生成显示体重等数据的实体。

**Comment by tufeikafei** [comment]
这个看来只能用gateway3 来支持了。。

**Comment by nflipeng** [comment]
我的也是一样，没有体脂秤的数据，只有一些事件。
