### ISSUE TITLE
米家互联网空调C1，空调实体显示未知

### ISSUE THREAD

**Issue by zhangqiang930** [XiaoMi/ha_xiaomi_home#363]
### Describe the Bug / 描述问题

空调实体显示未知

### How to Reproduce / 复现步骤

![微信截图_20241222231801](https://github.com/user-attachments/assets/f0074bc5-d463-4409-8fcd-8453d1ee6184)

### Expected Behavior / 预期结果

希望修复正常

### Home Assistant Logs / 系统日志

[home-assistant_2024-12-22T15-18-53.481Z.log](https://github.com/user-attachments/files/18222371/home-assistant_2024-12-22T15-18-53.481Z.log)

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

无

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

### Additional Context / 其他说明

设备信息
xiaomi.aircondition.ma2
访问地址
https://[home.mi.com/webapp/content/baike/product/index.html?model=xiaomi.aircondition.ma2](https://home.mi.com/webapp/content/baike/product/index.html?model=xiaomi.aircondition.ma2#/)#/

**Comment by zhangqiang930** [comment]
手动操作下空调，恢复正常。。

**Comment by SusanPhevos** [comment]
日志看起来是设备添加后，首次获取属性值失败，我们排查一下
