### ISSUE TITLE
小米智能门锁 M30 Pro无法获取到解锁方式、解锁id、解锁位置、锁状态、解锁时间等信息

### ISSUE THREAD

**Issue by x838902** [XiaoMi/ha_xiaomi_home#372]
### Describe the Bug / 描述问题

1.小米智能门锁 M30 Pro无法获取到解锁方式、解锁id、解锁位置、锁状态、解锁时间等信息；2.错误的告警信息(在米家app中实际没产出告警，猜测是开锁时锂电池和干电池安装的提示信息)

### How to Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/427be3e0-02f7-40ec-bae4-70aef5e30a32)
![image](https://github.com/user-attachments/assets/5807d41f-8e49-4305-b887-1d24aecd1d0a)
![image](https://github.com/user-attachments/assets/7103eb98-c5a6-4298-aef5-b7a57828ac08)

下面是我通过gateway3集成获取到的信息
![image](https://github.com/user-attachments/assets/b06cc832-d62e-42ac-8661-1d899631abfd)

### Expected Behavior / 预期结果

1.正确显示门锁开关操作相关的信息；2.不显示无效的报警信息(或者展示告警的具体内容)

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

0.1.3

**Comment by earlzz** [comment]
loock.lock.fcl201  鹿客v5max也有这个问题
<img width="370" alt="截屏2024-12-25 17 42 12" src="https://github.com/user-attachments/assets/8b47f124-22dd-4667-b0e0-5fc850d464bb" />
<img width="319" alt="截屏2024-12-25 17 42 59" src="https://github.com/user-attachments/assets/6ff828d7-6559-48a0-a06b-14dd75701794" />

**Comment by goodhelp** [comment]
我这个云米的锁，显示的信息更少，基本没啥用
![7160357e-b173-482f-a1e4-33c9fecb7e49](https://github.com/user-attachments/assets/c1e85e16-18a1-4729-807e-fc290fa62b10)

**Comment by x838902** [comment]
今天又看了下，这些信息应该可以在自动化中使用
查看实体信息，是有这些信息的
![image](https://github.com/user-attachments/assets/3d4187ae-b307-4fae-a562-853e66c1d276)

**Comment by goodhelp** [comment]
> 今天又看了下，这些信息应该可以在自动化中使用 查看实体信息，是有这些信息的 ![image](https://private-user-images.githubusercontent.com/52066731/398627449-3d4187ae-b307-4fae-a562-853e66c1d276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODkxMzMsIm5iZiI6MTczNTE4ODgzMywicGF0aCI6Ii81MjA2NjczMS8zOTg2Mjc0NDktM2Q0MTg3YWUtYjMwNy00ZmFlLWE1NjItODUzZTY2YzFkMjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA0NTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YjE4Mjk5MTUyMGU3ZDFmMmQ1NTVmYjI1MmI5ODczOTI1NTAwODMzZjBlN2NjOWU4MDVkZWNlMTM4OTI0ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IXeeAQgr-Nq0THf1JqwQRJlFkqJI8dIbbrFZc6oJx9c)

果然如你所说，有这些信息，node-red中可以直接使用

**Comment by goodhelp** [comment]
不过这个属性，要过35秒左右才出现，太慢了
![Uploading 7160357e-b173-482f-a1e4-33c9fecb7e49.png…]()

**Comment by goodhelp** [comment]
不过这个属性，要过35秒左右才出现，太慢了
![1](https://github.com/user-attachments/assets/750ad72f-6e0e-4318-91b9-6b6c8b24f633)

**Comment by x838902** [comment]
你再检查一下，应该不能这么慢，我看了下比我gateway3本地接入的还是快一点
实际使用中gateway3接入的有大概5s的延迟
![image](https://github.com/user-attachments/assets/9dbaf579-04f5-476f-a197-4f115e31e1a2)

**Comment by goodhelp** [comment]
可以了，开门时取的属性，和过一会儿去取的属性不一样，开门时有new_state和old_sate，加上new_state取属性就正常了！基本没有延时!

**Comment by idevmo** [comment]
麻烦问下大佬们，这里能获取到门锁视频的实时推流地址吗，或者录像文件下载地址也行，想把视频转存到NAS里面。

**Comment by x838902** [comment]
> 麻烦问下大佬们，这里能获取到门锁视频的实时推流地址吗，或者录像文件下载地址也行，想把视频转存到NAS里面。

不行，获取不了流，录像的话你看看能不能抓下包
