### ISSUE TITLE
[Bug]: Disable ping check

### ISSUE THREAD

**Issue by diaznet** [XiaoMi/ha_xiaomi_home#38]
### Describe the bug / 描述问题

Ping checks failing prevents setup of the integration

### To Reproduce / 复现步骤

In my setup home assistant is not allowed to ping to teh Internet.
In custom_components/xiaomi_home/miot/miot_network.py access to various DNS servers via ping is checked prior to allowing setup of teh integration.
Please implement a mechanism so this could be bypassed or disabled. 

### Expected behavior / 预期结果

DNS check is disabled or bypassed when required by advanced users

### Home Assistant Core version / Home Assistant Core 版本

2024.11.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

Docker

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by topsworld** [comment]
Thanks for your suggestion, we will update the network monitoring logic in the future
