### ISSUE TITLE
手动更新设备列表时，用户应可选择包括/排除哪些设备

### ISSUE THREAD

**Issue by zz66** [XiaoMi/ha_xiaomi_home#384]
### Describe the Bug / 描述问题

集成不支持的设备，会反复提示设备离线，把设备设置为Disabled依然会提示离线。

### How to Reproduce / 复现步骤

![Screenshot_2024-12-23-12-14-24-942_io homeassistant companion android-edit](https://github.com/user-attachments/assets/3a79b239-a6ef-4295-beeb-b3939a3eac87)

### Expected Behavior / 预期结果

建议在手动更新设备列表时，用户可选择包括或者排除哪些设备。

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by mmzhi** [comment]
支持，我有一个小米对讲机，一直提示离线，比较心烦
