### ISSUE TITLE
Xiaomi Home 集成错误 

### ISSUE THREAD

**Issue by qq173972819** [XiaoMi/ha_xiaomi_home#387]
### Describe the Bug / 描述问题

Xiaomi Home 集成错误 检测到 Insane(29999458, cn) 出现错误，请进入选项页面重新配置。  错误信息: 认证信息失效，云端链路将不可用，请进入 Xiaomi Home 集成页面，点击“选项”重新认证

### How to Reproduce / 复现步骤

认证配置
检测到本地认证信息过期，请重新开始认证

当前登录地区: 中国大陆
OAuth2 认证跳转地址
OAuth2 认证跳转地址为 http://homeassistant.local:8123/，Home Assistant 需要与当前操作终端（例如，个人电脑）在同一局域网内，且操作终端能通过该地址访问 Home Assistant 首页，否则登录认证可能会失败。

认证跳转地址

http://homeassistant.local:8123

无法认证  未知错误

### Expected Behavior / 预期结果

认证成功

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

0.1.3

**Comment by dacancc** [comment]
如果是无法跳转，可以在跳转后将地址栏中的http://homeassistant.local:8123/改为你hass地址，或者在路由器将主机名homeassistant.local与你的hass的ip绑定（不要科学上网）

**Comment by xjpz** [comment]
一样出现过，重启HA后重新授权解决

**Comment by yuqy96** [comment]
今天在路由器自动重启后出现了这个问题，重新授权后解决

**Comment by topsworld** [comment]
您好，最新的v0.1.4b0已经修复该问题

**Comment by topsworld** [comment]
如上，问题修复，issue关闭。
