### ISSUE TITLE
添加集成后，设备实体未生成问题

### ISSUE THREAD

**Issue by hass-demacia** [XiaoMi/ha_xiaomi_home#388]
### Describe the Bug / 描述问题

登陆后有提示多个家，设备数量，但是完成配置后，没有设备生成

### How to Reproduce / 复现步骤

1. 登陆认证完成
2. 默认勾选配置

### Expected Behavior / 预期结果

-

### Home Assistant Logs / 系统日志

志记录器: homeassistant.config_entries
来源: config_entries.py:594
首次出现: 14:44:35 (7 次总计出现)
上次记录: 14:52:18

Error setting up entry Xiaomi:XXXXXXX [中国大陆] for xiaomi_home
Error setting up entry XXXXXXXX: XXXXXXX [中国大陆] for xiaomi_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry
    raise err
  File "/config/custom_components/xiaomi_home/__init__.py", line 140, in async_setup_entry
    device.spec_transform()
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 531, in spec_transform
    service_entity = self.parse_miot_service_entity(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 478, in parse_miot_service_entity
    prop.external_unit = self.unit_convert(prop.unit)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 630, in unit_convert
    unit_map['μS/cm'] = UnitOfConductivity.MICROSIEMENS_PER_CM
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'

### Home Assistant Core Version / Home Assistant Core 版本

2024.10.2

### Home Assistant Operation System Version / Home Assistant Operation System 版本

-

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

### Additional Context / 其他说明

看报错的参数，像净水器设备处理的问题

**Comment by Leeeeeeooo** [comment]
好多人都反映了这个问题没人解决啊，我是docker重下了HA最新12.5的镜像，再添加了一次集成，还是无设备或实体，而且没有任何报错。但是家里设备的离线上线，HA会有通知，离谱。

**Comment by hass-demacia** [comment]
> 好多人都反映了这个问题没人解决啊，我是docker重下了HA最新12.5的镜像，再添加了一次集成，还是无设备或实体，而且没有任何报错。但是家里设备的离线上线，HA会有通知，离谱。

这种问题能明显复现的，是好解决的，关键是看有没有什么方案，不能来一个不兼容的设备就全挂（这样子对第一次接入的人不太友好）。

**Comment by sqs1116** [comment]
我也不显示设备，貌似是晾衣架设备处理报错
![1734961504898](https://github.com/user-attachments/assets/aae2a410-f117-4824-a1cc-8ba20defcb54)

**Comment by Leofiztt866** [comment]
> 好多人都反映了这个问题没人解决啊，我是docker重下了HA最新12.5的镜像，再添加了一次集成，还是无设备或实体，而且没有任何报错。但是家里设备的离线上线，HA会有通知，离谱。

都一样一问题啊，就是不知道官方啥时候给解决啊

**Comment by zghnwsq** [comment]
请升级你的ha版本
报错AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'
我看了ha core 2024.10.2版的const.py， UnitOfConductivity类没有MICROSIEMENS_PER_CM这个单位


看起来降低了ha版本的要求，带来了兼容性问题

**Comment by hass-demacia** [comment]
> 请升级你的ha版本 报错AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM' 我看了ha core 2024.10.2版的const.py， UnitOfConductivity类没有MICROSIEMENS_PER_CM这个单位，应该是2024.11.0b1这个版本增加的
> 
> 看起来降低了ha版本的要求，带来了兼容性问题
> 
> 参考 #396

因为看到是兼容低版本才尝试使用的。我试试新版本。有结果回来反馈

**Comment by hass-demacia** [comment]
> > 请升级你的ha版本 报错AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM' 我看了ha core 2024.10.2版的const.py， UnitOfConductivity类没有MICROSIEMENS_PER_CM这个单位，应该是2024.11.0b1这个版本增加的
> > 看起来降低了ha版本的要求，带来了兼容性问题
> > 参考 #396
> 
> 因为看到是兼容低版本才尝试使用的。我试试新版本。有结果回来反馈

HA升级到12月份stable版本后没有问题了

**Comment by sqs1116** [comment]
好像最新版本没问题，10月的版本应该还是不行

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月27日 09:46 |
| 收件人 | XiaoMi/ha_xiaomi_home ***@***.***> |
| 抄送人 | sqs1116 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [XiaoMi/ha_xiaomi_home] 添加集成后，设备实体未生成问题 (Issue #388) |

请升级你的ha版本 报错AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM' 我看了ha core 2024.10.2版的const.py， UnitOfConductivity类没有MICROSIEMENS_PER_CM这个单位，应该是2024.11.0b1这个版本增加的
看起来降低了ha版本的要求，带来了兼容性问题
参考 #396

因为看到是兼容低版本才尝试使用的。我试试新版本。有结果回来反馈

HA升级到12月份stable版本后没有问题了
