### ISSUE TITLE
初始化报错

### ISSUE THREAD

**Issue by liusinpun** [XiaoMi/ha_xiaomi_home#392]
### Describe the Bug / 描述问题

登录账号完成并成功， 查看日志有实体报错

### How to Reproduce / 复现步骤

1. 正常登录
2. 进入设置页面
![image](https://github.com/user-attachments/assets/57df1096-af2b-44cb-ab05-4d37c751be99)
3. 显示异常
4. 异常日志如下
`
home-assistant  | 2024-12-23 20:28:48.365 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'blt.3.1co3hfceklc01', 'uid': 904972817, 'token': '9676ac63afc53479983d0b40', 'name': '体温计', 'pid': 6, 'mac': 'E5:94:AE:66:06:0F', 'bssid': '', 'longitude': '0.00000000', 'latitude': '0.00000000', 'show_mode': 1, 'model': 'miaomiaoce.thermo.t10', 'permitLevel': 16, 'isOnline': False, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'fw_version': '1.1.3_0068', 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1673264296, 'freqFlag': True, 'hide_mode': 0, 'cnt': 6, 'last_online': 1734347659, 'comFlag': 385, 'carPicInfo': ''}

home-assistant  | 2024-12-23 20:28:48.365 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'lumi.158d0007279888', 'uid': 904972817, 'token': '', 'name': '无线开关魔方版', 'pid': 3, 'mac': '', 'ssid': 'Xiaomi_2B4C', 'bssid': '58:EA:1F:71:3F:D0', 'longitude': '0.00000000', 'latitude': '0.00000000', 'parent_id': '463550302', 'show_mode': 1, 'model': 'lumi.sensor_cube.aqgl01', 'permitLevel': 16, 'isOnline': True, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'fw_version': '1.0.0_0005', 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1657189252, 'freqFlag': False, 'hide_mode': 0, 'cnt': 3, 'comFlag': 128, 'carPicInfo': ''}

home-assistant  | 2024-12-23 20:28:48.366 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, blt.3.1co3hfceklc01

home-assistant  | 2024-12-23 20:28:48.366 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, lumi.158d0007279888

home-assistant  | 2024-12-23 20:29:04.717 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Sinpun: 904972817 [中国大陆] for xiaomi_home

home-assistant  | Traceback (most recent call last):
home-assistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
home-assistant  |     result = await component.async_setup_entry(hass, self)

home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry

home-assistant  |     raise err

home-assistant  |   File "/config/custom_components/xiaomi_home/__init__.py", line 140, in async_setup_entry

home-assistant  |     device.spec_transform()
home-assistant  |   File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 531, in spec_transform
home-assistant  |     service_entity = self.parse_miot_service_entity(

home-assistant  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 478, in parse_miot_service_entity

home-assistant  |     prop.external_unit = self.unit_convert(prop.unit)
home-assistant  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 630, in unit_convert
home-assistant  |     unit_map['μS/cm'] = UnitOfConductivity.MICROSIEMENS_PER_CM
home-assistant  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

home-assistant  | AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'

home-assistant  | 2024-12-23 20:29:04.724 WARNING (MainThread) [py.warnings] /config/custom_components/xiaomi_home/miot/miot_cloud.py:100: RuntimeWarning: coroutine 'ClientSession.close' was never awaited

home-assistant  |   self._session.close()
home-assistant  | 

home-assistant  | 2024-12-23 20:29:04.725 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)

home-assistant  | 2024-12-23 20:29:04.725 WARNING (MainThread) [py.warnings] /config/custom_components/xiaomi_home/miot/miot_cloud.py:256: RuntimeWarning: coroutine 'ClientSession.close' was never awaited

home-assistant  |   self._session.close()
home-assistant  | 

home-assistant  | 2024-12-23 20:29:04.725 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)

home-assistant  | 2024-12-23 20:29:04.725 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector (None)

home-assistant  | 2024-12-23 20:29:05.389 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'lumi.158d0007279888', 'uid': 904972817, 'token': '', 'name': '无线开关魔方版', 'pid': 3, 'mac': '', 'ssid': 'Xiaomi_2B4C', 'bssid': '58:EA:1F:71:3F:D0', 'longitude': '0.00000000', 'latitude': '0.00000000', 'parent_id': '463550302', 'show_mode': 1, 'model': 'lumi.sensor_cube.aqgl01', 'permitLevel': 16, 'isOnline': True, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'fw_version': '1.0.0_0005', 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1657189252, 'freqFlag': False, 'hide_mode': 0, 'cnt': 3, 'comFlag': 128, 'carPicInfo': ''}

home-assistant  | 2024-12-23 20:29:05.390 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'blt.3.1co3hfceklc01', 'uid': 904972817, 'token': '9676ac63afc53479983d0b40', 'name': '体温计', 'pid': 6, 'mac': 'E5:94:AE:66:06:0F', 'bssid': '', 'longitude': '0.00000000', 'latitude': '0.00000000', 'show_mode': 1, 'model': 'miaomiaoce.thermo.t10', 'permitLevel': 16, 'isOnline': False, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'fw_version': '1.1.3_0068', 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1673264296, 'freqFlag': True, 'hide_mode': 0, 'cnt': 6, 'last_online': 1734347659, 'comFlag': 385, 'carPicInfo': ''}

home-assistant  | 2024-12-23 20:29:05.390 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, blt.3.1co3hfceklc01

home-assistant  | 2024-12-23 20:29:05.390 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, lumi.158d0007279888``

### Expected Behavior / 预期结果

无异常

### Home Assistant Logs / 系统日志

[home-assistant_2024-12-23T12-34-52.519Z.log](https://github.com/user-attachments/files/18229353/home-assistant_2024-12-23T12-34-52.519Z.log)

### Home Assistant Core Version / Home Assistant Core 版本

2024.10.2

### Home Assistant Operation System Version / Home Assistant Operation System 版本

no

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

### Additional Context / 其他说明

no

**Comment by topsworld** [comment]
您好，请将集成升级到最新版本，我们后面会升级做兼容

**Comment by liusinpun** [comment]
非常感谢 @topsworld ， 升级后已经可以使用
