### ISSUE TITLE
依然是oauth登录问题

### ISSUE THREAD

**Issue by KopHao** [XiaoMi/ha_xiaomi_home#395]
### Describe the Bug / 描述问题

修改回调地址为本地IP失败，并且尝试多次之后直接无法进入授权流程了

### How to Reproduce / 复现步骤

1. 之前通过修改回调地址为本地NAS的IP，成功了一次
2. 家里停电了设备上提示登录信息过期，今天在用相同的修改IP的办法重试怎么都不行
3. 试了多次之后直接卡在这个弹窗了
<img width="700" alt="image" src="https://github.com/user-attachments/assets/41c0c59f-42bd-4164-a50b-9c77840a591e" />

### Expected Behavior / 预期结果

咋能成功授权啊，好难

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by linkingtd** [comment]
我也是一样的问题，怎么提示认证过期，再次认证就不行了呢

**Comment by linkingtd** [comment]
此错误来自自定义集成。

日志记录器: custom_components.xiaomi_home.miot.miot_client
来源: custom_components/xiaomi_home/miot/miot_client.py:480
集成: Xiaomi Home (文档, 问题)
首次出现: 14:47:44 (15 次总计出现)
上次记录: 23:36:50

refresh oauth info error (141099665, cn), 'MIoTOauthClient' object has no attribute '_get_token_async', Traceback (most recent call last): File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 449, in refresh_oauth_info_async valid_auth_info = await self._oauth.refresh_access_token_async( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ refresh_token=auth_info['refresh_token']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 207, in refresh_access_token_async return await self._get_token_async(data={ ^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'MIoTOauthClient' object has no attribute '_get_token_async'

应该是服务端改代码了？

**Comment by linkingtd** [comment]
改好了。。。。

**Comment by will-huang9531** [comment]
> 改好了。。。。

请问如何解决的？

**Comment by yuqy96** [comment]
更新下v0.1.4b0 就好了

**Comment by will-huang9531** [comment]
> 更新下v0.1.4b0 就好了

是不是更新测试版以后就不会频繁提示重新认证了呀？

**Comment by topsworld** [comment]
您好，这个是最近一次pr引入的问题，该问题已经修复

**Comment by topsworld** [comment]
如上，可以先使用预发布版本v0.1.4b0。

**Comment by KopHao** [comment]
感谢，解决啦。
btw，发现修改浏览器地址栏IP的办法还是不如直接修改host来得直接😂
