### ISSUE TITLE
wfxx.motor.lsmk

### ISSUE THREAD

**Issue by gujiys** [XiaoMi/ha_xiaomi_home#405]
### Describe the Bug / 描述问题

缺失按键属性 0.1.0版是有，更新后没了

### How to Reproduce / 复现步骤

产品属性
https://home.miot-spec.com/spec/wfxx.motor.lsmk

![02102](https://github.com/user-attachments/assets/be40f454-ef00-4051-b191-32aa8e745728)

### Expected Behavior / 预期结果

属性齐全，可以通过nodered可以调用遥控按键

### Home Assistant Logs / 系统日志

无

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

docker coer

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by topsworld** [comment]
您好，我们本地测试是有的，这个属于非标准属性，咱是不是勾选了隐藏非标属性？后面我们会支持实体的筛选配置。
![image](https://github.com/user-attachments/assets/56f6e47a-402d-4414-8fce-9b101735be25)

**Comment by topsworld** [comment]
如上，非问题，ISSUE关闭。
