### ISSUE TITLE
All devices became unavailable after selecting 'Reload'.

### ISSUE THREAD

**Issue by Elger9** [XiaoMi/ha_xiaomi_home#407]
### Describe the Bug / 描述问题

Devices are offline after reloading

### How to Reproduce / 复现步骤

After reloading HUB:

Settings -> Devices and services -> Xiaomi Home -> Hubs - Three dots -> Reload

All devices are offline. I tried the options in 'Configure' and deleted and added the hub in 'Add Hub'. Unfortunately, this did not resolve the issue

### Expected Behavior / 预期结果

Devices should be online after reloading

### Home Assistant Logs / 系统日志
 
Logger: paho.mqtt.client
Source: custom_components/xiaomi_home/miot/miot_mips.py:781
integration: Xiaomi Home ([documentation](https://github.com/XiaoMi/ha_xiaomi_home/blob/main/README.md), [issues](https://github.com/XiaoMi/ha_xiaomi_home/issues))
First occurred: 12:27:15 AM (19 occurrences)
Last logged: 12:49:56 AM
failed to receive on socket: [Errno 104] Connection reset by peer

Logger: custom_components.xiaomi_home.miot.miot_client
Source: custom_components/xiaomi_home/miot/miot_client.py:1541
integration: Xiaomi Home ([documentation](https://github.com/XiaoMi/ha_xiaomi_home/blob/main/README.md), [issues](https://github.com/XiaoMi/ha_xiaomi_home/issues))
First occurred: 12:27:29 AM (29 occurrences)
Last logged: 12:42:27 AM

    refresh props failed, cloud, ['358387043|15|4', '358387043|7|1', '358387043|15|13', '358387043|15|8', '358387043|15|6', '358387043|15|5', '358387043|14|5', '358387043|14|4', '358387043|14|3', '358387043|14|2', '358387043|13|8', '358387043|13|7', '358387043|13|5', '358387043|13|4', '358387043|13|3', '358387043|13|2', '358387043|10|9', '358387043|10|8', '358387043|2|1', '332574920|7|1', '332574920|3|22', '332574920|3|21', '332574920|3|20', '332574920|3|17', '332574920|3|14', '332574920|3|11', '332574920|3|8', '332574920|3|7', '332574920|3|6', '332574920|3|5', '332574920|3|4', '332574920|3|3', '332574920|3|1', '358387043|15|12', '358387043|15|11', '332574920|3|19', '332574920|3|18', '332574920|3|16', '332574920|3|15']
    refresh props failed, cloud, ['group.1753436666137694208|2|6']
    refresh props failed, cloud, ['332574920|7|1', '332574920|3|22', '332574920|3|21', '332574920|3|20', '332574920|3|17', '332574920|3|14', '332574920|3|11', '332574920|3|8', '332574920|3|7', '332574920|3|6', '332574920|3|5', '332574920|3|4', '332574920|3|3', '332574920|3|1', '332574920|3|19', '332574920|3|18', '332574920|3|16', '332574920|3|15', '332574920|3|13', '332574920|3|12', '332574920|3|10', '332574920|3|9', '332574920|6|6', 'group.1753436666137694208|2|6']
    refresh props failed, cloud, ['358387043|6|6', '358387043|9|1', '358387043|9|2', '358387043|10|1', '358387043|10|2', '358387043|10|3', '358387043|10|4', '358387043|10|5', '358387043|10|6', '358387043|10|7', '358387043|13|6', '358387043|13|9', '358387043|15|1', '358387043|15|2', '358387043|15|3', '358387043|15|11', '358387043|15|12', '358387043|2|1', '358387043|10|8', '358387043|10|9', '358387043|13|2', '358387043|13|3', '358387043|13|4', '358387043|13|5', '358387043|13|7', '358387043|13|8', '358387043|14|2', '358387043|14|3', '358387043|14|4', '358387043|14|5', '358387043|15|5', '358387043|15|6', '358387043|15|8', '358387043|15|13', '358387043|7|1', '358387043|15|4']
    refresh props failed, cloud, ['332574920|7|1', '332574920|3|22', '332574920|3|21', '332574920|3|20', '332574920|3|17', '332574920|3|14', '332574920|3|11', '332574920|3|8', '332574920|3|7', '332574920|3|6', '332574920|3|5', '332574920|3|4', '332574920|3|3', '332574920|3|1', '332574920|3|19', '332574920|3|18', '332574920|3|16', '332574920|3|15', '332574920|3|13', '332574920|3|12', '332574920|3|10', '332574920|3|9', '332574920|6|6', 'group.1753436666137694208|2|6', 'blt.4.1fne6h0ccgg00|2|1']

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

Docker

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b0

### Additional Context / 其他说明

After restarting the Raspberry Pi on which I have Home Assistant running, the devices seem to be available for a while, then go offline

**Comment by Elger9** [comment]
It seems you have to wait. After a few minutes, all the devices are back online. Problem solved.

**Comment by topsworld** [comment]
Hello, it seems the problem lies in the failure of the cloud service connection. By the way, where are you from ( Login Region ) ?

**Comment by Elger9** [comment]
Europe, EU server. However, I suspect it was a problem with my LAN. I will let you know if the problem reoccurs after double-checking that my network is fine.

**Comment by Elger9** [comment]
It works fine, the problem has not reoccurred. I am closing the issue.
