### ISSUE TITLE
加湿器中的“相对湿度”不可用

### ISSUE THREAD

**Issue by qibao07** [XiaoMi/ha_xiaomi_home#409]
### Describe the Bug / 描述问题

加湿器中的“相对湿度”不可用，当前版本是v0.1.3，应该上一个版本是可以的

### How to Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/97c05ed1-6543-4a61-94ba-baedbdd7bdf7)

### Expected Behavior / 预期结果

正常显示加湿器中传感器的“相对湿度”

### Home Assistant Core Version / Home Assistant Core 版本

2024.11.1

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20241106.2

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by MarcPolaris** [comment]
米家智能除菌加湿器 deerma.humidifier.jsq2g   缺少“相对湿度”实体，当前版本是v0.1.3。

**Comment by MarcPolaris** [comment]
德业除湿机 deye.derh.z20  加湿器中的“环境参数 相对湿度”不可用，提示“集成“xiaomi_home”不再提供此实体。如果实体不再使用，可以在“设置”中删除它。”当前版本是v0.1.3，应该之前版本应该是可以的，不然不会出现这个实体。

**Comment by topsworld** [comment]
> 德业除湿机 deye.derh.z20 加湿器中的“环境参数 相对湿度”不可用，提示“集成“xiaomi_home”不再提供此实体。如果实体不再使用，可以在“设置”中删除它。”当前版本是v0.1.3，应该之前版本应该是可以的，不然不会出现这个实体。

您好，新版本支持加湿器除湿器实体显示，相关参加参数在这些实体中显示

**Comment by topsworld** [comment]
如上，非问题，ISSUE关闭

**Comment by qibao07** [comment]
@topsworld 但是加湿器除湿器实体并不是通用的传感器，有时候需要图表展示，或者写一些自动化，还是传感器方便一些
![image](https://github.com/user-attachments/assets/34d46cfc-b8e7-4036-a605-0294a42f5eb5)
