### ISSUE TITLE
小米米家智能墙壁插座 zimi.plug.zncz01缺少日电量 月电量实体

### ISSUE THREAD

**Issue by MarcPolaris** [XiaoMi/ha_xiaomi_home#411]
### Describe the Bug / 描述问题

无需描述

### How to Reproduce / 复现步骤

无需复现
<img width="664" alt="截屏2024-12-24 14 50 31" src="https://github.com/user-attachments/assets/3269cd2f-e734-4f86-86ac-28947fa0b6cf" />

### Expected Behavior / 预期结果

增加日电量 月电量实体

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

Frontend 20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by topsworld** [comment]
Duplicate of #410
