### ISSUE TITLE
小爱音箱pro无法播放文本   执行文本指令

### ISSUE THREAD

**Issue by qq173972819** [XiaoMi/ha_xiaomi_home#414]
### Describe the Bug / 描述问题

小爱音箱pro无法播放文本   执行文本指令

### How to Reproduce / 复现步骤

无法执行动作“text/set_value” 。 action exec failed, 智能音箱 播放文本(text.xiaomi_cn_604357173_lx06_play_text_a_5_1), invalid action params, 123
无法执行动作“text/set_value” 。 action exec failed, 智能音箱 执行文本指令(text.xiaomi_cn_604357173_lx06_execute_text_directive_a_5_5), invalid action params, 123123

### Expected Behavior / 预期结果

播放文本  执行命令

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b

**Comment by zghnwsq** [comment]
参考 #57

**Comment by topsworld** [comment]
非问题，请readme查看使用方法，问题关闭
