### ISSUE TITLE
能源設定

### ISSUE THREAD

**Issue by ysbledmh** [XiaoMi/ha_xiaomi_home#424]
### Describe the Bug / 描述问题

電量監控的裝置顯示實體未定義

### How to Reproduce / 复现步骤

1.到能源2.右上角...3.選擇能源設定4.電網、太陽能產量內選擇有計量用電的設備，選擇後顯示 {實體未定義}

### Expected Behavior / 预期结果

於能源標籤可看到設定的裝置，耗用的功率

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by JimmyKmi** [comment]
同
https://github.com/XiaoMi/ha_xiaomi_home/issues/325
https://github.com/XiaoMi/ha_xiaomi_home/issues/164
https://github.com/XiaoMi/ha_xiaomi_home/issues/89
https://github.com/XiaoMi/ha_xiaomi_home/issues/30
