### ISSUE TITLE
一堆故障，开发人员来看看

### ISSUE THREAD

**Issue by 5iphoto** [XiaoMi/ha_xiaomi_home#429]
### Describe the Bug / 描述问题

都是些基本的问题

### How to Reproduce / 复现步骤

任何时候都可以复现，重启homeassistant就会产生错误日志

### Expected Behavior / 预期结果

消除故障

### Home Assistant Logs / 系统日志

s2024-12-24 22:14:53.800 警告（SyncWorker_0）[homeassistant.loader]我们发现了一个自定义集成xiaomi_home，但尚未经过Home Assistant测试。此组件可能会导致稳定性问题，如果您在使用家庭助理时遇到问题，请务必禁用它2024-12-24 22:14:56.781 错误 (72338e0788d9c40b) [custom_components.xiaomi_home.miot.miot_client] 我的家，mips在6000毫秒后尝试重新连接2024-12-24 22:14:57.803 错误（主线程）[pyhap.characteristic] 目标加热冷却状态：值=0为无效值。2024-12-24 22:14:57.803 错误（主线程）[pyhap.characteristic] 目标加热冷却状态：值=0为无效值。2024-12-24 22:14:58.095 错误（主线程）[custom_components.xiaomi_home.miot.miot_client] 刷新道具失败，云，['blt.3.1i4t1vhckkg00|2|1081'，'61536346|2|3']2024-12-24 22:14:58.571 错误（主线程）[custom_components.xiaomi_home.miot.miot_device] get_prop_value错误，属性为None，热水器，water_heater.zimi_cn_832311745_h03_s_22024-12-24 22:14:58.969 错误（主线程）[custom_components.xiaomi_home.miot.miot_client]刷新道具失败，云，['1083233235|3|2'，'1102280829|3|2'，'70025798799|2|2'，'70025798799|2|2|3'，'70025798799|2|1']2024-12-24 22:15:02.823 错误 (72338e0788d9c40b) [custom_components.xiaomi_home.miot.miot_client] 我的家，mips在12000ms后尝试重新连接

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5 

### Home Assistant Operation System Version / Home Assistant Operation System 版本

无

### Xiaomi Home Integration Version / 米家集成版本

目前所有版本

**Comment by JimmyKmi** [comment]
请上传一份没有翻译的日志？这是日志基本的上传的基本要求。

**Comment by topsworld** [comment]
您好，上述为正常的错误日志，部分设备上报消息不符合标准规范，会有错误消息打印；
属性刷新失败是部分属性获取不到，会打印错误消息。
mips reconnect错误是因为发现本地存在中枢网关，但是中枢网关版本暂时不支持本地连接控制，所以连接上鉴权失败，然后断连重连。

**Comment by topsworld** [comment]
如上，非问题，后续会将一些日志降级打印。
