### ISSUE TITLE
米家智能插座增强版chuangmi.plug.v3无法显示电量统计数据

### ISSUE THREAD

**Issue by liuzhen99** [XiaoMi/ha_xiaomi_home#430]
### Describe the Bug / 描述问题

米家智能插座增强版chuangmi.plug.v3无法显示电量统计数据

### How to Reproduce / 复现步骤

![2](https://github.com/user-attachments/assets/276b4664-ee12-4e03-a477-52bf26539ae6)

### Expected Behavior / 预期结果

加入电量统计数据

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

Frontend 20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b0

**Comment by JimmyKmi** [comment]
已有大量重复反馈。设备没有统计属性上报，APP数据并非源于Spec。
同类问题请到百科查询设备是否支持相关属性上报：https://mijia.wiki/products

**Comment by JimmyKmi** [comment]
同
https://github.com/XiaoMi/ha_xiaomi_home/issues/325
https://github.com/XiaoMi/ha_xiaomi_home/issues/164
https://github.com/XiaoMi/ha_xiaomi_home/issues/89
https://github.com/XiaoMi/ha_xiaomi_home/issues/30
https://github.com/XiaoMi/ha_xiaomi_home/issues/424

**Comment by qypw** [comment]
更新插座固件就能解决的问题..小米就是这样..老设备根本不会去管你..想要好的体验..必须保持所有设备都是最新的..
