### ISSUE TITLE
小爱音箱缺少播放文本实体

### ISSUE THREAD

**Issue by windowlife** [XiaoMi/ha_xiaomi_home#434]
### Describe the Bug / 描述问题

不能让小爱音箱播放指定文本

### How to Reproduce / 复现步骤

![screenshot_2024-12-25_09-30-34](https://github.com/user-attachments/assets/79866de9-2216-4cfd-af67-959634831331)
缺少播放文本的实体

### Expected Behavior / 预期结果

增加实体

### Home Assistant Core Version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13。0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

### Additional Context / 其他说明

-

**Comment by windowlife** [comment]
点配置，更新了下设备，之后有这个实体了，但是播放文本报错
![播放文本](https://github.com/user-attachments/assets/8d383b38-4708-4681-ad51-3796eb57cf71)

**Comment by topsworld** [comment]
您好，非问题，请阅读readme或者discussion找使用教程，action有格式要求。
