### ISSUE TITLE
绿米空调伴侣缺少功耗计量 lumi.acpartner.v1  lumi.acpartner.v3

### ISSUE THREAD

**Issue by KleinerSource** [XiaoMi/ha_xiaomi_home#438]
### Describe the Bug / 描述问题

空调网关缺少功耗计量

### How to Reproduce / 复现步骤

在插件中添加绿米空调伴侣
绿米的 绿米空调伴侣 是支持功耗计量的 但是插件里不支持  miot auto支持 
lumi.acpartner.v1
lumi.acpartner.v3

### Expected Behavior / 预期结果

支持计量

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b1

**Comment by JimmyKmi** [comment]
同
https://github.com/XiaoMi/ha_xiaomi_home/issues/325
https://github.com/XiaoMi/ha_xiaomi_home/issues/164
https://github.com/XiaoMi/ha_xiaomi_home/issues/89
https://github.com/XiaoMi/ha_xiaomi_home/issues/30
https://github.com/XiaoMi/ha_xiaomi_home/issues/424

已有大量重复反馈。设备没有统计属性上报，APP数据并非源于Spec。
同类问题请到百科查询设备是否支持相关属性上报：https://mijia.wiki/products
