### ISSUE TITLE
小爱音箱pro不能播放文本

### ISSUE THREAD

**Issue by windowlife** [XiaoMi/ha_xiaomi_home#439]
### Describe the Bug / 描述问题

播放文本报错了

### How to Reproduce / 复现步骤

![播放文本](https://github.com/user-attachments/assets/1fc3a0d2-47d2-4070-98cf-075970ed9771)

### Expected Behavior / 预期结果

正常使用

### Home Assistant Core Version / Home Assistant Core 版本

2024.11.1

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13.2

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by MarcPolaris** [comment]
执行指令框里输入" ["文本指令",false]"   
播放文本框里输入" ["文本指令"]"

**Comment by windowlife** [comment]
> ["文本指令"]

按这个输入，没有报错，但是音箱没有反应

**Comment by dldui-captain** [comment]
> 执行指令框里输入" ["文本指令",false]" 播放文本框里输入" ["文本指令"]"

依然是不可以，另外不觉得反人类吗 ？

**Comment by 810517583** [comment]
> > 执行指令框里输入" ["文本指令",false]" 播放文本框里输入" ["文本指令"]"
> 
> 依然是不可以，另外不觉得反人类吗 ？

我不问之前也不知道，可能文字是字符串。执行命令的 false和true 应该是静默执行的与否

**Comment by topsworld** [comment]
设计如此，为了兼容其它设备的action命令

**Comment by MarcPolaris** [comment]
> > 执行指令框里输入" ["文本指令",false]" 播放文本框里输入" ["文本指令"]"
> 
> 依然是不可以，另外不觉得反人类吗 ？

确实，不像[hass-xiaomi-miot] 播放文本和文本指令那么方便，我现在发方法是保留[hass-xiaomi-miot]集成里的小爱音箱的播放文本和文本指令框。
