### ISSUE TITLE
[Bug]: 人体传感器没有反应。

### ISSUE THREAD

**Issue by redhatme** [XiaoMi/ha_xiaomi_home#44]
### Describe the bug / 描述问题

1，小米的人体2s 2，小米的人体存在电池版本

### To Reproduce / 复现步骤

这两个没有反应。

### Expected behavior / 预期结果

至少有一个触发时间也行

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by SusanPhevos** [comment]
您好！请发一下Home Assistant中人体传感器详情的页面截图，以及Home Assistant系统日志。

**Comment by three1bro** [comment]
我这边可以使用，但是只有事件，没有存在传感器。
![image](https://github.com/user-attachments/assets/935819f0-3586-4876-b4a2-ea1be8dd360e)

**Comment by kasimir82** [comment]
我已经尝试用event来检测无人状态的时间了, 凑合可用, 使用if template的方式来workaround: 
{{ (as_timestamp(now()) - as_timestamp(states.event.lumi_cn_lumi_xxxx_motion_detected.last_changed)) |abs |int > 600 }}

**Comment by redhatme** [comment]
![1112222](https://github.com/user-attachments/assets/0fee5277-9036-4c74-a683-c1005970721a)
这个是小米的人体存在

**Comment by redhatme** [comment]
![1112222](https://github.com/user-attachments/assets/0feadb9c-399b-4dca-94b4-302d44a72f2f)
这个是小米的人体2s.  都没有任何的反应

**Comment by redhatme** [comment]
![222222](https://github.com/user-attachments/assets/085f53b6-9df0-4bce-831e-a91e23f75b9d)
这个是小米的人体2s 。 包括事件什么的。没有任何的触发。

**Comment by topsworld** [comment]
@redhatme 您好，可以进入设置-》系统-》日志，可以看下是否存在错误信息，或者导出相关日志

**Comment by redhatme** [comment]
日志详细信息（错误）
此错误来自自定义集成。
日志记录器: custom_components.xiaomi_home.miot.miot_spec
来源: custom_components/xiaomi_home/miot/miot_spec.py:824
集成: Xiaomi Home (文档, 问题)
首次出现: 21:36:33 (1 次总计出现)
上次记录: 21:36:33

the language is not supported, zh-Hans, try using the default language, en, urn:miot-spec-v2:device:gateway:0000A019:lumi-v3:2

**Comment by redhatme** [comment]
日志详细信息（错误）
此错误来自自定义集成。
日志记录器: custom_components.xiaomi_home.miot.miot_client
来源: custom_components/xiaomi_home/miot/miot_client.py:1492
集成: Xiaomi Home (文档, 问题)
首次出现: 17:08:38 (3 次总计出现)
上次记录: 21:36:47

refresh props failed, cloud, ['545439707|6|4', '746844334|3|5', '545439707|3|3', '545439707|6|2', '545439707|6|3', 'blt.3.1i6sn1k58ck00|2|1081', 'blt.3.1inhhau7gkk00|2|1053']
refresh props failed, cloud, ['545439707|6|1']
refresh props failed, cloud, ['545439707|6|4', '746844334|3|5', '545439707|3|3', '545439707|6|2', '545439707|6|3', 'blt.3.1i6sn1k58ck00|2|1081', '545439707|6|1']

**Comment by redhatme** [comment]
就这三个错误日志

**Comment by three1bro** [comment]
> 我已经尝试用event来检测无人状态的时间了, 凑合可用, 使用if template的方式来workaround: {{ (as_timestamp(now()) - as_timestamp(states.event.lumi_cn_lumi_xxxx_motion_detected.last_changed)) |abs |int > 600 }}

我使用的group组 如果要用template就得一对一设置 还是希望直接集成

**Comment by redhatme** [comment]
> > 我已经尝试用event来检测无人状态的时间了, 凑合可用, 使用if template的方式来workaround: {{ (as_timestamp(now()) - as_timestamp(states.event.lumi_cn_lumi_xxxx_motion_detected.last_changed)) |abs |int > 600 }}
> 
> 我使用的group组 如果要用template就得一对一设置 还是希望直接集成

你的是有反应，可以根据template生成一个。我的这个是没有任何反应。所以没有办法用template

**Comment by sansuming** [comment]
我的也是没反应
![Uploading 截屏2024-12-18 23.21.56.png…]()

**Comment by redhatme** [comment]
抱歉，是我这里的问题。不知道怎么多模网关的蓝牙网关里面的功能自己关了。 默认走的小爱音箱。把多模网关的蓝牙功能打开，顺便也升了级。 就可以了。里面就有反应了。

**Comment by sansuming** [comment]
哦，谢谢，具体咋操作啊，我家的设备也是这。




★为你★&nbsp;

***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaoMi/ha_xiaomi_home"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月19日(星期四) 中午11:15
***@***.***&gt;;
抄送:&nbsp;"★为你★  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaoMi/ha_xiaomi_home] [Bug]: 人体传感器没有反应。 (Issue #44)





 
抱歉，是我这里的问题。不知道怎么多模网关的蓝牙网关里面的功能自己关了。 默认走的小爱音箱。把多模网关的蓝牙功能打开，顺便也升了级。 就可以了。里面就有反应了。

**Comment by redhatme** [comment]
看看你的是再哪个网关下面的。

**Comment by sansuming** [comment]
好的，




★为你★&nbsp;

***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaoMi/ha_xiaomi_home"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月19日(星期四) 中午11:23
***@***.***&gt;;
抄送:&nbsp;"★为你★  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaoMi/ha_xiaomi_home] [Bug]: 人体传感器没有反应。 (Issue #44)





 
看看你的是再哪个网关下面的。
