### ISSUE TITLE
小米智能门锁E20 猫眼版无离家场景按键事件

### ISSUE THREAD

**Issue by big-mouth-cn** [XiaoMi/ha_xiaomi_home#440]
### Describe the Bug / 描述问题

无离家场景按键事件

### How to Reproduce / 复现步骤

<img width="1098" alt="iShot_2024-12-25_11 45 50" src="https://github.com/user-attachments/assets/5a241300-9eba-4003-80c2-ca243a53f228" />
小米智能门锁E20 猫眼版无离家场景按键事件

### Expected Behavior / 预期结果

能够监听无离家场景按键事件

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

docker

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by JimmyKmi** [comment]
设备没有统计属性上报，APP数据并非源于Spec。
同类问题请到百科查询设备是否支持相关属性上报：https://mijia.wiki/products
