### ISSUE TITLE
小爱音箱红外自定义设备不显示，非自定义设备可正常显示

### ISSUE THREAD

**Issue by masgg** [XiaoMi/ha_xiaomi_home#443]
### Describe the Bug / 描述问题

小爱音箱红外自定义设备不显示，非自定义设备可正常显示

### How to Reproduce / 复现步骤

小爱音箱红外自定义设备不显示，非自定义设备可正常显示

### Expected Behavior / 预期结果

能支持自定义红外设备吗

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b1

**Comment by SusanPhevos** [comment]
See #380
