### ISSUE TITLE
[Bug]: 米家智能宠物喂食器无手动出粮按钮

### ISSUE THREAD

**Issue by nadav-cheung** [XiaoMi/ha_xiaomi_home#45]
### Describe the bug / 描述问题

米家智能宠物喂食器无手动出粮按钮

### To Reproduce / 复现步骤

1、集成插件
2、自动方式添加设备
3、选中米家米家智能宠物喂食器设备
4、其中无手动出粮按钮
<img width="1139" alt="image" src="https://github.com/user-attachments/assets/52beb758-dfda-491b-97ba-f53f4e4ae693" />

### Expected behavior / 预期结果

增加一个实体或按钮 可以触发手动出粮

### Home Assistant Logs / 系统日志

[home-assistant_2024-12-17T01-07-56.104Z.log](https://github.com/user-attachments/files/18158763/home-assistant_2024-12-17T01-07-56.104Z.log)

### Home Assistant Core version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by topsworld** [comment]
您好，宠物喂食器出粮操作为action，可以打开选项中【action调试模式】，用文本框先调试出粮，文本框命令格式为可以看对应的通知程序实体属性，详细操作步骤社区后续会出相关教程，可以关注下
![image](https://github.com/user-attachments/assets/c99ea7cb-548c-4b87-854c-6422d7589098)

![image](https://github.com/user-attachments/assets/a4f31a67-9ee1-4769-b525-e696f83987ed)
