### ISSUE TITLE
HA日志一直提示插件错误日志

### ISSUE THREAD

**Issue by lockpen** [XiaoMi/ha_xiaomi_home#453]
### Describe the Bug / 描述问题

ERROR (db5e1b30f36fb7b7) [custom_components.xiaomi_home.miot.miot_client] 

### How to Reproduce / 复现步骤

![Uploading 微信截图_20241225152745.png…]()

### Expected Behavior / 预期结果

不知道是哪块报错

### Home Assistant Logs / 系统日志

2024-12-24T23:12:07.275324629Z [31m2024-12-25 07:12:07.273 ERROR (db5e1b30f36fb7b7) [custom_components.xiaomi_home.miot.miot_client] 水滴的家庭, mips try reconnect after 60000ms[0m

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by topsworld** [comment]
非问题，中枢暂时不支持本地控制，所以连接失败，等待中枢支持
