### ISSUE TITLE
每隔一两天就得重新认证一次

### ISSUE THREAD

**Issue by TommyMerlin** [XiaoMi/ha_xiaomi_home#475]
### Describe the Bug / 描述问题

每隔一两天就得重新认证一次

### How to Reproduce / 复现步骤

每隔一两天就得重新认证一次
![微信图片_20241227202756](https://github.com/user-attachments/assets/3f2e2818-1aa5-4970-91fb-d2034495183d)

### Expected Behavior / 预期结果

需要重新登陆

### Reproduce Time / 问题复现的时间点

不定期

### Log Timezone / 日志时区

Asia/Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by topsworld** [comment]
您好，预发布版本v0.1.4b0及以上已修复该问题

**Comment by Maotechh** [comment]
如何在HACS里安装预发布版本 @topsworld
