### ISSUE TITLE
设置旁路由之后 xiaomi_home集成添加设备就显示“配置失败。网络连接异常，请检查设备网络配置“

### ISSUE THREAD

**Issue by Ami8834671** [XiaoMi/ha_xiaomi_home#483]
### Describe the Bug / 描述问题

设置旁路由之后,不管是更新还是 重新添加都出现下面问题

配置失败。网络连接异常，请检查设备网络配置“
看了其他的有类似问题的 改了文件也添加不了集成

### Home Assistant Logs / 系统日志

拉取不了日志

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by PhDLuffy** [comment]
dns问题，dns指向主路由

**Comment by Ami8834671** [comment]
谢谢，成功了

**Comment by topsworld** [comment]
如上，非问题。
