### ISSUE TITLE
光猫重启后就一直离线了，重启HA和插件都不行

### ISSUE THREAD

**Issue by Trymeagain** [XiaoMi/ha_xiaomi_home#512]
### Describe the Bug / 描述问题

光猫重启后就一直离线了，重启HA和插件都不行

### How to Reproduce / 复现步骤

光猫重启后就一直离线了，重启HA和插件都不行
再重启几次之后就提示验证过期了，但是一直都无法重新验证身份，跳转之后也是一直转圈，已经升级到v0.1.4b1

### Expected Behavior / 预期结果

如何重新使插件工作正常

### Reproduce Time / 问题复现的时间点

2024-12-29

### Home Assistant Logs / 系统日志

[home-assistant_2024-12-31T02-49-47.731Z.log](https://github.com/user-attachments/files/18278951/home-assistant_2024-12-31T02-49-47.731Z.log)

### Log Timezone / 日志时区

Asia/Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

2024.12.5

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b1

**Comment by topsworld** [comment]
您好，这个账号有再几个HA上登录？

**Comment by Trymeagain** [comment]
> 您好，这个账号有再几个HA上登录？

只有这一个

**Comment by Trymeagain** [comment]
> 您好，这个账号有再几个HA上登录？
把它降级到0.1.3去尝试登录也是不行
![image](https://github.com/user-attachments/assets/091f5b15-9e08-4df5-8fec-ed5e7d114d52)

**Comment by topsworld** [comment]
看错误提示，可能是本地网络问题，无法刷新token，可以检查下是否能正常访问小米服务器


![image](https://github.com/user-attachments/assets/71288e1c-9713-487a-a681-8d00c585aef5)

**Comment by topsworld** [comment]
> > 您好，这个账号有再几个HA上登录？
> > 把它降级到0.1.3去尝试登录也是不行
> > ![image](https://private-user-images.githubusercontent.com/120345588/399433690-091f5b15-9e08-4df5-8fec-ed5e7d114d52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzI2NjAsIm5iZiI6MTczNTYzMjM2MCwicGF0aCI6Ii8xMjAzNDU1ODgvMzk5NDMzNjkwLTA5MWY1YjE1LTllMDgtNGRmNS04ZmVjLWVkNWU3ZDExNGQ1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwODA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGJkYmE5NTU0NTQ5NTU3MTgwZWJiNDRlY2Q3NDkzYzQ4NGM4NTc3ODUyYTg0YTExNGYyNDI3ZDY4OTQzOWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jac5ob6zZy49Nujx4kphmHHax8IWcH3JffZneIsTyw0)

国内的话，可以尝试下访问这个网址，看下有没有错误提示：https://ha.api.io.mi.com/app/v2/ha/oauth/get_token

**Comment by Trymeagain** [comment]
> > > 您好，这个账号有再几个HA上登录？
> > > 把它降级到0.1.3去尝试登录也是不行
> > > ![image](https://private-user-images.githubusercontent.com/120345588/399433690-091f5b15-9e08-4df5-8fec-ed5e7d114d52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzI2NjAsIm5iZiI6MTczNTYzMjM2MCwicGF0aCI6Ii8xMjAzNDU1ODgvMzk5NDMzNjkwLTA5MWY1YjE1LTllMDgtNGRmNS04ZmVjLWVkNWU3ZDExNGQ1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwODA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGJkYmE5NTU0NTQ5NTU3MTgwZWJiNDRlY2Q3NDkzYzQ4NGM4NTc3ODUyYTg0YTExNGYyNDI3ZDY4OTQzOWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jac5ob6zZy49Nujx4kphmHHax8IWcH3JffZneIsTyw0)
> 
> 国内的话，可以尝试下访问这个网址，看下有没有错误提示：https://ha.api.io.mi.com/app/v2/ha/oauth/get_token

![image](https://github.com/user-attachments/assets/3b2770ed-3205-4c5a-8e08-ed90e1a3d11b)
米家设备也是都在线的

**Comment by Trymeagain** [comment]
> > > 您好，这个账号有再几个HA上登录？
> > > 把它降级到0.1.3去尝试登录也是不行
> > > ![image](https://private-user-images.githubusercontent.com/120345588/399433690-091f5b15-9e08-4df5-8fec-ed5e7d114d52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzI2NjAsIm5iZiI6MTczNTYzMjM2MCwicGF0aCI6Ii8xMjAzNDU1ODgvMzk5NDMzNjkwLTA5MWY1YjE1LTllMDgtNGRmNS04ZmVjLWVkNWU3ZDExNGQ1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwODA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGJkYmE5NTU0NTQ5NTU3MTgwZWJiNDRlY2Q3NDkzYzQ4NGM4NTc3ODUyYTg0YTExNGYyNDI3ZDY4OTQzOWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Jac5ob6zZy49Nujx4kphmHHax8IWcH3JffZneIsTyw0)
> 
> 国内的话，可以尝试下访问这个网址，看下有没有错误提示：https://ha.api.io.mi.com/app/v2/ha/oauth/get_token

我再确认授权几次之后，他又能重新添加了，又正常了
