### ISSUE TITLE
[Bug]: 无法单独删除设备

### ISSUE THREAD

**Issue by w961471797** [XiaoMi/ha_xiaomi_home#53]
### Describe the bug / 描述问题

在设备详情界面无法删除设备

### To Reproduce / 复现步骤

在设备详情界面无法删除设备
![微信截图_20241217104148](https://github.com/user-attachments/assets/9f34a7a3-7b5f-4677-878c-791d47df1329)

### Expected behavior / 预期结果

希望可以删除

### Home Assistant Logs / 系统日志

在设备管理界面无法删除单独设备
![微信截图_20241217104148](https://github.com/user-attachments/assets/bfe5d003-49b4-4941-b7f1-2678c7f30141)

### Home Assistant Core version / Home Assistant Core 版本

2024.12.2

### Home Assistant Operation System version / Home Assistant Operation System 版本

2024.11.4

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by 52216108** [comment]
我也遇到这个问题，虽然页面右上角可以禁用这个设备，但是还是会被homekit bridge显示到家庭中去。

**Comment by githubgj** [comment]
> 我也遇到这个问题，虽然页面右上角可以禁用这个设备，但是还是会被homekit bridge显示到家庭中去。

在HASS中隐藏掉，然后更新HomeKit bridge就不会显示出来了

**Comment by topsworld** [comment]
v0.1.4b1及以上支持设备过滤。
