### ISSUE TITLE
[Bug]: 无法登录小米账号

### ISSUE THREAD

**Issue by ryyusong** [XiaoMi/ha_xiaomi_home#55]
### Describe the bug / 描述问题

当前无法使用此页面 homeassistant.local 当前无法处理此请求。 HTTP ERROR 503

### To Reproduce / 复现步骤

当前无法使用此页面
homeassistant.local 当前无法处理此请求。
HTTP ERROR 503

### Expected behavior / 预期结果

登录

### Home Assistant Logs / 系统日志

当前无法使用此页面
homeassistant.local 当前无法处理此请求。
HTTP ERROR 503

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.10

### Additional context / 其他说明

当前无法使用此页面
homeassistant.local 当前无法处理此请求。
HTTP ERROR 503

**Comment by Leetfs** [comment]
此问题已有 issue, 参考：issue #8

**Comment by topsworld** [comment]
如上，问题关闭
