### ISSUE TITLE
[Bug]: 小爱音箱执行无法执行指令

### ISSUE THREAD

**Issue by bizshow** [XiaoMi/ha_xiaomi_home#57]
### Describe the bug / 描述问题

小爱音箱执行指令会报错

### To Reproduce / 复现步骤

在hass的设备页面，在执行指令的输入框中输入指令，并按下回车，弹出错误提示

无法执行动作“text/set_value” 。 action exec failed, 智能音箱 执行文本指令(text.xiaomi_cn_636727251_l04m_execute_text_directive_a_5_4), invalid action params format, 关闭客厅电视

![image](https://github.com/user-attachments/assets/ffbce7d2-9cad-4c0c-9c96-9bc93e8aa49e)

### Expected behavior / 预期结果

正确执行指令，音箱会响应执行结果

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

无

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by topsworld** [comment]
可以按照对应通知程序实体中的属性字段拼接控制命令
如，["测试"]
![image](https://github.com/user-attachments/assets/e7c893c8-5a6b-4a66-9954-5d9b66e32895)

**Comment by bizshow** [comment]
后来我仔细看readme发现了这个，感谢！

**Comment by bizshow** [comment]
> 可以按照对应通知程序实体中的属性字段拼接控制命令 如，["测试"] ![image](https://private-user-images.githubusercontent.com/32349595/396338501-e7c893c8-5a6b-4a66-9954-5d9b66e32895.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDgxNjgsIm5iZiI6MTczNDQwNzg2OCwicGF0aCI6Ii8zMjM0OTU5NS8zOTYzMzg1MDEtZTdjODkzYzgtNWE2Yi00YTY2LTk5NTQtNWQ5YjY2ZTMyODk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzRmMmYwZGFmNGE5ZWQzOTg1MDZhNDUyMTg0NzZjMDNhYTBiMzczZTE5NjA3ZWE2Y2ZiMmM0NGQ2NzU3ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DHu_VOvHhDoiZq1n0EGPS58HXzWT6c1PMweeflTHlFk)

感谢！

**Comment by bizshow** [comment]
close

**Comment by bighamx** [comment]
> 可以按照对应通知程序实体中的属性字段拼接控制命令 如，["测试"] ![image](https://github.com/user-attachments/assets/e7c893c8-5a6b-4a66-9954-5d9b66e32895)

你好 可以问一下属性 这一部分为啥我的音响没有吗 是用来什么额外的插件之类的东西吗?
