### ISSUE TITLE
[Bug]: 米家智能除湿机 13L xiaomi.derh.13l无控制实体

### ISSUE THREAD

**Issue by Peterzhangnoise** [XiaoMi/ha_xiaomi_home#59]
### Describe the bug / 描述问题

无法控制模式，无法控制目标湿度

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/9c44b52e-965e-43cb-a19f-56c484f76404)

### Expected behavior / 预期结果

可以控制模式，可以控制目标湿度

### Home Assistant Core version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by Peterzhangnoise** [comment]
同样传感器也缺少开机状态

**Comment by topsworld** [comment]
v0.1.1已适配，问题关闭

**Comment by Sd62** [comment]
#320

**Comment by Sd62** [comment]
__
