### ISSUE TITLE
[Bug]: 摄像头无法实时出流

### ISSUE THREAD

**Issue by KioZhang** [XiaoMi/ha_xiaomi_home#62]
### Describe the bug / 描述问题

家里有三款摄像头，均无法看到实时查看视频流的按钮

### To Reproduce / 复现步骤

型号1： 小米智能摄像机C700 
chuangmi.camera.81ac1
制造商：小白
固件：5.3.2_0702

型号2：小米智能摄像机 标准本2K
isa.camera.hlc7
制造商：小方
固件：4.3.2_0220

型号3：小米智能摄像头云台版 
chuangmi.camera.ipc009
制造商：小白
版本：4.0.9_0409

### Expected behavior / 预期结果

可以查看视频流

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by KioZhang** [comment]
![image](https://github.com/user-attachments/assets/523d362b-8b6e-42c9-bb56-3c7d57f176a7)
![image](https://github.com/user-attachments/assets/7d09913d-40aa-4754-acb9-15059aac8fed)
![image](https://github.com/user-attachments/assets/fc2e37d9-ee40-4a55-99bd-d26bdfde5041)
没有视频流查看框

**Comment by Oniokey** [comment]
#40
