### ISSUE TITLE
[Bug]: 显示没有设备或实体

### ISSUE THREAD

**Issue by tattoo8355** [XiaoMi/ha_xiaomi_home#63]
### Describe the bug / 描述问题

显示设置失败，没有设备或实体

### To Reproduce / 复现步骤

![PixPin_20241217_112647](https://github.com/user-attachments/assets/328e8ea2-98dc-4e69-be4b-a957d15c2987)

### Expected behavior / 预期结果

1

### Home Assistant Logs / 系统日志

[home-assistant_xiaomi_home_2024-12-17T03-27-59.081Z.log](https://github.com/user-attachments/files/18159661/home-assistant_xiaomi_home_2024-12-17T03-27-59.081Z.log)

### Home Assistant Core version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by topsworld** [comment]
您好，麻烦确认下Home Assistant Core版本是不是最新的2024.11.0

**Comment by tattoo8355** [comment]
> 您好，麻烦确认下Home Assistant Core版本是不是最新的2024.11.0

版本是2024.10.3

**Comment by topsworld** [comment]
如上，现集成core需要更新至2024.11.0及以上
