### ISSUE TITLE
[功能建议] 导入设备/更新设备列表时，支持手动勾选设备

### ISSUE THREAD

**Issue by topsworld** [XiaoMi/ha_xiaomi_home#65]
### Discussed in https://github.com/XiaoMi/ha_xiaomi_home/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **iKira** December 17, 2024</sup>
目前只能将小米账号下所有设备全部导入，不支持手动勾选，遇到设备离线时Home Assistant会频出现设备离线通知，而这些设备离线是预期内的，并不需要频繁出现通知。

hass-xiaomi-miot（https://github.com/al-one/hass-xiaomi-miot）插件目前是支持手动勾选设备的，希望小米官方插件也能支持。</div>

**Comment by nandidi1** [comment]
附议

**Comment by louisslee** [comment]
+1

**Comment by chiachunli08** [comment]
真的需要有Filter, 不然米家帳號就要夠乾淨

**Comment by bloodmao1** [comment]
+1

**Comment by wuchilai** [comment]
+1

**Comment by Superxinxing** [comment]
+1

**Comment by Superxinxing** [comment]
+1

**Comment by HankSU7889** [comment]
+1

**Comment by zyq328328** [comment]
+1

**Comment by topsworld** [comment]
v0.1.4b1支持设备过滤和通知隐藏。
