### ISSUE TITLE
[Bug]: 平头熊x6旋钮开关中的空调，没有根据规则生成空调实体

### ISSUE THREAD

**Issue by x838902** [XiaoMi/ha_xiaomi_home#67]
### Describe the bug / 描述问题

存在air-conditioner规则必须的 on、mode、target-temperature属性，但是没有生成climate实体

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/7ce13c18-3735-4cc8-bf43-0b5de0a7b1b0)

### Expected behavior / 预期结果

根据规则生成climate实体

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

0.1.0

**Comment by SusanPhevos** [comment]
090615.switch.x6ntft 这款设备的[MIoT-Spec-V2定义](https://home.miot-spec.com/spec/090615.switch.x6ntft) device instance name 是switch而不是air-conditioner，不符合`SPEC_DEVICE_TRANS_MAP`转换规则。故未生成Climate Entity。

**Comment by x838902** [comment]
> 090615.switch.x6ntft 这款设备的[MIoT-Spec-V2定义](https://home.miot-spec.com/spec/090615.switch.x6ntft) device instance name 是switch而不是air-conditioner，不符合转换规则。故未生成 Climate Entity。`SPEC_DEVICE_TRANS_MAP`

感谢解答，尝试添加规则后可以识别设备，有两个疑问：
1.对于规则配置，非标准名称是否可以做映射，比如在这个设备中 风速 是 soft-wind ，有没有办法转换为插件可以识别的名称
2.建议设备默认名称根据转换后ha中的实体类型命名更加统一
![image](https://github.com/user-attachments/assets/9dddedc8-83ec-435f-95a1-191ebb9be396)
