### ISSUE TITLE
[Bug]: 为啥红外虚拟空调,只能显示出各个按键 却没有控制实体

### ISSUE THREAD

**Issue by xxxxuanya** [XiaoMi/ha_xiaomi_home#87]
### Describe the bug / 描述问题

为啥红外虚拟空调,只能显示出各个按键 却没有控制实体

### To Reproduce / 复现步骤

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/41652fcc-0f76-48c5-af6f-7107803f445d" />

### Expected behavior / 预期结果

应该有个实体

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

### Additional context / 其他说明

<img width="819" alt="image" src="https://github.com/user-attachments/assets/62b36553-0fe7-42e0-b12a-d5ece279afc1" />
是不是少一个打开这个的实体

**Comment by JimmyKmi** [comment]
红外空调遥控没有状态，在米家与ha的定义是“红外遥控器”而不是“空调”，所以没有“空调”实体。

**Comment by JimmyKmi** [comment]
> 那能不能作为一个new feature 加上

欢迎提交PR
