### ISSUE TITLE
[Bug]: iot.switch.padw2p 浦安达单相智能保护开关没有当日耗电量、当月耗电量数据

### ISSUE THREAD

**Issue by mickey50** [XiaoMi/ha_xiaomi_home#89]
### Describe the bug / 描述问题

没有每日、当月耗电量数据，功耗参数 耗电量数据不更新

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/8b85b088-80be-428d-a80b-f5beca984c39)

### Expected behavior / 预期结果

得到相应的数据

### Home Assistant Core version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.10

### Additional context / 其他说明

Xiaomi Miot Auto 集成可以得到相应的数据
![image](https://github.com/user-attachments/assets/2831f121-b9aa-4b6c-8ee9-9ea45bb307cc)

**Comment by yizhaoyiximh** [comment]
你这是缺少参数，我那单位都不对。

**Comment by JimmyKmi** [comment]
参考https://mijia.wiki/products/iot.switch.padw2p，厂商并没有定义当日耗电量、当月耗电量数据的属性。如需该参数作为属性上报请联系厂商。

**Comment by mickey50** [comment]
> 参考[https://mijia.wiki/products/iot.switch.padw2p，厂商并没有定义当日耗电量、当月耗电量数据的属性。如需该参数作为属性上报请联系厂商。](https://mijia.wiki/products/iot.switch.padw2p%EF%BC%8C%E5%8E%82%E5%95%86%E5%B9%B6%E6%B2%A1%E6%9C%89%E5%AE%9A%E4%B9%89%E5%BD%93%E6%97%A5%E8%80%97%E7%94%B5%E9%87%8F%E3%80%81%E5%BD%93%E6%9C%88%E8%80%97%E7%94%B5%E9%87%8F%E6%95%B0%E6%8D%AE%E7%9A%84%E5%B1%9E%E6%80%A7%E3%80%82%E5%A6%82%E9%9C%80%E8%AF%A5%E5%8F%82%E6%95%B0%E4%BD%9C%E4%B8%BA%E5%B1%9E%E6%80%A7%E4%B8%8A%E6%8A%A5%E8%AF%B7%E8%81%94%E7%B3%BB%E5%8E%82%E5%95%86%E3%80%82)

Xiaomi Miot Auto 集成应该是通过小米云服务的数据统计接口取得的数据，可否考虑用同样的方式实现？
![image](https://github.com/user-attachments/assets/dcb97e39-ee2f-4775-9117-3997df43b33c)

**Comment by mickey50** [comment]
> 参考[https://mijia.wiki/products/iot.switch.padw2p，厂商并没有定义当日耗电量、当月耗电量数据的属性。如需该参数作为属性上报请联系厂商。](https://mijia.wiki/products/iot.switch.padw2p%EF%BC%8C%E5%8E%82%E5%95%86%E5%B9%B6%E6%B2%A1%E6%9C%89%E5%AE%9A%E4%B9%89%E5%BD%93%E6%97%A5%E8%80%97%E7%94%B5%E9%87%8F%E3%80%81%E5%BD%93%E6%9C%88%E8%80%97%E7%94%B5%E9%87%8F%E6%95%B0%E6%8D%AE%E7%9A%84%E5%B1%9E%E6%80%A7%E3%80%82%E5%A6%82%E9%9C%80%E8%AF%A5%E5%8F%82%E6%95%B0%E4%BD%9C%E4%B8%BA%E5%B1%9E%E6%80%A7%E4%B8%8A%E6%8A%A5%E8%AF%B7%E8%81%94%E7%B3%BB%E5%8E%82%E5%95%86%E3%80%82)
hass-xiaomi-miot的实现：
https://github.com/al-one/hass-xiaomi-miot/blob/d5a4076861b24185bd216f013ac9ad72ec12e7de/custom_components/xiaomi_miot/core/device_customizes.py#L810

**Comment by 413505805** [comment]
我的里面电压是mv自己修改后正常，缺少当月用电，当日用电等效（有一个功耗一直不更新不知道是不是这个），希望更新解决一下
![Uploading Screenshot_2024-12-18-08-13-46-367_io.homeassistant.companion.android.jpg…]()

**Comment by qleehao** [comment]
暂时可以自己添加一个辅助元素，用积分传感器计算点功率，可以得到kWh的耗电量

**Comment by olonglongo** [comment]
> 暂时可以自己添加一个辅助元素，用积分传感器计算电功率，可以得到kWh的耗电量

Hello, could you share an example? I'd really appreciate it for reference.

**Comment by olonglongo** [comment]
> > > 暂时可以自己添加一个辅助元素，用积分传感器计算电功率，可以得到kWh的耗电量
> > 
> > 
> > Hello, could you share an example? I'd really appreciate it for reference.
> 
> ![屏幕截图 2025-01-08 153751](https://private-user-images.githubusercontent.com/93974419/401051827-0cac0e2d-a0a8-4824-9bf4-91afb4f0a98d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMjI0NDcsIm5iZiI6MTczNjMyMjE0NywicGF0aCI6Ii85Mzk3NDQxOS80MDEwNTE4MjctMGNhYzBlMmQtYTBhOC00ODI0LTliZjQtOTFhZmI0ZjBhOThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDA3NDIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMWJjODNhZGQyZmI2OGVjNGJhZjRhMzg2ZDY4MjkzNWZkOTM3MjY5YzU5ZjVhOWE5N2FlZmQ4YTQ0NzE1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BF2i64J1kHzSp1C4Misuzu1EmIrdHHiqYd7DMaV4OSU)

It's very good, but it would be even better if there were YAML files!

**Comment by qleehao** [comment]
> It's very good, but it would be even better if there were YAML files!

sensor:
  - platform: integration
    source: sensor.current_power
    name: energy_spent
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5

This should work, but I haven't tested it.

see: https://www.home-assistant.io/integrations/integration/

**Comment by smresultwithout** [comment]
目前还未修复，有同样问题

**Comment by leafyelin** [comment]
我的也是同样获取不到用电量
