### ISSUE TITLE
射频遥控器按键缺失

### ISSUE THREAD

**Issue by juzi214032** [XiaoMi/ha_xiaomi_home#90]
### Describe the bug / 描述问题

这个射频遥控器在ha的操作只有一个pasue，实际上在米家中一共是有4个按键的

### To Reproduce / 复现步骤

![IMG_8026](https://github.com/user-attachments/assets/42232f44-98d2-4c84-8dec-1a8b50ccbebf)

### Expected behavior / 预期结果

能操作4个按键

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.1

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by juzi214032** [comment]
![IMG_8023](https://github.com/user-attachments/assets/087617de-8f69-4b21-9f8d-6926a7015f5b)

**Comment by juzi214032** [comment]
@JimmyKmi 在app上触发了对应按键，但这几个按键的状态值并没有变更，看起来不是修改他们的状态值

**Comment by JimmyKmi** [comment]
> @JimmyKmi 在app上触发了对应按键，但这几个按键的状态值并没有变更，看起来不是修改他们的状态值

这个取决于设备开发者，看起来他们没有提供状态的上报。所以虽然定义了状态但是还是一个事件。

**Comment by juzi214032** [comment]
@JimmyKmi 试出来了，需要先把按键设置为 Unset，再设置为 Set，才代表把按键按下，想问下针对这种 case ，除了自己尝试，有什么办法从其他地方知道这种规则吗？比如抓包或者其他文档之类的

**Comment by JimmyKmi** [comment]
> @JimmyKmi 试出来了，需要先把按键设置为 Unset，再设置为 Set，才代表把按键按下，想问下针对这种 case ，除了自己尝试，有什么办法从其他地方知道这种规则吗？比如抓包或者其他文档之类的

暂时还没有，这种一般是厂商定义出来的用法。你可以尝试看看米物百科（mijia.wiki）或者其小程序版对设备展示的参数，是否能看出规律。如果看出来了欢迎分享~

**Comment by ericsyy** [comment]
如果有小米的中枢网关或者小爱音响的话可以使用另一种方法实现控制此设备（这里举例中枢网关）
1. 在米家自动化中创建自动化，触发事件为中枢的自定义虚拟事件如`开门`，执行为射频遥控器的开门操作。创建完成后应该可以看到本条自动化显示‘本地’字样。
2. 在ha中对 Xiaomi 中枢网关 虚拟服务 产生虚拟事件发送消息`["开门"]`，即可实现本地化操作射频遥控器，最后可以绑定对应的自定义实体实现开关门操作

如果使用小爱音响的话就必须在联网状态下才能实现。
当然，如果能联系到射频遥控器的厂家让他们进行改进那必然是更好了
