### ISSUE TITLE
[Bug]: 小爱音箱播放文本,执行文本指令功能失效

### ISSUE THREAD

**Issue by xietiancn** [XiaoMi/ha_xiaomi_home#91]
### Describe the bug / 描述问题

目前发现xiaomi sound 及小爱音箱万能遥控板

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/8cd60f14-8fb7-4944-a253-12061e709651)
这里和对应的实体设置,都会提示错误
![image](https://github.com/user-attachments/assets/5941f7d6-91c3-473f-969a-6c5de85bb2d0)

### Expected behavior / 预期结果

预期应如xiaomi-miot-auto插件那样,可以直接触发使其播放指定文本或执行指定指令

### Home Assistant Core version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by zghnwsq** [comment]
参考  #57

**Comment by topsworld** [comment]
如上，问题关闭

**Comment by ericsyy** [comment]
> > 参考 #57
> 
> 看了一下,没看懂,可以详细说一下步骤吗

![image](https://github.com/user-attachments/assets/822320de-a24d-40cd-9e76-db5b61488c96)
如上图

**Comment by zghnwsq** [comment]
> > > 参考 #57
> > 
> > 
> > 看了一下,没看懂,可以详细说一下步骤吗
> 
> ![image](https://private-user-images.githubusercontent.com/30077485/396443997-822320de-a24d-40cd-9e76-db5b61488c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDYyOTEsIm5iZiI6MTczNDUwNTk5MSwicGF0aCI6Ii8zMDA3NzQ4NS8zOTY0NDM5OTctODIyMzIwZGUtYTI0ZC00MGNkLTllNzYtZGI1YjYxNDg4Yzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA3MTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOTk4NzlmMzI2ODYyZGE3OTQ2ODQzNDMzZjljOGZkZjhjMjk3ODI2MGNmNGMyYjgxYzkyYTY4Y2I3NTU4YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DOJtBUEC5aWHMLNFa6YTvgdRNpLoE5XIY75L0Aqrimw) 如上图

这是个action，接收["测试“]这样的参数。说明文档写了打开Action 调试模式，Notify 实体详情页中 Attributes 会显示输入参数的格式。
