### ISSUE TITLE
[Bug]: 实体名、友好名称，都无法区分是哪一个滤芯。

### ISSUE THREAD

**Issue by devang2** [XiaoMi/ha_xiaomi_home#94]
### Describe the bug / 描述问题

4个滤芯的友好名称是一样的

### To Reproduce / 复现步骤

点进设备里查看
控制
滤芯 重置滤芯
滤芯 重置滤芯
滤芯 重置滤芯
滤芯 重置滤芯

### Expected behavior / 预期结果

PP棉滤芯、前置活性炭滤芯、后置活性炭滤芯、RO反渗透滤芯

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

无

### Xiaomi Home integration version / 米家集成版本

v0.1.0

### Additional context / 其他说明

实体名、友好名称，都无法区分是哪一个滤芯。

控制
滤芯 重置滤芯
滤芯 重置滤芯
滤芯 重置滤芯
滤芯 重置滤芯

type: entities
entities:

entity: button.yunmi_cn_1283268_v2_reset_filter_life_a_3_1
name: " 滤芯 重置滤芯"
entity: button.yunmi_cn_1283268_v2_reset_filter_life_a_5_1
name: " 滤芯 重置滤芯"
entity: button.yunmi_cn_1283268_v2_reset_filter_life_a_6_1
name: " 滤芯 重置滤芯"
entity: button.yunmi_cn_1283268_v2_reset_filter_life_a_7_1
name: " 滤芯 重置滤芯"
title: 小米净水器厨上版2

**Comment by JimmyKmi** [comment]
参考：https://note.p.lzj.ac.cn/s/bd635048-ae38-43c9-9f31-d61175a01cf6/doc/6k65ash5bge5ocn5a6a5lmj6zsz6kv562j-rpH7aJptHy
如不满足文档描述条件请继续跟进

**Comment by al-one** [comment]
这些名称都是厂商在米家开放平台定义的，云米太懒了，三个重置动作定义了一样的名字。

**Comment by devang2** [comment]
@al-one 还用着你的Xiaomi Miot Auto呢。
