### ISSUE TITLE
[Bug]: 中枢网关虚拟事件发生时无法看到具体的事件内容

### ISSUE THREAD

**Issue by ericsyy** [XiaoMi/ha_xiaomi_home#96]
### Describe the bug / 描述问题

中枢网关虚拟事件发生时无法看到具体的事件内容

### To Reproduce / 复现步骤

1. 在中枢网关执行产生虚拟事件("test")
![image](https://github.com/user-attachments/assets/58dc1f8b-2706-48e7-b9e1-b6f2cd9044b5)
2. 在ha中只能收到事件，但无法收到具体的事件内容("test")
![image](https://github.com/user-attachments/assets/4ad4991e-917d-40c4-928f-f60cdccca66d)

### Expected behavior / 预期结果

在ha中收到事件的同时收到事件内容

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by mickey50** [comment]
event的属性里面可以得到的

**Comment by xietiancn** [comment]
> event的属性里面可以得到的

请教在哪里可以查看的到

**Comment by ericsyy** [comment]
> event的属性里面可以得到的

确实有，非常感谢！
![image](https://github.com/user-attachments/assets/e76f9707-7ade-4882-a505-065fafdb52f3)

**Comment by mickey50** [comment]
> > event的属性里面可以得到的
> 
> 请教在哪里可以查看的到

![95c7b18b2f5f3dc03ff3030d9cb5bf1](https://github.com/user-attachments/assets/0a65440f-8cc5-47a6-9c35-7a245f7132c5)

**Comment by xietiancn** [comment]
> > > event的属性里面可以得到的
> > 
> > 
> > 请教在哪里可以查看的到
> 
> ![95c7b18b2f5f3dc03ff3030d9cb5bf1](https://private-user-images.githubusercontent.com/6166901/396458605-0a65440f-8cc5-47a6-9c35-7a245f7132c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzEzODksIm5iZiI6MTczNDQzMTA4OSwicGF0aCI6Ii82MTY2OTAxLzM5NjQ1ODYwNS0wYTY1NDQwZi04Y2M1LTQ3YTYtOWMzNS03YTI0NWY3MTMyYzUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMTAyNDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGMxYzhhMWVmZmVkMzJhYTEzY2U2MWNjMzJlMzg3YTI3NTdjYjc4MTA3NjY0NTc5NzBlMTViNDM4NDIxYjBlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HOX-ISzztXfDECnHNW15CmNu8iCopQKWsS60JUpr2Zg)

谢谢你

**Comment by JimmyKmi** [comment]
完整触发+执行方法参考： https://note.p.lzj.ac.cn/s/bd635048-ae38-43c9-9f31-d61175a01cf6/doc/5lit5p6i572r5ywz6jma5ouf5lql5lu26kem5yr5yk5omn6kgm-BBcVquoizJ

**Comment by JimmyKmi** [comment]
> > 完整触发+执行方法参考： https://note.p.lzj.ac.cn/s/bd635048-ae38-43c9-9f31-d61175a01cf6/doc/5lit5p6i572r5ywz6jma5ouf5lql5lu26kem5yr5yk5omn6kgm-BBcVquoizJ
> 
> @JimmyKmi 这个文章里面写的接收虚拟事件的方法，如果一个事件连续触发多次，是接收不到的，因为事件名称没有变化

我测试过是可以用的，虚拟事件名称不存在状态。如果有更好的方法欢迎提出，我更新到文章里。

**Comment by juzi214032** [comment]
> 我测试过是可以用的，虚拟事件名称不存在状态。如果有更好的方法欢迎提出，我更新到文章里。

@JimmyKmi 我刚又测试了下还是不行，一直触发一个事件，只会执行一次

**Comment by JimmyKmi** [comment]
> > 我测试过是可以用的，虚拟事件名称不存在状态。如果有更好的方法欢迎提出，我更新到文章里。
> 
> 
> 
> @JimmyKmi 我刚又测试了下还是不行，一直触发一个事件，只会执行一次
> 
> 

OK，我待会再复测一下。如果你有解决方案可以提出，我更改下文章。

**Comment by xietiancn** [comment]
> > > 我测试过是可以用的，虚拟事件名称不存在状态。如果有更好的方法欢迎提出，我更新到文章里。
> > 
> > 
> > @JimmyKmi 我刚又测试了下还是不行，一直触发一个事件，只会执行一次
> 
> OK，我待会再复测一下。如果你有解决方案可以提出，我更改下文章。

的确是,同一虚拟事件多次产生,因为事件名称没有变化,所以ha里自动化触发设置事件名称变化, 是不会再次接收到的,只会接收第一次,我的方法是触发检测虚拟事件任何状态,在执行操作里再去判断是什么具体事件
![image](https://github.com/user-attachments/assets/6c371d27-dd02-47d9-9c85-528cf71e67b0)

![image](https://github.com/user-attachments/assets/2251fd22-27eb-4aeb-ae02-f68b05cbdb2b)
注意看两张图都成功触发,并且是同一事件的连续触发.

执行操作如下设置
![image](https://github.com/user-attachments/assets/56e98036-8298-4fab-8c49-a81200b17290)

**Comment by juzi214032** [comment]
@xietiancn 这样可行，但有个缺点就是这个自动化会总是被触发（虽然最后没执行动作），去自动化跟踪那里看执行记录的时候就不太方便了，理想情况是直接不要触发

**Comment by xietiancn** [comment]
> @xietiancn 这样可行，但有个缺点就是这个自动化会总是被触发（虽然最后没执行动作），去自动化跟踪那里看执行记录的时候就不太方便了，理想情况是直接不要触发

目前没想到更好的方式,或者就是上面的那位说得,每次发事件再发一个当做重置,但是那个更麻烦了

**Comment by JimmyKmi** [comment]
@xietiancn @juzi214032 @mickey50 感谢几位的提醒，新的案例已经更新到文档
https://note.p.lzj.ac.cn/s/bd635048-ae38-43c9-9f31-d61175a01cf6/doc/5lit5p6i572r5ywz6jma5ouf5lql5lu26kem5yr5yk5omn6kgm-BBcVquoizJ

**Comment by StereoApp** [comment]
> @xietiancn @juzi214032 @mickey50 感谢几位的提醒，新的案例已经更新到文档 https://note.p.lzj.ac.cn/s/bd635048-ae38-43c9-9f31-d61175a01cf6/doc/5lit5p6i572r5ywz6jma5ouf5lql5lu26kem5yr5yk5omn6kgm-BBcVquoizJ

感谢文档，有个typo，文档中举的例子，事件格式为 [“虚拟事件“]，使用的双引号不是直立引号，直接复制应该是不行。

**Comment by JimmyKmi** [comment]
> > @xietiancn @juzi214032 @mickey50 感谢几位的提醒，新的案例已经更新到文档 https://note.p.lzj.ac.cn/s/bd635048-ae38-43c9-9f31-d61175a01cf6/doc/5lit5p6i572r5ywz6jma5ouf5lql5lu26kem5yr5yk5omn6kgm-BBcVquoizJ
> 
> 感谢文档，有个typo，文档中举的例子，事件格式为 [“虚拟事件“]，使用的双引号不是直立引号，直接复制应该是不行。

感谢反馈，已修正 √
